(()=>{'use strict';const D='kathleenStartDesktopV42',M='kathleenStartMobileV42',isMob=()=>matchMedia('(max-width:900px)').matches,key=()=>isMob()?M:D;
function state(){try{return Object.assign({panels:['schedule','todos'],tools:['whiteboard','classes','quest','observations','material','games'],hidden:[]},JSON.parse(localStorage.getItem(key())||'{}'))}catch(e){return{panels:['schedule','todos'],tools:['whiteboard','classes','quest','observations','material','games'],hidden:[]}}}function save(s){localStorage.setItem(key(),JSON.stringify(s))}
function init(){document.body.classList.add('start-v42');const shell=document.querySelector('.shell');if(!shell)return;
 const side=document.createElement('aside');side.className='start-sidebar';side.innerHTML='<a class="start-brand" href="./"><i>✦</i><span>Kathleens<strong>magische Kiste</strong></span></a><div class="start-side-label">MEIN UNTERRICHT</div><nav>'+nav('home','⌂','Start')+'<a href="tools/timetable/"><i>▦</i>Stundenplan</a><a href="tools/class-cockpit/"><i>♧</i>Meine Klassen</a><a href="tools/classroom-board/"><i>▣</i>Whiteboard</a><a href="tools/quest-mode/"><i>✦</i>Quest Mode</a><a href="tools/mobile-observations/"><i>◉</i>Beobachtungen</a>'+nav('library','▤','Material & Aufgaben')+nav('tools','⌘','Quiz & Spiele')+'</nav><div class="start-side-bottom">'+nav('manage','⚙','Einstellungen')+'<small>Gemeinsam lernen.<br>Gemeinsam wachsen.</small></div>';document.body.prepend(side);
 const top=document.createElement('header');top.className='start-top';top.innerHTML='<div class="start-crumb"><b>Meine Kiste</b><span>/</span><b>Start</b></div><div class="start-top-actions"><label class="start-search">⌕<input placeholder="In deiner Kiste suchen..."></label><span class="start-avatar">K</span><b>Kathleen⌄</b><button class="start-preview">Layoutvorschau</button></div>';shell.prepend(top);
 document.querySelectorAll('[data-start-view]').forEach(x=>x.onclick=e=>{e.preventDefault();document.querySelector('.nav-btn[data-view="'+x.dataset.startView+'"]')?.click()});document.querySelectorAll('[data-start-nav]').forEach(x=>x.onclick=e=>{e.preventDefault();document.querySelector('.nav-btn[data-view="'+x.dataset.startNav+'"]')?.click()});
 let edit=false;const layout=document.getElementById('startLayout'),tools=document.getElementById('startTools'),dock=document.getElementById('startHiddenDock');
 function apply(){const s=state();s.panels.forEach(id=>{const e=document.querySelector('[data-start-card="'+id+'"]');if(e)layout.appendChild(e)});s.tools.forEach(id=>{const e=document.querySelector('[data-start-tool="'+id+'"]');if(e)tools.insertBefore(e,document.getElementById('startAddTool'))});document.querySelectorAll('[data-start-tool]').forEach(e=>e.style.display=s.hidden.includes(e.dataset.startTool)?'none':'');dock.querySelector('div').innerHTML=s.hidden.map(id=>'<button data-restore="'+id+'">＋ '+id+'</button>').join('');dock.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>{const q=state();q.hidden=q.hidden.filter(x=>x!==b.dataset.restore);save(q);apply()})}
 document.getElementById('startCustomize').onclick=()=>{edit=!edit;document.body.classList.toggle('start-editing',edit);document.getElementById('startCustomize').textContent=edit?'✓ Fertig':'⚙ Startseite anpassen';document.querySelectorAll('.start-tool').forEach(e=>e.draggable=edit&&!isMob())};
 document.querySelectorAll('[data-start-card]').forEach(card=>card.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const s=state(),i=s.panels.indexOf(card.dataset.startCard),j=Math.max(0,Math.min(s.panels.length-1,i+Number(b.dataset.move)));s.panels.splice(j,0,s.panels.splice(i,1)[0]);save(s);apply()}));
 document.querySelectorAll('[data-start-tool]').forEach(t=>{t.addEventListener('dragstart',e=>{if(!edit){e.preventDefault();return}e.dataTransfer.setData('text/plain',t.dataset.startTool);t.classList.add('dragging')});t.addEventListener('dragend',()=>t.classList.remove('dragging'));t.addEventListener('dragover',e=>{if(edit)e.preventDefault()});t.addEventListener('drop',e=>{if(!edit)return;e.preventDefault();const id=e.dataTransfer.getData('text/plain'),s=state(),a=s.tools.indexOf(id),b=s.tools.indexOf(t.dataset.startTool);if(a<0||b<0)return;s.tools.splice(b,0,s.tools.splice(a,1)[0]);save(s);apply()});t.querySelector('em').onclick=e=>{if(!edit)return;e.preventDefault();const s=state(),id=t.dataset.startTool;s.hidden=[...new Set([...s.hidden,id])];save(s);apply()}});
 document.getElementById('startAddTool').onclick=()=>{if(!edit){document.getElementById('startCustomize').click();return}dock.scrollIntoView({behavior:'smooth',block:'center'})};
 top.querySelector('input').oninput=e=>{const q=e.target.value.trim();if(!q)return;const search=document.getElementById('search');if(search){search.value=q;search.dispatchEvent(new Event('input'));document.querySelector('.nav-btn[data-view="library"]')?.click()}};
 apply()}
 function nav(v,i,t){return '<a '+(v==='home'?'class="active" ':'')+'href="#'+v+'" data-start-nav="'+v+'"><i>'+i+'</i>'+t+'</a>'}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();