(()=>{'use strict';
const g=window.KathleenGamification,lists=window.KathleenClassLists,root=document.getElementById('quest');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=x=>Number(x||0).toLocaleString('de-DE');
const percent=(n,d)=>Math.max(0,Math.min(100,Number(d)>0?Number(n)/Number(d)*100:0));
const bar=(n,d,label)=>`<div class="bar" role="progressbar" aria-label="${esc(label)}" aria-valuemin="0" aria-valuemax="${esc(d)}" aria-valuenow="${Math.min(d,Math.max(0,n))}"><span style="width:${percent(n,d)}%"></span></div>`;
let search='',timer=0;
function notice(message){clearTimeout(timer);document.getElementById('notice').textContent=message;timer=setTimeout(()=>document.getElementById('notice').textContent='',4500)}
function picker(){const active=lists.getGlobalClass(),loaded=lists.load(),rows=loaded.length?loaded:lists.classMeta();return `<label class="class-picker"><span>AKTIVE KLASSE</span><select id="questClass" aria-label="Aktive Klasse"><option value="">Klasse wählen</option>${rows.map(r=>`<option value="${esc(r.id)}" ${active?.id===r.id?'selected':''}>${esc(r.name)}</option>`).join('')}</select></label>`}
function header(c){return `<section class="quest-head"><div class="title-group"><span class="emblem" aria-hidden="true">🏆</span><div><span class="eyebrow">${c?'KLASSE '+esc(c.name):'DEINE KLASSENQUEST'}</span><h1>Quest Mode${c?'<span class="active-pill">AKTIV</span>':''}</h1><p class="subtitle">Gemeinsam lernen. Gemeinsam leveln.</p></div></div><div class="head-actions">${picker()}${c?`<a class="button primary" href="../gamification-beamer/?class=${encodeURIComponent(c.id)}" target="_blank" rel="noopener">▣ Beamer öffnen</a>`:'<button data-do="unlock">🔓 Klassen entsperren</button>'}</div></section>`}
function student(st){const name=g.firstName(st.name),initial=Array.from(name)[0]||'';return `<article class="student-card" data-student-id="${esc(st.id)}" data-student-name="${esc(name.toLocaleLowerCase('de-DE'))}"><div class="student-head"><span class="avatar" aria-hidden="true">${esc(initial)}</span><div><h3 class="student-name">${esc(name)}</h3><span class="student-level">Level ${num(st.level)} · Streak ${num(st.streak)}</span></div></div><div class="student-xp"><b>${num(st.xp)} XP</b><span>${num(250-st.xp%250)} bis Level ${st.level+1}</span></div>${bar(st.xp%250,250,'Level-Fortschritt von '+name)}<div class="student-controls"><button data-action="participation" data-student="${esc(st.id)}" aria-label="${esc(name)}: Mitarbeit +15 XP">＋ Mitarbeit</button><button data-action="quiz_correct" data-student="${esc(st.id)}" aria-label="${esc(name)}: Quiz +10 XP">🧠</button></div><details><summary>Profil & weitere Aktionen</summary><div class="tags">${(st.badges||[]).map(b=>`<span>${esc(b.icon)} ${esc(b.title)}</span>`).join('')}${(st.powerups||[]).map(p=>`<span>${esc(p==='boost'?'⚡ XP Boost':p==='shield'?'🛡 Combo Shield':p)}</span>`).join('')}</div><div class="tags">${g.missions.map(m=>`<span>${esc(m.icon)} ${esc(m.title)} · ${num(st.missions?.[m.id]?.progress)}/${m.target}</span>`).join('')}</div><div class="button-row">${['challenge','learning_game','teamwork','bonus'].map(k=>`<button data-action="${k}" data-student="${esc(st.id)}">${esc(g.actions[k].label)} +${g.actions[k].xp}</button>`).join('')}<button data-adjust="${esc(st.id)}">−10 XP korrigieren</button>${st.level>=3?`<button data-mystery="${esc(st.id)}">🎁 Mystery Box</button>`:''}${st.rewards?.some(r=>r.type==='homework-voucher'&&r.status==='claimable')?`<button data-voucher="${esc(st.id)}">🎟 Gutschein</button>`:''}</div></details></article>`}
function draw(){
 const focused=document.activeElement,focusData=focused?.tagName==='BUTTON'?{...focused.dataset}:null,focusId=focused?.id,selection=focusId==='studentSearch'?focused.selectionStart:null;
 const open=[...root.querySelectorAll('.student-card details[open]')].map(x=>x.closest('[data-student-id]').dataset.studentId);
 const c=g.current(),s=g.load();
 if(!c){const selected=lists.getGlobalClass();root.innerHTML=header(null)+`<section class="empty"><h2>${selected?'Klassenliste für '+esc(selected.name||'die aktive Klasse')+' laden':'Welche Klasse startet die Quest?'}</h2><p>${selected?'Entsperre die Klassenlisten, um mit den gespeicherten Schülerinnen, Schülern und Quest-Fortschritten dieser Klasse weiterzumachen.':'Wähle oben eine deiner Klassen aus. Falls noch keine Klassen angezeigt werden, entsperre zuerst deine Klassenlisten.'}</p><div class="button-row"><button class="primary" data-do="unlock">🔓 Klassenlisten entsperren</button><a class="button" href="../class-lists/">Klassenlisten öffnen</a></div></section>`;return}
 const students=Object.values(c.students),xpInLevel=c.classXp%250,b=c.boss,w=c.weekly;
 root.innerHTML=header(c)+`
 <section class="hero" aria-label="Gemeinsame Klassenreise"><div class="hero-copy"><h2>Auf zum nächsten Level!</h2><p>Ihr sammelt gemeinsam XP – für mehr Wissen, mehr Teamgeist und magische Momente.</p></div><div class="hero-progress"><div class="level-shield"><small>LEVEL</small><b>${num(c.level)}</b></div><div class="hero-meter"><div class="meter-label"><span>KLASSENFORTSCHRITT</span><span>LEVEL ${c.level+1}</span></div>${bar(xpInLevel,250,'Klassenfortschritt zum nächsten Level')}<div class="meter-caption"><b>${num(c.classXp)} / ${num(c.level*250)} XP</b><small>Noch ${num(250-xpInLevel)} XP bis zum nächsten Level</small></div></div></div><div class="milestones" aria-hidden="true">${Array.from({length:6},(_,i)=>`<span class="milestone ${percent(xpInLevel,250)>=i*20?'complete':''}">${i===5?'✦':percent(xpInLevel,250)>=i*20?'✓':'·'}</span>`).join('')}</div><div class="hero-flag"><b>✧ ${b.done?'BOSS BESIEGT':b.active?'BOSS CHALLENGE':'DEINE KLASSENREISE'}</b>${b.active?num(b.progress)+' / '+num(b.target)+' Treffer':'Gemeinsam weiterkommen'}</div></section>
 <section class="quick-actions" aria-label="XP-Aktionen für die ganze Klasse">${['participation','quiz_correct','challenge','learning_game','teamwork','bonus'].map(k=>`<button data-action="${k}" aria-label="Klasse: ${esc(g.actions[k].label)} +${g.actions[k].xp} XP"><strong>${g.actions[k].icon} +${g.actions[k].xp} XP</strong><small>${esc(g.actions[k].label)}</small></button>`).join('')}</section>
 <div class="section-grid"><section class="card boss-card"><div class="card-top"><h2>👾 Boss-Challenge</h2><small>${b.done?'Geschafft!':b.active?'Aktiv':'Bereit'}</small></div><div class="boss-detail"><span class="boss-icon" aria-hidden="true">${b.done?'🏆':'👾'}</span><div><h3>${esc(b.title)}</h3><p>Quiz, Lernspiele und Challenges<br>bringen euch gemeinsam ans Ziel.</p></div></div>${bar(b.progress,b.target,'Boss-Fortschritt')}<div class="statline"><span>${num(b.progress)} / ${num(b.target)} Treffer</span><span>+${num(b.reward)} Klassen-XP</span></div><div class="button-row"><button class="primary" data-do="boss" ${b.active?'disabled':''}>${b.active?'Challenge läuft':b.done?'Neue Challenge starten':'Boss-Challenge starten'}</button></div></section>
 <section class="card weekly-card"><div class="card-top"><h2>🎯 Wochenziel</h2><small>${esc(w.week)}</small></div><p class="weekly-title">${esc(w.title)}</p><span class="muted">Jeder Beitrag zählt.</span>${bar(w.progress,w.target,'Wochenziel')}<div class="statline"><span>${num(w.progress)} / ${num(w.target)} XP</span><b>${w.done?'✓ Geschafft':Math.floor(percent(w.progress,w.target))+' %'}</b></div><span class="reward">✦ ${w.done||w.rewardClaimed?'Bereits erhalten: ':'Belohnung: '}+${num(w.reward)} Klassen-XP</span><div class="button-row" style="margin-top:12px"><button data-do="weekly-reset" ${w.progress||w.done?'':'disabled'}>↶ Wochenziel zurücksetzen</button></div></section>
 <section class="card combo-card"><div class="card-top"><h2>🔥 Eure Combo</h2></div><div class="combo-number">${num(c.combo)}×</div><p>Erfolgreiche Aktionen in Folge.<br>Ihr wachst über euch hinaus!</p><button data-do="combo">Combo zurücksetzen</button></section></div>
 <section class="card students-section"><div class="students-heading"><div><h2>Schülerübersicht <span class="muted">· ${students.length}</span></h2><p>Individuell fördern. Gemeinsam wachsen. Nur in deiner Lehreransicht.</p></div><label class="search"><span aria-hidden="true">⌕</span><input id="studentSearch" type="search" placeholder="Schüler suchen …" aria-label="Schüler suchen" value="${esc(search)}"></label></div><div class="student-grid">${students.map(student).join('')}</div><p class="no-results" id="noResults" hidden>Keine passenden Schüler gefunden.</p>${students.length?'':'<p class="muted">Diese Klassenliste enthält noch keine Schüler. <a href="../class-lists/">Klassenliste bearbeiten →</a></p>'}</section>
 <div class="activity-section"><section class="card"><div class="card-top"><h2>♧ Teams der Klasse</h2><button data-do="teams">${c.teams.length?'Neu einteilen':'Teams bilden'}</button></div>${c.teams.length?c.teams.map(t=>`<div class="team-row"><span>${esc(t.name)}</span><span class="muted">${t.members.filter(id=>c.students[id]).length} Mitglieder</span></div>`).join(''):'<p class="muted">Erstelle Teams aus der aktuellen Klassenliste.</p>'}</section><section class="card"><div class="card-top"><h2>✦ Letzte Ereignisse</h2><small>Klasse ${esc(c.name)}</small></div><ol class="activity-list">${c.events.slice(-4).reverse().map(e=>`<li><time>${esc(new Date(e.at).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}))}</time><span class="xp-tag">+${num(e.amount)} XP</span><span>${esc(e.reason)}</span></li>`).join('')||'<li class="muted">Eure nächsten Erfolge erscheinen hier.</li>'}</ol></section></div>
 <footer class="footer"><div class="button-row"><a class="button" href="../classroom-board/">▣ Whiteboard öffnen</a><button data-do="undo" ${c.undoHistory?.length?'':'disabled'}>↶ Letzte Aktion zurück</button><details><summary>⚙ Einstellungen</summary><div class="settings-menu"><label><input data-setting="sound" type="checkbox" ${s.settings.sound?'checked':''}> Sound</label><label><input data-setting="haptics" type="checkbox" ${s.settings.haptics!==false?'checked':''}> Haptik</label><button data-do="backup">Quest-Backup herunterladen</button><a class="button" href="../gamification-remote/">Schnellsteuerung öffnen</a></div></details></div><a class="button" href="../../">← Zurück zur Kiste</a></footer>`;
 root.querySelectorAll('.student-card').forEach(x=>{if(open.includes(x.dataset.studentId))x.querySelector('details').open=true});
 filter();if(focusData&&Object.keys(focusData).length){const next=[...root.querySelectorAll('button')].find(b=>Object.entries(focusData).every(([k,v])=>b.dataset[k]===v));next?.focus({preventScroll:true})}if(focusId){const next=document.getElementById(focusId);if(next){next.focus({preventScroll:true});if(selection!==null)try{next.setSelectionRange(selection,selection)}catch{}}}
}
function filter(){let count=0;root.querySelectorAll('[data-student-name]').forEach(el=>{el.hidden=!el.dataset.studentName.includes(search.toLocaleLowerCase('de-DE'));if(!el.hidden)count++});const empty=document.getElementById('noResults');if(empty)empty.hidden=count>0||!search}
root.addEventListener('input',e=>{if(e.target.id==='studentSearch'){search=e.target.value;filter()}});
root.addEventListener('change',e=>{if(e.target.id==='questClass'){const rows=lists.load().length?lists.load():lists.classMeta(),r=rows.find(x=>x.id===e.target.value);lists.setGlobalClass(r?.id||'',r?.name||'');search='';g.activate();draw()}if(e.target.dataset.setting)g.settings(e.target.dataset.setting,e.target.checked)});
root.addEventListener('click',async e=>{const button=e.target.closest('button');if(!button||button.disabled)return;try{
 if(button.dataset.action){g.action(button.dataset.action,button.dataset.student||'');return}
 if(button.dataset.adjust){g.adjust(button.dataset.adjust,-10);return}
 if(button.dataset.mystery){g.mystery(button.dataset.mystery);return}
 if(button.dataset.voucher){const c=g.current();g.voucher(c.students[button.dataset.voucher],c);return}
 switch(button.dataset.do){
 case 'unlock':button.disabled=true;await lists.requireUnlock();await g.restore();g.activate();draw();break;
 case 'weekly-reset':{const c=g.current();if(!c)break;const paid=c.weekly.done||c.weekly.rewardClaimed;const message='Wochenziel für Klasse '+c.name+' ('+c.weekly.week+') zurücksetzen?\n\nNur der Wochenfortschritt von '+num(c.weekly.progress)+' XP wird auf 0 gesetzt. Schüler-XP, Klassen-XP und Boss-Fortschritt bleiben erhalten.'+(paid?'\nDie Wochenbelohnung bleibt erhalten und wird diese Woche nicht erneut vergeben.':'')+'\n\nDu kannst den Reset über „Letzte Aktion zurück“ rückgängig machen.';if(window.confirm(message)){if(g.resetWeekly({classId:c.id,week:c.weekly.week}))notice('Wochenziel zurückgesetzt. Mit „Letzte Aktion zurück“ rückgängig machen.');else notice('Die Klasse oder Woche hat sich geändert oder das Wochenziel ist bereits bei 0.')}break;}
 case 'boss':g.boss(true);break;
 case 'combo':g.resetCombo();break;
 case 'undo':if(!g.undo())notice('Keine Aktion zum Zurücknehmen vorhanden.');break;
 case 'teams':if(!g.current()?.students||!Object.keys(g.current().students).length){notice('Die Klassenliste enthält noch keine Schüler.');break}g.teams(4);break;
 case 'backup':{const data=g.backup(),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='quest-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Quest-Backup wurde erstellt.');break}
 }
 }catch(error){notice('Die Aktion konnte nicht gespeichert werden. '+(error.message||'Bitte erneut versuchen.'));button.disabled=false}});
window.addEventListener('kathleen:gamification',draw);
for(const event of ['kathleen:globalclass','kathleen:classlists'])window.addEventListener(event,()=>{g.activate();draw()});
window.addEventListener('kathleen:classlists-unlocked',async()=>{await g.restore();g.activate();draw()});
window.addEventListener('storage',e=>{if([g.key,'kathleenGlobalClassV1','kathleenClassRosterCacheV37'].includes(e.key))draw()});
sessionStorage.setItem('kathleenGamificationPreviewV1','1');g.activate();draw();
})();
