import test from 'node:test';
import assert from 'node:assert/strict';
import {createHandler,digest,encrypt,decrypt} from '../supabase/functions/canva-connect/handler.mjs';
const origin='https://whiteboard.example',key=Buffer.alloc(32,7).toString('base64');
function fixture(){
  const rows=new Map(),calls=[];
  const store={authenticate:async p=>p==='correct',cleanup:async now=>{for(const [id,r]of rows)if(r.expires_at<now)rows.delete(id);},insert:async r=>rows.set(r.token_hash,structuredClone(r)),get:async h=>structuredClone(rows.get(h)),update:async(h,p)=>{if(rows.has(h))Object.assign(rows.get(h),p);},remove:async h=>rows.delete(h),lock:async(h,now)=>{const r=rows.get(h);if(r.lock_until>=now)return false;r.lock_until=now+120000;return true;}};
  let mode='normal';
  const request=async(url,options={})=>{
    calls.push({url:String(url),...options});
    if(mode==='expired')return Response.json({error:'invalid_grant'},{status:400});
    if(mode==='network')throw Error('Network failed');
    if(mode==='rate')return new Response('{}',{status:429});
    if(String(url).endsWith('oauth/token'))return Response.json({access_token:'PRIVATE_ACCESS',refresh_token:'PRIVATE_REFRESH',expires_in:3600});
    if(String(url).endsWith('oauth/revoke'))return new Response(null,{status:200});
    if(String(url).includes('/designs?'))return Response.json({items:[{id:'DESIGN',title:'Unterricht',urls:{edit_url:'PRIVATE_URL'},thumbnail:{url:'https://example.org/preview.png'}}],continuation:'next-page'});
    if(String(url).endsWith('/exports'))return Response.json({job:{id:'JOB'}});
    if(String(url).endsWith('/exports/JOB'))return Response.json({job:{status:mode==='export-fail'?'failed':'success',urls:['https://downloads.canva.com/test.pdf']}});
    if(String(url).endsWith('test.pdf'))return new Response(mode==='bad-pdf'?'not a PDF':'%PDF-1.7 test',{headers:{'content-type':'application/pdf'}});
    throw Error('Unexpected request '+url);
  };
  const vars={CANVA_CLIENT_ID:'client',CANVA_CLIENT_SECRET:'secret',CANVA_TOKEN_KEY:key,CANVA_REDIRECT_URI:origin+'/canva-callback.html'};
  const handler=createHandler({store,env:n=>vars[n],fetch:request});
  const send=(action,body={},session='',source=origin)=>handler(new Request(origin+'/api',{method:'POST',headers:{Origin:source,'x-canva-session':session,'Content-Type':'application/json'},body:JSON.stringify({action,...body})}));
  const connect=async()=>{const res=await send('connect',{passphrase:'correct'});assert.equal(res.status,200);const data=await res.json();return {...data,state:new URL(data.url).searchParams.get('state')};};
  const login=async()=>{const c=await connect();assert.equal((await send('callback',{state:c.state,code:'code'},c.session)).status,200);return c;};
  return{rows,calls,vars,send,connect,login,setMode:m=>mode=m};
}
test('tokens encrypt with authentication and do not survive a wrong key',async()=>{const data=await encrypt({secret:'private'},key);assert(!JSON.stringify(data).includes('private'));assert.deepEqual(await decrypt(data,key),{secret:'private'});await assert.rejects(decrypt(data,Buffer.alloc(32,8).toString('base64')));});
test('configuration, CORS and admin password gate OAuth',async()=>{const f=fixture();assert.equal((await f.send('connect',{passphrase:'bad'})).status,403);assert.equal((await f.send('config',{},'','https://attacker.example')).status,403);delete f.vars.CANVA_CLIENT_SECRET;assert.equal((await f.send('config')).status,503);assert.equal(f.rows.size,0);});
test('OAuth uses PKCE, read-only scopes and hashed session IDs',async()=>{const f=fixture(),c=await f.connect(),u=new URL(c.url),row=f.rows.get(await digest(c.session));assert.equal(u.origin,'https://www.canva.com');assert.equal(u.searchParams.get('code_challenge'),await digest(row.verifier));assert.equal(u.searchParams.get('code_challenge_method'),'s256');assert.equal(u.searchParams.get('scope'),'design:meta:read design:content:read');assert(!f.rows.has(c.session));assert(!JSON.stringify(c).includes('PRIVATE'));});
test('OAuth rejects forged state, other sessions and replay',async()=>{const f=fixture(),a=await f.connect(),b=await f.connect();assert.equal((await f.send('callback',{code:'code',state:a.state},b.session)).status,400);assert.equal((await f.send('callback',{code:'code',state:'forged'},a.session)).status,400);assert.equal((await f.send('callback',{code:'code',state:a.state},a.session)).status,200);assert.equal((await f.send('callback',{code:'code',state:a.state},a.session)).status,400);const row=f.rows.get(await digest(a.session));assert.equal(row.verifier,null);assert(!JSON.stringify(row).includes('PRIVATE_ACCESS'));});
test('expired OAuth attempts and expired browser sessions are rejected',async()=>{const f=fixture(),c=await f.connect(),row=f.rows.get(await digest(c.session));row.pending_until=0;assert.equal((await f.send('callback',{state:c.state,code:'code'},c.session)).status,400);row.expires_at=0;assert.equal((await f.send('status',{},c.session)).status,401);assert.equal((await f.send('designs')).status,401);});
test('design search is encoded, paginated and strips private design links',async()=>{const f=fixture(),c=await f.login(),res=await f.send('designs',{query:'Raum & Zeit',continuation:'page/2'},c.session),data=await res.json();assert.equal(data.continuation,'next-page');assert.equal(data.items[0].title,'Unterricht');assert(!JSON.stringify(data).includes('PRIVATE'));const u=new URL(f.calls.at(-1).url);assert.equal(u.searchParams.get('query'),'Raum & Zeit');assert.equal(u.searchParams.get('continuation'),'page/2');});
test('expired access token refreshes once and concurrent requests do not reuse refresh tokens',async()=>{const f=fixture(),c=await f.login(),row=f.rows.get(await digest(c.session));row.credentials=await encrypt({access_token:'old',refresh_token:'refresh',expires_at:0},key);await f.send('designs',{},c.session);assert.equal(f.calls.filter(x=>x.body?.get?.('grant_type')==='refresh_token').length,1);row.lock_until=Date.now()+60000;assert.equal((await f.send('designs',{},c.session)).status,409);row.lock_until=0;await f.send('designs',{},c.session);assert.equal(f.calls.filter(x=>x.body?.get?.('grant_type')==='refresh_token').length,1);});
test('exports and downloads are bound to the authenticated session',async()=>{const f=fixture(),a=await f.login(),b=await f.login();assert.equal((await f.send('export',{designId:'../escape'},a.session)).status,400);const result=await f.send('export',{designId:'DESIGN'},a.session);assert.equal((await result.json()).jobId,'JOB');assert.equal((await f.send('download',{jobId:'JOB'},b.session)).status,403);assert.equal((await f.send('export-status',{jobId:'JOB'},a.session)).status,200);const file=await f.send('download',{jobId:'JOB',url:'http://localhost/private'},a.session);assert.equal(file.status,200);assert((await file.text()).startsWith('%PDF-'));assert(!f.calls.some(c=>c.url.includes('localhost')));});
test('export errors, unexpected files and rate limits return actionable failures',async()=>{const f=fixture(),c=await f.login();await f.send('export',{designId:'DESIGN'},c.session);f.setMode('export-fail');assert.equal((await f.send('export-status',{jobId:'JOB'},c.session)).status,422);f.setMode('bad-pdf');assert.equal((await f.send('download',{jobId:'JOB'},c.session)).status,502);f.setMode('rate');assert.equal((await f.send('designs',{},c.session)).status,429);assert.equal(f.rows.get(await digest(c.session)).lock_until,0);});
test('disconnect revokes credentials before deleting the connection',async()=>{const f=fixture(),c=await f.login();f.setMode('network');assert.equal((await f.send('disconnect',{},c.session)).status,503);assert.equal(f.rows.size,1);f.setMode('normal');assert.equal((await f.send('disconnect',{},c.session)).status,200);assert.equal(f.rows.size,0);assert.equal((await f.send('designs',{},c.session)).status,401);assert(f.calls.some(c=>c.url.endsWith('oauth/revoke')));});

test('a revoked refresh token prompts reconnection instead of endless retries',async()=>{const f=fixture(),c=await f.login(),row=f.rows.get(await digest(c.session));row.credentials=await encrypt({access_token:'old',refresh_token:'revoked',expires_at:0},key);f.setMode('expired');const result=await f.send('designs',{},c.session);assert.equal(result.status,401);assert.match((await result.json()).error,/erneut verbinden/);assert.equal(row.lock_until,0);});
