const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const root=path.join(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
test('bulk extractor captures positional PDF lines and preprocesses images locally',()=>{const js=read('tools/english-bulk-extractor/english-bulk-extractor.js'),html=read('tools/english-bulk-extractor/index.html');assert.match(html,/english-content-extractor-v3-core\.js/);for(const marker of ['pdfLayoutLines','bbox','zone','prepareImage','imageMetrics','ocr_preprocessed'])assert.ok(js.includes(marker),marker);assert.doesNotMatch(js,/openai\.com|anthropic\.com/i)});
test('mobile quick review offers gestures, buttons, undo and never swipe-deletes',()=>{const html=read('tools/english-knowledge-base/index.html'),js=read('tools/english-knowledge-base/quick-review.js');for(const id of ['quickReviewStart','quickLater','quickEdit','quickAccept','quickUndo','quickBulk'])assert.ok(html.includes(`id="${id}"`),id);assert.match(js,/ArrowRight/);assert.match(js,/ArrowLeft/);assert.match(js,/pointerdown/);assert.match(js,/function undo/);assert.doesNotMatch(js,/Library\.remove/)});
test('reanalysis preserves manual fields and requires an explicit apply action',()=>{const html=read('tools/english-knowledge-base/index.html'),js=read('tools/english-knowledge-base/reanalysis.js');assert.match(html,/Mit Extractor V3 erneut analysieren/);assert.match(js,/manualFields/);assert.match(js,/notFoundInLatestAnalysis/);assert.match(js,/reanalyzeApply/)});
test('exercise workshop exposes all modes, levels, sequences and draft-only saving',()=>{const html=read('tools/english-exercise-generator/index.html'),js=read('tools/english-exercise-generator/exercise-generator.js'),core=read('tools/english-exercise-generator-core.js'),sw=read('service-worker.js');for(const value of ['similar','new_context','transfer','easy','medium','hard'])assert.ok(html.includes(`value="${value}"`),value);assert.match(js,/buildSequence/);assert.match(core,/reviewStatus:'needs_review'/);assert.match(sw,/english-exercise-generator\/index\.html/)});
test('private sync migration enforces ownership, update checks and private previews',()=>{const sql=read('supabase/migrations/202609290002_english_extractor_v3_private_sync.sql');assert.match(sql,/enable row level security/i);assert.match(sql,/to authenticated using \(\(select auth\.uid\(\)\)=user_id\)/i);assert.match(sql,/with check \(\(select auth\.uid\(\)\)=user_id\)/i);assert.match(sql,/english-kb-previews','english-kb-previews',false/);assert.match(sql,/security invoker/i);assert.match(sql,/revoke all on function .* from public,anon/i);assert.doesNotMatch(sql,/service_role|security definer/i)});
test('sync client excludes original documents and reports unresolved conflicts',()=>{const js=read('tools/english-knowledge-base/english-kb-sync.js');assert.match(js,/function sanitize/);assert.doesNotMatch(js,/absolutePath/);assert.match(js,/conflicts/);assert.match(js,/Original-PDFs/);assert.match(js,/source_sha256/);assert.match(js,/english-kb-previews/)});
test('offline cache version and V3 assets are registered',()=>{const sw=read('service-worker.js');assert.match(sw,/kathleen-v123-welcome-artwork-20260930/);for(const asset of ['english-content-extractor-v3-core.js','quick-review.js','reanalysis.js','english-kb-sync.js','english-exercise-generator-core.js'])assert.ok(sw.includes(asset),asset)});
