const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const code=fs.readFileSync('tools/lesson-mode.js','utf8');
const KEY='kathleenLessonModeV1',LOG='kathleenLessonEventsV1',LAST='kathleenLastLessonV1';
function fixture(){
 const store=new Map(),emitted=[],warnings=[],classes=new Set(['show']);let failKey='',throwListener=false;
 const active={id:'qa-lesson',lessonId:'qa-slot',classId:'qa-class',className:'QA Klasse',subject:'Testfach',room:'QA Raum',start:'08:00',end:'09:00',startedAt:'2026-09-22T08:00:00Z',status:'active'};
 store.set(KEY,JSON.stringify(active));store.set(LOG,JSON.stringify([{id:'qa-event',lessonId:active.id,type:'observation',student:'QA Person',at:active.startedAt},{id:'qa-homework',lessonId:active.id,type:'homework',student:'QA Person',at:active.startedAt}]));
 const elements={lessonModeBar:{classList:{remove:x=>classes.delete(x),add:x=>classes.add(x)}},lessonModeTitle:{},lessonModeRoom:{},lessonModeTime:{}};
 const window={KathleenClassLists:{getClassroomState:()=>({connectedCount:2,rosterCount:3})},addEventListener(){},dispatchEvent(e){emitted.push(e);if(throwListener&&e.type==='kathleen:lessonevent')throw Error('Optional integration failed');}};
 const ctx={window,localStorage:{getItem:k=>store.get(k)||null,setItem(k,v){if(failKey===k)throw Error('Storage unavailable');store.set(k,String(v));},removeItem(k){if(failKey===k)throw Error('Storage unavailable');store.delete(k);}},document:{readyState:'loading',addEventListener(){},getElementById:id=>elements[id]||null},CustomEvent:class{constructor(type,options){this.type=type;this.detail=options.detail;}},console:{error:(...a)=>warnings.push(a),warn:(...a)=>warnings.push(a)},location:{pathname:'/tools/classroom-board/'},setInterval(){},Date};
 vm.runInNewContext(code,ctx);
 return{api:window.KathleenLessonMode,store,emitted,warnings,classes,active,window,fail:key=>failKey=key,throwListener:()=>throwListener=true};
}
test('summary is a detached serializable snapshot even when assigned to its source',()=>{const h=fixture(),lesson=h.api.get();lesson.runtime=lesson;lesson.summary=h.api.summary(lesson);assert.doesNotThrow(()=>JSON.stringify(lesson.summary));assert.notEqual(lesson.summary.x,lesson);assert.equal(lesson.summary.x.runtime,undefined);assert.equal(lesson.summary.x.summary,undefined);lesson.subject='Changed';assert.equal(lesson.summary.x.subject,'Testfach');assert.equal(lesson.summary.observations,1);assert.equal(lesson.summary.homework,1);});
test('finish stores a complete summary and clears active mode before notifying integrations',()=>{const h=fixture();const original=h.window.dispatchEvent;h.window.dispatchEvent=e=>{assert.equal(h.store.has(KEY),false);assert.equal(JSON.parse(h.store.get(LAST)).status,'ended');original(e);};assert.equal(h.api.finish(),true);const saved=JSON.parse(h.store.get(LAST));assert.equal(saved.summary.x.id,h.active.id);assert.equal(saved.summary.x.status,'ended');assert.equal(saved.summary.connected,2);assert.equal(saved.summary.roster,3);assert.equal(saved.summary.events.filter(e=>e.type==='lesson_end').length,1);assert.equal(h.classes.has('show'),false);assert.equal(h.emitted.filter(e=>e.type==='kathleen:lessonevent').length,1);assert.equal(h.api.finish(),false);assert.equal(h.emitted.filter(e=>e.type==='kathleen:lessonevent').length,1);});
test('retry recovers the active lesson from the old circular-reference bug without duplicate end events',()=>{const h=fixture(),old=JSON.parse(h.store.get(LOG));old.push({id:'old-end',lessonId:h.active.id,type:'lesson_end',at:'2026-09-22T09:00:00Z'},{id:'old-end-again',lessonId:h.active.id,type:'lesson_end'});h.store.set(LOG,JSON.stringify(old));assert.equal(h.api.finish(),true);const events=JSON.parse(h.store.get(LOG)).filter(e=>e.type==='lesson_end');assert.equal(events.length,1);assert.equal(events[0].id,'old-end');assert.equal(events[0].classId,h.active.classId);});
test('archive, log and active-state storage failures preserve a retryable lesson and send no completion',()=>{for(const failed of [LAST,LOG,KEY]){const h=fixture();h.fail(failed);assert.equal(h.api.finish(),false);assert.equal(h.api.get().status,'active');assert.equal(h.emitted.length,0);h.fail('');assert.equal(h.api.finish(),true);assert.equal(JSON.parse(h.store.get(LOG)).filter(e=>e.type==='lesson_end').length,1);assert.equal(h.emitted.filter(e=>e.type==='kathleen:lessonevent').length,1);}});
test('a throwing optional integration cannot undo a successful finish',()=>{const h=fixture();h.throwListener();assert.equal(h.api.finish(),true);assert.equal(h.api.get(),null);assert.equal(JSON.parse(h.store.get(LAST)).status,'ended');assert.equal(h.warnings.length,1);});
test('missing Classroom counters cannot block the serializable summary',()=>{const h=fixture();h.window.KathleenClassLists.getClassroomState=()=>{throw Error('Classroom offline');};assert.equal(h.api.finish(),true);assert.equal(JSON.parse(h.store.get(LAST)).summary.connected,0);});
