// Isolated regression fixtures. Never loaded by the app or written to a live browser profile.
const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const code=fs.readFileSync('tools/gamification-preview.js','utf8');
function harness(){
 const data=new Map(),session=new Map(),events={};let selected={id:'qa-a',name:'QA A'},rows=[{...selected,students:['__qa_01__','__qa_02__']},{id:'qa-b',name:'QA B',students:['__qa_03__']}];
 const storage=m=>({getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)});
 const window={addEventListener:(k,f)=>events[k]=f,dispatchEvent:()=>{},KathleenClassLists:{load:()=>rows,getGlobalClass:()=>selected,isUnlocked:()=>false}};
 const ctx={window,localStorage:storage(data),sessionStorage:storage(session),document:{currentScript:{src:'https://example.org/tools/gamification-preview.js'},readyState:'loading',addEventListener:()=>{},getElementById:()=>null,createElement:()=>({classList:{add(){}},remove(){}}),body:{appendChild(){}}},location:{search:'',pathname:'/tools/quest-mode/'},URL,URLSearchParams,CustomEvent:class{},setTimeout:()=>0,clearTimeout(){},navigator:{},requestAnimationFrame:()=>{},console,Date};
 vm.runInNewContext(code,ctx);return {g:window.KathleenGamification,select:x=>selected=x,rows:x=>rows=x,data,window,listeners:events};
}
const plain=x=>JSON.parse(JSON.stringify(x));
test('No class selection and unavailable selected roster never award another class',()=>{const h=harness();h.select(null);h.g.action('participation');assert.equal(Object.keys(h.g.load().classes).length,0);h.g.load();h.select({id:'missing',name:'Missing'});h.g.action('participation');assert.equal(Object.keys(h.g.load().classes).length,0)});
test('Class and student XP persist, remain isolated, and undo is exact',()=>{const h=harness();h.g.activate();const before=plain(h.g.current());const id=Object.keys(before.students)[0];h.g.action('participation',id);assert.equal(h.g.current().classXp,15);assert.equal(h.g.current().students[id].xp,15);h.select({id:'qa-b',name:'QA B'});assert.equal(h.g.current().classXp,0);h.select({id:'qa-a',name:'QA A'});assert.equal(h.g.current().classXp,15);assert.ok(h.g.undo());const after=plain(h.g.current());delete after.undoHistory;assert.deepEqual(after,before)});
test('Undo restores mission bonus, consumed boost, streak, badges and student level',()=>{const h=harness();h.g.activate();const id=Object.keys(h.g.current().students)[0];h.g.action('participation',id);h.g.action('participation',id);let state=h.g.load();state.classes['qa-a'].students[id].xp=230;state.classes['qa-a'].students[id].powerups=['boost'];h.g.save(state);const before=plain(h.g.current());h.g.action('participation',id);let st=h.g.current().students[id];assert.equal(st.xp,285);assert.equal(st.level,2);assert.equal(st.missions.p3.done,true);assert.equal(st.powerups.length,0);h.g.undo();assert.deepEqual(plain(h.g.current()),before)});
test('Goal rewards update level and undo restores boss and weekly completion',()=>{const h=harness();h.g.activate();let s=h.g.load(),c=s.classes['qa-a'];c.classXp=490;c.weekly.progress=490;c.boss.active=true;c.boss.progress=9;h.g.save(s);const before=plain(h.g.current());h.g.action('quiz_correct');c=h.g.current();assert.equal(c.classXp,750);assert.equal(c.level,4);assert.equal(c.boss.done,true);assert.equal(c.weekly.done,true);h.g.undo();const after=plain(h.g.current());delete after.undoHistory;assert.deepEqual(after,before)});
test('Unknown student, negative, infinite, and unknown actions cannot award XP',()=>{const h=harness();h.g.activate();const before=plain(h.g.current());h.g.action('participation','unknown');h.g.addXP({amount:Infinity});h.g.addXP({amount:-10});h.g.action('not-an-action');assert.deepEqual(plain(h.g.current()),before)});
test('Roster reorder preserves identity and removed students cannot receive XP',()=>{const h=harness();h.g.activate();let id=Object.keys(h.g.current().students)[0];h.g.action('participation',id);h.rows([{id:'qa-a',name:'QA A',students:['__qa_02__','__qa_01__']}]);assert.equal(h.g.current().students[id].xp,15);h.rows([{id:'qa-a',name:'QA A',students:['__qa_02__']}]);h.g.action('participation',id);assert.equal(h.g.current().classXp,15)});
test('Undo cannot discard a later boss or correction operation',()=>{const h=harness();h.g.action('quiz_correct');h.g.boss();assert.equal(h.g.undo(),false);assert.equal(h.g.current().boss.active,true)});
test('Secure restore accepts saved progress when local state is absent',async()=>{const h=harness();const state=plain(h.g.load());state.updatedAt='2020-01-01T00:00:00Z';state.classes.persisted={classXp:42};h.window.KathleenClassLists.isUnlocked=()=>true;h.window.KathleenClassLists.secureGet=async()=>state;h.window.KathleenClassLists.secureSet=async()=>{throw Error('Must not overwrite backup')};assert.equal(await h.g.restore(),true);assert.equal(h.g.load().classes.persisted.classXp,42)});
test('Weekly reset is scoped, preserves all other progress, and can be undone exactly',()=>{const h=harness();h.g.activate();const id=Object.keys(h.g.current().students)[0];h.g.addXP({amount:170,studentId:id});const before=plain(h.g.current());h.select({id:'qa-b',name:'QA B'});h.g.action('quiz_correct');const other=plain(h.g.current());h.select({id:'qa-a',name:'QA A'});assert.equal(h.g.resetWeekly({classId:'qa-b'}),false);assert.equal(h.g.resetWeekly({week:'2000-W01'}),false);assert.ok(h.g.resetWeekly({classId:'qa-a',week:before.weekly.week}));const after=plain(h.g.current());assert.equal(after.weekly.progress,0);for(const key of ['students','classXp','level','boss','combo','events','teams'])assert.deepEqual(after[key],before[key]);h.select({id:'qa-b',name:'QA B'});assert.deepEqual(plain(h.g.current()),other);h.select({id:'qa-a',name:'QA A'});assert.ok(h.g.undo());assert.deepEqual(plain(h.g.current()),before)});
test('Reset retains a paid weekly bonus and cannot pay it twice, including legacy completed weeks',()=>{for(const legacy of [false,true]){const h=harness();h.g.addXP({amount:500});let s=h.g.load();if(legacy){delete s.classes['qa-a'].weekly.rewardClaimed;h.g.save(s)}assert.equal(h.g.current().classXp,600);h.g.resetWeekly();assert.equal(h.g.current().classXp,600);assert.equal(h.g.current().weekly.rewardClaimed,true);assert.equal(h.g.current().weekly.done,false);h.g.addXP({amount:500});assert.equal(h.g.current().classXp,1100);assert.equal(h.g.current().weekly.done,true);h.g.undo();assert.equal(h.g.current().weekly.progress,0);assert.equal(h.g.current().weekly.rewardClaimed,true);h.g.undo();assert.equal(h.g.current().weekly.progress,500);assert.equal(h.g.current().classXp,600)}});
test('Unpaid week still rewards once after reset and a new week is eligible again',()=>{const h=harness();h.g.addXP({amount:170});h.g.resetWeekly();h.g.addXP({amount:500});assert.equal(h.g.current().classXp,770);let s=h.g.load();s.classes['qa-a'].weekly.week='2000-W01';h.g.save(s);h.g.addXP({amount:500});assert.equal(h.g.current().classXp,1370);assert.equal(h.g.current().weekly.progress,500)});
test('Reset at zero and without an available class is a no-op',()=>{const h=harness();h.g.activate();const before=plain(h.g.load());assert.equal(h.g.resetWeekly(),false);assert.deepEqual(plain(h.g.load()),before);h.select(null);assert.equal(h.g.resetWeekly(),false)});


test('lesson completion updates the lesson class only once, even after class selection changes',()=>{const h=harness();h.g.activate();h.select({id:'qa-b',name:'QA B'});const event={detail:{type:'lesson_end',lessonId:'qa-lesson-end',classId:'qa-a'}};h.listeners['kathleen:lessonevent'](event);h.listeners['kathleen:lessonevent'](event);assert.equal(h.g.load().classes['qa-a'].streak,1);assert.equal(h.g.current().streak,0);h.listeners['kathleen:lessonevent']({detail:{...event.detail,classId:'missing'}});assert.equal(h.g.current().streak,0);});
test('gamification failures at lesson end stay inside the optional listener',()=>{const h=harness();h.data.set(h.g.key,JSON.stringify({version:3,classes:null}));assert.doesNotThrow(()=>h.listeners['kathleen:lessonevent']({detail:{type:'lesson_end',classId:'qa-a',lessonId:'qa-broken-game'}}));});
