(()=>{'use strict';
const VERSION='2.0.0',MAX_BYTES=20*1024*1024,MAX_PAGES=100,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={catalog:null,pages:[],file:null,sha:'',imports:[],existingTopics:[],duplicate:false,ocr:null};
function status(text,kind='neutral'){const el=$('#backendStatus');el.textContent=text;el.className='badge '+kind}
async function json(url){const r=await fetch(url);if(!r.ok)throw Error('Knowledge-Base-Katalog konnte nicht geladen werden.');return r.json()}
function gradeRows(){return state.catalog?.grades||[]}
function fillGrades(){const select=$('#grade');select.innerHTML=gradeRows().map(g=>`<option value="${g.grade}">Klasse ${g.grade}</option>`).join('');select.onchange=()=>{fillChapters();loadImports()};fillChapters()}
function fillChapters(){const grade=gradeRows().find(g=>Number(g.grade)===Number($('#grade').value));const chapters=[...(grade?.chapters||[])];$('#chapter').innerHTML=chapters.map(c=>`<option value="${esc(c.id)}" data-path="${esc(c.data)}">${esc(c.title)}</option>`).join('');$('#chapter').onchange=loadImports}
async function loadImports(){const id=$('#chapter').value;if(!id)return;try{state.imports=await KathleenHistoryImports.importsForChapter(id);state.duplicate=state.imports.some(x=>x.source_sha256===state.sha);const path=$('#chapter').selectedOptions[0]?.dataset.path;if(path){const canonical=await json('../../data/history/'+path);state.existingTopics=KathleenHistoryImports.merge(canonical,state.imports).topics}status('History-KB verbunden','green');updateDuplicate()}catch(e){state.imports=[];state.existingTopics=[];status('SQL-Migration noch nicht eingerichtet','yellow');$('#duplicateNotice').hidden=false;$('#duplicateNotice').textContent='Die History-Import-Datenbank ist noch nicht eingerichtet. Bitte zuerst supabase/migrations/202609250001_history_content_imports.sql ausführen.'}}
function updateDuplicate(){const found=state.imports.find(x=>x.source_sha256===state.sha);state.duplicate=!!found;const n=$('#duplicateNotice');n.hidden=!found;if(found)n.textContent=`Mögliches / bestehendes Duplikat: Diese PDF wurde bereits importiert (${found.import_id}). Ein erneuter Import wird serverseitig verhindert.`;$('#confirm').disabled=!state.pages.length||state.duplicate}
function cleanLines(text){return String(text||'').replace(/\r/g,'').split('\n').map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean)}
function detectHeadings(text){return cleanLines(text).filter(line=>line.length>=4&&line.length<=100&&(/^(?:\d+(?:\.\d+)*[.)]?\s+|[A-ZÄÖÜ0-9][A-ZÄÖÜ0-9 \-–:]{5,}$|(?:Kapitel|Thema|Quelle|M\s*\d+|Aufgabe|Material)\s*\d*\s*[:.-]?\s*\S)/i.test(line)||line===line.toLocaleUpperCase('de-DE'))).slice(0,5)}
function printedPage(text){const m=String(text||'').match(/\b(?:Seite|S\.)\s*(\d{1,3})\b/i);return m?Number(m[1]):null}
function classify(page){const words=(page.text.match(/[\p{L}]{4,}/gu)||[]).length;const historyHits=(page.text.match(/\b(?:Quelle|Herrschaft|König|Kaiser|Krieg|Revolution|Mittelalter|Republik|Diktatur|Reformation|Demokratie|Ereignis|historisch|Jahrhundert)\b/gi)||[]).length;const text=page.method==='pdf_text'?Math.min(.99,.64+Math.log10(Math.max(10,page.charCount))/8):Math.max(.25,Math.min(.95,(page.ocrConfidence||50)/100));const structure=page.headings.length?.91:.53;const subject=historyHits>=3?.96:historyHits>=1?.77:words>70?.55:.35;const quality=words>35?.88:words>12?.68:.38;return Math.round(Math.max(.15,Math.min(.99,text*.36+structure*.24+subject*.24+quality*.16))*100)/100}
function confidenceName(v){return v>=.82?'Sicher':v>=.55?'Prüfen':'Problematisch'}
function confidenceClass(v){return v>=.82?'green':v>=.55?'yellow':'red'}
function similarTopic(title){const normalize=s=>String(s||'').toLocaleLowerCase('de-DE').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}]+/gu,' ').trim(),candidate=normalize(title),words=new Set(candidate.split(' ').filter(x=>x.length>3));if(!candidate)return null;for(const topic of state.existingTopics){const existing=normalize(topic.title);if(existing===candidate)return topic.title;const other=new Set(existing.split(' ').filter(x=>x.length>3));if(words.size>1&&other.size>1){const overlap=[...words].filter(x=>other.has(x)).length/Math.max(1,Math.min(words.size,other.size));if(overlap>=.7)return topic.title}}return null}
function updateProgress(done,total,text){$('#progressCount').textContent=`${done} / ${total} Seiten`;$('#progressText').textContent=text;$('#progressBar').style.width=(total?Math.round(done/total*100):0)+'%'}
function stage(name){document.querySelectorAll('.pipeline li').forEach((el,i,all)=>{const active=el.dataset.stage===name,idx=all.indexOf(el),current=[...all].findIndex(x=>x.dataset.stage===name);el.classList.toggle('active',active);el.classList.toggle('done',idx<current)})}
async function sha256(file){const digest=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());return[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function mapError(error){const m=String(error?.message||error);if(/password|encrypted/i.test(m))return'Diese PDF ist passwortgeschützt und kann noch nicht analysiert werden.';if(/invalid pdf|format|header|stream/i.test(m))return'Diese PDF ist beschädigt oder hat kein unterstütztes PDF-Format.';if(/worker|network|fetch/i.test(m))return'Die Analyse-Komponente konnte nicht geladen werden. Bitte Internetverbindung prüfen und erneut versuchen.';return'Die PDF konnte nicht analysiert werden. Bitte eine andere Datei versuchen.'}
async function getOcr(){if(state.ocr)return state.ocr;if(!window.Tesseract?.createWorker)throw Error('OCR-Bibliothek nicht erreichbar');state.ocr=await Tesseract.createWorker('deu',1,{logger:m=>{if(m.status==='recognizing text')$('#progressText').textContent=`Scan wird gelesen · ${Math.round((m.progress||0)*100)} %`}});return state.ocr}
function needsOcr(text){const chars=String(text||'').replace(/\s/g,'');const letters=(chars.match(/[\p{L}\p{N}]/gu)||[]).length;return chars.length<45||letters/Math.max(1,chars.length)<.52}
async function extractPdf(file){if(!window.pdfjsLib?.getDocument)throw Error('PDF-Parser nicht erreichbar');pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const loading=pdfjsLib.getDocument({data:await file.arrayBuffer()});let pdf;try{pdf=await loading.promise}catch(error){throw Error(mapError(error))}if(pdf.numPages>MAX_PAGES)throw Error(`Die PDF hat ${pdf.numPages} Seiten. Pro Import sind höchstens ${MAX_PAGES} Seiten erlaubt.`);$('#progressPanel').hidden=false;$('#reviewPanel').hidden=true;updateProgress(0,pdf.numPages,'PDF geöffnet; Seiten werden untersucht …');stage('read');const pages=[];stage('text');for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),content=await page.getTextContent(),text=content.items.map(x=>(x.str||'')+(x.hasEOL?'\n':' ')).join('').replace(/[ \t]{2,}/g,' ').trim();let finalText=text,method='pdf_text',ocrConfidence=null;if(needsOcr(text)){method='ocr';const worker=await getOcr();const viewport=page.getViewport({scale:1.6});const canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;const result=await worker.recognize(canvas);finalText=result.data.text||'';ocrConfidence=Number(result.data.confidence)||0;canvas.width=canvas.height=1;canvas.remove()}const headings=detectHeadings(finalText);const record={pageIndex:i,printedPage:printedPage(finalText),text:finalText.slice(0,12000),method,ocrConfidence,charCount:finalText.length,headings};record.confidence=classify(record);record.confidenceLabel=confidenceName(record.confidence);record.warning=record.confidence<.55?'Fach- oder Strukturerkennung ist unsicher. Bitte Inhalt sorgfältig prüfen.':record.confidence<.82?'Bitte Themenzuordnung und Zusammenfassung prüfen.':'';pages.push(record);updateProgress(i,pdf.numPages,`${method==='ocr'?'OCR':'Textlayer'} · Seite ${i} analysiert`);page.cleanup?.()}if(state.ocr){await state.ocr.terminate();state.ocr=null}stage('structure');return pages}
function headingFor(page){return page.headings[0]||cleanLines(page.text)[0]?.slice(0,100)||`Material auf Seite ${page.printedPage||page.pageIndex}`}
function candidateId(){return'ext-'+crypto.randomUUID()}
function renderReview(){const selectedChapter=$('#chapter').selectedOptions[0],grade=Number($('#grade').value);$('#reviewSummary').textContent=`${state.file.name} · ${state.pages.length} Seiten · ${selectedChapter?.text||''} · Klasse ${grade}`;$('#pageReviews').innerHTML=state.pages.map((p,i)=>{const excerpt=p.text.slice(0,450),duplicate=similarTopic(headingFor(p));return`<article class="page-review" data-page="${i}"><div class="page-top"><label class="page-select"><input type="checkbox" data-include="${i}" ${p.confidence>=.82&&!duplicate?'checked':''}> Seite ${p.pageIndex}${p.printedPage?` · Buchseite ${p.printedPage}`:''}</label><span class="confidence ${confidenceClass(p.confidence)}">${confidenceName(p.confidence)} · ${Math.round(p.confidence*100)} %</span></div><div class="page-meta">${p.method==='ocr'?`OCR · erkannte Sicherheit ${p.ocrConfidence||0} %`:'Maschinenlesbarer PDF-Text'}${p.warning?` · ⚠ ${esc(p.warning)}`:''}${duplicate?`<br><span style="color:#a16d1e;font-weight:850">Mögliche Dublette in der bestehenden KB: „${esc(duplicate)}“. Seite startet abgewählt; nur bei bewusster Bestätigung auswählen.</span>`:''}</div><div class="fields"><label>Vorgeschlagene Überschrift<input data-title="${i}" maxlength="180" value="${esc(headingFor(p))}"></label><label>Eigene kurze Zusammenfassung (Pflicht)<textarea data-summary="${i}" maxlength="800" placeholder="In eigenen Worten: Was sollen Lernende aus dieser Seite / Quelle verstehen? Nicht den Originaltext kopieren."></textarea></label><label class="wide">Lernziel / fachlicher Fokus<input data-objective="${i}" maxlength="240" placeholder="Optional · z. B. eine historische Quelle zeitlich einordnen"></label></div><details><summary>Extrahierter Text nur zur Prüfung anzeigen</summary><div class="excerpt">${esc(excerpt||'Kein brauchbarer Text erkannt.')}</div></details></article>`}).join('');$('#reviewPanel').hidden=false;$('#progressPanel').hidden=true;$('#confirm').disabled=state.pages.length===0||state.duplicate;stage('review')}
function validateReview(){const errors=[];const checked=[...document.querySelectorAll('[data-include]:checked')];if(!checked.length)errors.push('Wähle mindestens eine Seite / ein Thema aus.');for(const box of checked){const i=Number(box.dataset.include),title=$(`[data-title="${i}"]`).value.trim(),summary=$(`[data-summary="${i}"]`).value.trim();if(title.length<2)errors.push(`Seite ${state.pages[i].pageIndex}: Titel fehlt.`);if(summary.length<10)errors.push(`Seite ${state.pages[i].pageIndex}: bitte eine eigene Zusammenfassung mit mindestens 10 Zeichen ergänzen.`)}return errors}
function selectedPages(){return[...document.querySelectorAll('[data-include]:checked')].map(box=>Number(box.dataset.include))}
async function confirmImport(){const errors=validateReview();const box=$('#validation');box.hidden=!errors.length;box.classList.toggle('error',errors.length>0);box.textContent=errors.join(' ');if(errors.length)return;if(state.duplicate){box.hidden=false;box.classList.add('error');box.textContent='Diese Datei wurde bereits importiert. Es wird nichts überschrieben.';return}let pass=sessionStorage.getItem('kathleenAdminPass')||'';if(!pass)pass=prompt('Bitte Kisten-Adminpasswort eingeben:')||'';if(!pass)return;$('#confirm').disabled=true;$('#confirm').textContent='Import wird validiert …';try{const chapterId=$('#chapter').value,grade=Number($('#grade').value),sourceId=`imp-${crypto.randomUUID()}`,importId=`IMP-${crypto.randomUUID().toUpperCase()}`,selected=selectedPages(),created=new Date().toISOString();const topics=selected.map(i=>{const p=state.pages[i],title=$(`[data-title="${i}"]`).value.trim(),summary=$(`[data-summary="${i}"]`).value.trim(),objective=$(`[data-objective="${i}"]`).value.trim();return{id:candidateId(),title,summary,student_level_summary:summary,learning_objectives:objective?[objective]:[summary],terms:[],people:[],events:[],source_refs:[{source_id:sourceId,book_pages:p.printedPage?String(p.printedPage):`PDF-Seite ${p.pageIndex}`,note:`Extrahiert aus ${state.file.name}; PDF-Seite ${p.pageIndex}.`}],tags:['content-import-v2','teacher-reviewed'],extraction_provenance:{kind:'uploaded_material',source_file:state.file.name,page_index:p.pageIndex,printed_page:p.printedPage,extraction_method:p.method,confidence:p.confidence,reviewed:true,import_id:importId,extractor_version:VERSION,extracted_at:created}}});const metadata={file:state.file.name,type:'application/pdf',size_bytes:state.file.size,pages:state.pages.length,source_sha256:state.sha};const payload={import_id:importId,extractor_version:VERSION,grade,chapter_id:chapterId,source_sha256:state.sha,source_metadata:metadata,payload:{topics,source_inventory:[{id:sourceId,file:state.file.name,type:'PDF · Text/OCR',scope:`${topics.length} geprüfte Inhalte`,pages:state.pages.length,audited:true,import_id:importId,extractor_version:VERSION,uploaded_at:created,source_sha256:state.sha,binary_in_repo:false}]}};const result=await KathleenHistoryImports.confirm(pass,payload);if(result.status==='duplicate')throw Error('Diese Datei wurde bereits importiert ('+result.import_id+').');sessionStorage.setItem('kathleenAdminPass',pass);showReport(result,topics.length)}catch(error){box.hidden=false;box.classList.add('error');box.textContent=error.message.includes('28000')?'Admin-Passwort ist ungültig.':error.message.includes('history_import_confirm')?'Import konnte nicht gespeichert werden. Prüfe, ob die Content-Import-Migration bereits eingerichtet wurde.':error.message;$('#confirm').disabled=false;$('#confirm').textContent='Geprüfte Inhalte importieren'}}
function showReport(result,count){$('#reviewPanel').hidden=true;const report=$('#report');report.hidden=false;report.innerHTML=`<span class="step">IMPORT ABGESCHLOSSEN</span><h2>${count} geprüfte Inhalte zur History Knowledge Base hinzugefügt</h2><div class="report-grid"><div class="report-item"><b>${esc(result.import_id)}</b><span>Import-Session</span></div><div class="report-item"><b>${count}</b><span>Neue Themen · Klasse ${esc($('#grade').value)}</span></div><div class="report-item"><b>${esc($('#chapter').selectedOptions[0]?.text||'')}</b><span>Kapitel aktualisiert · PDF-Original nicht gespeichert</span></div></div><div class="actions"><a class="button primary" href="../history-content-center/?grade=${encodeURIComponent($('#grade').value)}&chapter=${encodeURIComponent(result.chapter_id)}">Knowledge Base öffnen</a><a class="button soft" href="../assessments/">Assessment erstellen</a><button class="button soft" id="rollback">Diesen Import zurücknehmen</button><button class="button soft" id="newImport">Weiteres Material importieren</button></div>`;$('#newImport').onclick=()=>location.reload();$('#rollback').onclick=async()=>{if(!confirm(`Import ${result.import_id} vollständig aus der History Knowledge Base entfernen?`))return;let pass=sessionStorage.getItem('kathleenAdminPass')||prompt('Kisten-Adminpasswort für den Rollback:')||'';if(!pass)return;try{const response=await KathleenHistoryImports.rollback(pass,result.import_id);if(response.status==='rolled_back'){sessionStorage.setItem('kathleenAdminPass',pass);report.insertAdjacentHTML('beforeend','<div class="notice">Import wurde zurückgenommen. Die Knowledge Base lädt die Inhalte nicht mehr.</div>');$('#rollback').disabled=true}else throw Error('Import-Session wurde nicht gefunden.')}catch(error){alert(error.message.includes('28000')?'Admin-Passwort ist ungültig.':error.message)}}}
async function analyze(file){if(!file)return;if(file.size>MAX_BYTES)throw Error('Die Datei ist größer als 20 MB.');if(file.type!=='application/pdf'&&!/\.pdf$/i.test(file.name))throw Error('Bitte eine PDF-Datei auswählen.');state.file=file;state.pages=[];state.sha=await sha256(file);await loadImports();if(state.duplicate){status('PDF bereits importiert','yellow')}$('#progressPanel').hidden=false;$('#reviewPanel').hidden=true;$('#report').hidden=true;$('#progressTitle').textContent='Material wird analysiert';$('#progressPanel').classList.remove('failed');try{state.pages=await extractPdf(file);renderReview()}catch(error){$('#progressPanel').hidden=false;$('#progressTitle').textContent='Analyse konnte nicht abgeschlossen werden';$('#progressText').textContent=mapError(error);$('#progressPanel').classList.add('failed')}}
async function init(){try{state.catalog=await json('../../data/history/catalog.json');fillGrades();status('Prüfe Importdatenbank …','neutral');loadImports()}catch(e){status('History-Katalog nicht verfügbar','red');$('#progressText').textContent=e.message}$('#file').onchange=async e=>{const file=e.target.files?.[0];e.target.value='';try{await analyze(file)}catch(error){alert(error.message)}};$('#pageReviews').oninput=e=>{const card=e.target.closest('.page-review');if(card){const i=Number(card.dataset.page),box=card.querySelector('[data-include]');if(e.target.matches('[data-summary],[data-title]'))box.checked=true;$('#confirm').disabled=state.duplicate||!selectedPages().length}};$('#pageReviews').onchange=e=>{if(e.target.matches('[data-include]'))$('#confirm').disabled=state.duplicate||!selectedPages().length};$('#allPages').onclick=()=>{document.querySelectorAll('[data-include]').forEach(x=>x.checked=true);$('#confirm').disabled=state.duplicate};$('#noPages').onclick=()=>{document.querySelectorAll('[data-include]').forEach(x=>x.checked=false);$('#confirm').disabled=true};$('#confirm').onclick=confirmImport;$('#discard').onclick=()=>{state.file=null;state.pages=[];state.sha='';$('#reviewPanel').hidden=true;$('#progressPanel').hidden=true;$('#file').value=''}}
if(typeof document!=='undefined')document.addEventListener('DOMContentLoaded',init,{once:true});
if(typeof module==='object'&&module.exports)module.exports={cleanLines,detectHeadings,printedPage,classify,confidenceName,confidenceClass,needsOcr,mapError};
})();
