(()=>{
'use strict';
const host=window.KathleenWidgetHost;if(!host)return;
const top=document.querySelector('.top'),library=document.querySelector('#libraryBtn');if(!top||document.querySelector('#presetBtn'))return;
const btn=document.createElement('button');btn.className='pill';btn.id='presetBtn';btn.textContent='⚡ Presets';(library?.nextSibling?top.insertBefore(btn,library.nextSibling):top.appendChild(btn));
const style=document.createElement('style');style.id='kathleenPresetStyle';style.textContent='.presetOverlay{position:fixed;inset:0;z-index:26000;display:none;place-items:center;padding:18px;background:rgba(51,37,54,.36);backdrop-filter:blur(10px)}.presetOverlay.show{display:grid}.presetCard{width:min(720px,95vw);max-height:88dvh;overflow:auto;background:#fff;border:1px solid #e6d9e7;border-radius:24px;padding:18px;box-shadow:0 30px 100px rgba(63,43,67,.28);color:#503d51}.presetHead{display:flex;justify-content:space-between;align-items:flex-start;gap:10px}.presetHead h2{margin:0;font-size:22px}.presetHead p{margin:4px 0 0;color:#8d788f;font-size:10px}.presetClose{border:1px solid #eadde9;background:#fff;border-radius:10px;min-width:40px;min-height:40px;font-weight:900}.presetGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}.presetChoice{border:1px solid #eadde9;background:linear-gradient(145deg,#fff,#fff8fc);border-radius:17px;padding:14px;text-align:left;color:#503d51;cursor:pointer}.presetChoice:hover{border-color:#d7bcd0;transform:translateY(-1px)}.presetChoice .emoji{font-size:27px}.presetChoice b{display:block;font-size:14px;margin:7px 0 4px}.presetChoice small{display:block;color:#8d788f;font-size:9px;line-height:1.45}.presetChoice .chips{display:flex;gap:4px;flex-wrap:wrap;margin-top:9px}.presetChoice .chips span{font-size:7px;font-weight:900;background:#f4edf5;border-radius:999px;padding:4px 6px}.presetFoot{margin-top:12px;padding:10px 12px;border-radius:12px;background:#f5f0fa;color:#806d84;font-size:9px;line-height:1.45}@media(max-width:650px){.presetOverlay{align-items:end;padding:0}.presetCard{width:100%;max-width:none;border-radius:24px 24px 0 0;padding-bottom:calc(18px + env(safe-area-inset-bottom))}.presetGrid{grid-template-columns:1fr}.presetChoice{min-height:108px}}';document.head.appendChild(style);
const overlay=document.createElement('div');overlay.className='presetOverlay';overlay.id='presetOverlay';overlay.innerHTML='<div class="presetCard"><div class="presetHead"><div><h2>⚡ Unterrichts-Presets</h2><p>Ein Klick ergänzt die passenden Widgets. Dein bestehendes Board bleibt erhalten.</p></div><button class="presetClose" id="presetClose">×</button></div><div class="presetGrid"><button class="presetChoice" data-preset="english"><span class="emoji">🇬🇧</span><b>Englisch normal</b><small>Für Einstieg, Wortschatz und spontane Schülerauswahl.</small><div class="chips"><span>5-Min.-Timer</span><span>Ampel</span><span>Zufall</span></div></button><button class="presetChoice" data-preset="group"><span class="emoji">👥</span><b>Gruppenarbeit</b><small>Gruppen schnell bilden, Arbeitszeit sichtbar machen und Lautstärke im Blick behalten.</small><div class="chips"><span>10-Min.-Timer</span><span>Teams</span><span>Sound</span></div></button><button class="presetChoice" data-preset="exam"><span class="emoji">📝</span><b>Klassenarbeit</b><small>Reduzierte, ruhige Ansicht für schriftliche Leistungsnachweise.</small><div class="chips"><span>45-Min.-Timer</span><span>Ruhe-Ampel</span></div></button><button class="presetChoice" data-preset="history"><span class="emoji">🏛️</span><b>Geschichte</b><small>Diskussion und Ergebnissicherung mit schnellem Materialzugriff.</small><div class="chips"><span>7-Min.-Timer</span><span>Live Poll</span><span>Material</span></div></button></div><div class="presetFoot">Die Widgets verwenden automatisch die aktuell aktive Klasse. Bei einem laufenden Classroom greifen Teams, Zufall und Live Poll auf denselben Klassenraum zurück.</div></div>';document.body.appendChild(overlay);
const close=()=>overlay.classList.remove('show');btn.onclick=()=>overlay.classList.add('show');overlay.querySelector('#presetClose').onclick=close;overlay.onclick=e=>{if(e.target===overlay)close()};
function addAt(type,base,dx,dy,widgetData={}){const o={widgetData,...(base?{x:base.x+dx,y:base.y+dy}:{})},el=host.add(type,o);if(!el)return null;return{x:parseFloat(el.style.left)||0,y:parseFloat(el.style.top)||0,el}}
function timerData(sec){return{duration:sec,remaining:sec,seconds:sec,running:false,endsAt:null,alarm:true}}
function setBg(value){const bg=document.querySelector('#bg');if(bg){bg.value=value;bg.dispatchEvent(new Event('change',{bubbles:true}))}}
function traffic(type){if(type==='quiet')return{active:'red',variant:'quiet',showLabels:true,labels:{red:'Stillarbeit',yellow:'Flüsterstimme',green:'Innenstimme'}};return{active:'green',variant:'default',showLabels:true,labels:{red:'Stopp',yellow:'Leiser',green:'Austausch erlaubt'}}}
function apply(name){
 let a=null;
 if(name==='english'){setBg('lined');a=addAt('timer',null,0,0,timerData(300));addAt('traffic',a,390,0,traffic('normal'));addAt('random',a,0,290,{count:1,excludeDrawn:true})}
 if(name==='group'){setBg('');a=addAt('timer',null,0,0,timerData(600));addAt('teams',a,390,0,{mode:'count',teamCount:4});addAt('sound',a,0,300,{threshold:65,running:false,level:0,counter:0})}
 if(name==='exam'){setBg('lined');a=addAt('timer',null,0,0,timerData(2700));addAt('traffic',a,400,0,traffic('quiet'))}
 if(name==='history'){setBg('lined');a=addAt('timer',null,0,0,timerData(420));addAt('poll',a,390,0,{pollType:'choice',question:'Welche Aussage überzeugt euch am meisten?',options:['A','B','C','D'],counts:[0,0,0,0],open:false,revealResults:false});setTimeout(()=>document.querySelector('#materialBtn')?.click(),120)}
 close();const save=document.querySelector('#saveState');if(save)save.textContent='Preset ergänzt · speichert…'
}
overlay.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>apply(b.dataset.preset));
})();