(()=>{'use strict';
if(window.KathleenCountryHuntPremiumV71)return;window.KathleenCountryHuntPremiumV71=true;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let timerMax=24,lastMission='',lastResultHidden=true;
function addAvatars(){const teams=$$('#teams .ch-team');const meta=[['🦄','lav'],['🍃','mint'],['🌸','rose'],['☁️','sky']];teams.forEach((t,i)=>{if(t.querySelector('.ch-team-avatar'))return;const a=document.createElement('div');a.className='ch-team-avatar '+(meta[i]?.[1]||'lav');a.textContent=meta[i]?.[0]||'✦';t.prepend(a)});const combo=$('.ch-combo'),txt=$('#comboText')?.textContent||'';combo?.classList.toggle('hot',/x(?:1\.5|2\.0)/.test(txt))}
function ring(){const t=$('#timerText'),r=$('.ch-ring');if(!t||!r)return;const sec=Number((t.textContent.split(':')[1]||'0').trim());if(sec>timerMax||sec>=23)timerMax=Math.max(sec,24);if($('#missionType')?.textContent.includes('FINAL'))timerMax=25;else if(sec<=20&&sec>=19&&timerMax!==24)timerMax=20;const p=Math.max(0,Math.min(1,sec/(timerMax||24)));r.style.setProperty('--progress',p);r.classList.toggle('danger',sec<=7)}
function placePin(path){const pin=$('#mapPin'),wrap=$('.ch-map-wrap'),svg=$('#mapSvg');if(!pin||!wrap||!svg||!path)return;try{const b=path.getBBox(),pt=svg.createSVGPoint();pt.x=b.x+b.width/2;pt.y=b.y+b.height/2;const m=path.getCTM();if(!m)return;const screen=pt.matrixTransform(m),svgRect=svg.getBoundingClientRect(),wrapRect=wrap.getBoundingClientRect();const vb=svg.viewBox.baseVal,sx=svgRect.width/vb.width,sy=svgRect.height/vb.height;pin.style.left=(svgRect.left-wrapRect.left+(screen.x-vb.x)*sx)+'px';pin.style.top=(svgRect.top-wrapRect.top+(screen.y-vb.y)*sy)+'px';pin.classList.remove('show');void pin.offsetWidth;pin.classList.add('show')}catch(e){}}
function hookMap(){const svg=$('#mapSvg');if(!svg||svg.dataset.v71Hook)return;svg.dataset.v71Hook='1';svg.addEventListener('click',e=>{const p=e.target.closest?.('path.country');if(!p)return;setTimeout(()=>{if(p.classList.contains('correct')||p.classList.contains('boss-hit'))placePin(p)},20)},true)}
function particles(panel,count=18){const palette=['#a987ef','#76cfb2','#f2b84b','#91c9ee','#d98bb0'];for(let i=0;i<count;i++){const p=document.createElement('i');p.className='chfx-particle';const a=Math.random()*Math.PI*2,d=80+Math.random()*170;p.style.setProperty('--x',Math.cos(a)*d+'px');p.style.setProperty('--y',Math.sin(a)*d+'px');p.style.setProperty('--d',(Math.random()*.28)+'s');p.style.setProperty('--p',palette[i%palette.length]);p.style.left=(50+(Math.random()-.5)*20)+'%';p.style.top=(50+(Math.random()-.5)*18)+'%';panel.appendChild(p)}}
function ensureFx(){if($('#chfxOverlay'))return;const o=document.createElement('div');o.id='chfxOverlay';o.className='chfx-overlay';o.innerHTML='<div class="chfx-panel"><div class="chfx-icon" id="chfxIcon">👑</div><div class="chfx-kicker" id="chfxKicker">FINAL MISSION</div><div class="chfx-title" id="chfxTitle">Boss Round</div><div class="chfx-sub" id="chfxSub">Three targets. One final challenge.</div></div>';document.body.appendChild(o);particles(o.querySelector('.chfx-panel'),22)}
function showFx(type){ensureFx();const o=$('#chfxOverlay'),panel=o.querySelector('.chfx-panel');o.className='chfx-overlay '+type;$('#chfxIcon').textContent=type==='boss'?'👑':'🏆';$('#chfxKicker').textContent=type==='boss'?'FINAL MISSION':'MISSION COMPLETE';$('#chfxTitle').textContent=type==='boss'?'Boss Round':'Country Hunt geschafft';$('#chfxSub').textContent=type==='boss'?'Three targets. One final challenge.':'Great work — your journey is complete.';panel.querySelectorAll('.chfx-particle').forEach(x=>x.remove());particles(panel,type==='boss'?20:28);requestAnimationFrame(()=>o.classList.add('show'));setTimeout(()=>o.classList.remove('show'),type==='boss'?1850:2100)}
function watchMission(){const m=$('#missionType');if(!m)return;const value=m.textContent.trim();if(value!==lastMission&&value.includes('FINAL'))showFx('boss');lastMission=value}
function watchResult(){const r=$('#resultScreen');if(!r)return;const hidden=r.classList.contains('hidden');if(lastResultHidden&&!hidden)showFx('victory');lastResultHidden=hidden}
function polish(){addAvatars();ring();hookMap();watchMission();watchResult()}
const mo=new MutationObserver(polish);mo.observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['class']});
window.addEventListener('resize',()=>{const active=$('.country.correct,.country.boss-hit');if(active&&$('#mapPin')?.classList.contains('show'))placePin(active)});
polish();
})();