(()=>{'use strict';
const CLASSIC_KEY='kathleenQuickGamesV1',V68_KEY='kathleenQuickGamesV68';
const GAMES={
 buzzer:{icon:'🔔',title:'Buzzer Battle',group:'classic',help:'Kurze Fragen und eindeutige Antworten für das Teamduell.',fields:[['question','Frage'],['answer','Antwort']]},
 risk:{icon:'⚡',title:'Risk or Safe',group:'classic',help:'Leichte Safe-Fragen und anspruchsvollere Risk-Fragen.',fields:[['mode','Typ','select',['safe','risk']],['question','Frage'],['answer','Antwort']]},
 timeline:{icon:'↕',title:'Timeline Race',group:'classic',help:'Ereignisse mit Jahr oder Zahl; gespeichert wird die richtige Reihenfolge.',fields:[['year','Jahr'],['event','Ereignis']]},
 picture:{icon:'▦',title:'Picture Reveal',group:'classic',help:'Bildadresse, Lösung und optionaler Hinweis.',fields:[['url','Bild-URL'],['answer','Lösung'],['hint','Hinweis']]},
 bomb:{icon:'💣',title:'Word Bomb',group:'classic',help:'Jeder Eintrag ist eine Kategorie für eine neue Runde.',fields:[['category','Kategorie']]},
 classvs:{icon:'♛',title:'Class vs Teacher',group:'classic',help:'Fragen und Antworten für das gemeinsame Duell gegen die Lehrkraft.',fields:[['question','Frage'],['answer','Antwort']]},
 odd:{icon:'◈',title:'Odd One Out',group:'v68',help:'Vier Begriffe, Nummer der Lösung und eine kurze Begründung.',fields:[['one','Begriff 1'],['two','Begriff 2'],['three','Begriff 3'],['four','Begriff 4'],['answer','Lösung 1–4'],['why','Begründung']]},
 estimate:{icon:'◎',title:'Estimate It',group:'v68',help:'Schätzfrage, Zielwert, Einheit und erlaubte Abweichung.',fields:[['question','Frage'],['target','Zielwert'],['unit','Einheit'],['tolerance','Toleranz']]},
 taboo:{icon:'◉',title:'Hot Seat · Taboo',group:'v68',help:'Suchbegriff und bis zu vier Wörter, die nicht genannt werden dürfen.',fields:[['term','Begriff'],['one','Tabu 1'],['two','Tabu 2'],['three','Tabu 3'],['four','Tabu 4']]},
 memory:{icon:'✦',title:'Memory Match',group:'v68',help:'Je zwei Inhalte bilden ein zusammengehöriges Paar.',fields:[['left','Karte A'],['right','Karte B']]}
};
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));let game='buzzer',rows=[];
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch(e){return fallback}}
function db(){return read(CLASSIC_KEY,{version:1,sets:{}})}function v68(){return read(V68_KEY,{})}
function content(){const m=GAMES[game];if(m.group==='classic')return db().sets?.[game]?.content||'';return v68()[game]?.content||''}
function meta(){const m=GAMES[game];if(m.group==='classic')return db().sets?.[game]||{};return{title:m.title,subject:'',grade:''}}
function parse(){const size=GAMES[game].fields.length;rows=String(content()).split(/\n+/).map(x=>x.trim()).filter(Boolean).map(line=>{const a=line.split('|').map(x=>x.trim());while(a.length<size)a.push('');return a.slice(0,size)});if(!rows.length)rows=[Array(size).fill('')]}
function gameList(){$('#gameList').innerHTML=Object.entries(GAMES).map(([id,m])=>`<button class="game-tab ${id===game?'active':''}" data-game="${id}"><i>${m.icon}</i><span><b>${m.title}</b><small>${m.group==='classic'?'Gameshow':'Quizformat'}</small></span></button>`).join('');document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>select(b.dataset.game))}
function render(){const m=GAMES[game],info=meta();gameList();$('#gameTitle').textContent=m.title;$('#gameHelp').textContent=m.help;$('#setTitle').value=info.title||m.title;$('#setSubject').value=info.subject||'';$('#setGrade').value=info.grade||'';document.documentElement.style.setProperty('--cols',m.fields.length);$('#tableHead').innerHTML='<span>#</span>'+m.fields.map(x=>`<span>${esc(x[1])}</span>`).join('')+'<span></span>';$('#rows').innerHTML=rows.length?rows.map((row,i)=>`<div class="content-row" data-row="${i}"><div class="row-number">${i+1}</div>${m.fields.map((field,j)=>`<label class="cell">${field[2]==='select'?`<select data-cell="${j}">${field[3].map(x=>`<option ${row[j]===x?'selected':''}>${x}</option>`).join('')}</select>`:`<textarea rows="1" data-cell="${j}" placeholder="${esc(field[1])}">${esc(row[j])}</textarea>`}</label>`).join('')}<button class="delete" data-delete="${i}" title="Eintrag löschen">×</button></div>`).join(''):'<div class="empty">Noch keine Inhalte vorhanden.</div>';$('#rowCount').textContent=rows.filter(row=>row.some(Boolean)).length;document.querySelectorAll('[data-row]').forEach(el=>el.querySelectorAll('[data-cell]').forEach(input=>input.oninput=()=>{rows[Number(el.dataset.row)][Number(input.dataset.cell)]=input.value}));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{rows.splice(Number(b.dataset.delete),1);render()})}
function select(id){game=id;parse();render();state('Bereit zum Bearbeiten.',false)}
function add(){rows.push(Array(GAMES[game].fields.length).fill(''));render();document.querySelector('.content-row:last-child textarea, .content-row:last-child select')?.focus()}
function save(){const m=GAMES[game],content=rows.filter(row=>row.some(x=>String(x).trim())).map(row=>row.map(x=>String(x).trim()).join(' | ')).join('\n');if(m.group==='classic'){const data=db();data.sets??={};data.sets[game]={title:$('#setTitle').value.trim()||m.title,subject:$('#setSubject').value.trim(),grade:$('#setGrade').value.trim(),content};localStorage.setItem(CLASSIC_KEY,JSON.stringify(data))}else{const data=v68();data[game]={content,source:$('#setTitle').value.trim()||m.title,difficulty:'standard',updatedAt:new Date().toISOString()};localStorage.setItem(V68_KEY,JSON.stringify(data))}state(`${rows.filter(r=>r.some(Boolean)).length} Einträge gespeichert.`,true)}
function state(message,saved){$('#saveState').textContent=message;$('#saveState').classList.toggle('saved',!!saved)}
$('#addRow').onclick=add;$('#save').onclick=save;$('#reset').onclick=()=>{if(confirm('Dieses Set wirklich leeren?')){rows=[Array(GAMES[game].fields.length).fill('')];render();state('Set geleert – zum Übernehmen noch speichern.',false)}};$('#openGame').onclick=()=>{save();location.href='../?game='+(GAMES[game].group==='v68'?'v68-'+game:game)};parse();render();
})();
