(()=>{'use strict';
const URL_BASE='https://fzqxnjhuvgpgovcovosl.supabase.co',KEY='sb_publishable_GIyyWoyaQXipaA4S9OuTyQ_cZn7LUgV',SESSION_KEY='kathleenEnglishKbSessionV1',DEVICE_KEY='kathleenEnglishKbDeviceV1',$=id=>document.getElementById(id),Library=window.KathleenEnglishBulkLibrary,state={session:null,plan:null};
function deviceId(){let id=localStorage.getItem(DEVICE_KEY);if(!id){id=`device-${crypto.randomUUID?.()||Date.now().toString(36)}`;localStorage.setItem(DEVICE_KEY,id)}return id}
function headers(json=true){return{apikey:KEY,...(state.session?.access_token?{Authorization:`Bearer ${state.session.access_token}`}:{}) ,...(json?{'Content-Type':'application/json'}:{})}}
async function api(path,options={}){const response=await fetch(URL_BASE+path,{...options,headers:{...headers(options.json!==false),...(options.headers||{})}});if(!response.ok)throw Error(`${response.status}: ${await response.text()}`);if(response.status===204)return null;return(response.headers.get('content-type')||'').includes('json')?response.json():response.blob()}
async function fingerprint(value){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(value)));return[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
const clone=value=>JSON.parse(JSON.stringify(value));
function sanitizeDocument(record){return{id:record.id,schemaVersion:record.schemaVersion,classification:record.classification,content:{objects:record.content?.objects||[],analysisSummary:record.content?.analysisV3?{metadata:record.content.analysisV3.metadata,warnings:record.content.analysisV3.warnings}:null},quality:record.quality,source:{fileName:record.source?.fileName||'',sha256:record.source?.sha256||'',size:record.source?.size||0,type:record.source?.type||''},provenance:record.provenance,lifecycle:record.lifecycle||{},managerSchemaVersion:record.managerSchemaVersion||1}}
function sanitizeRule(rule){return{id:rule.id,kind:rule.kind,label:rule.label||'',pattern:rule.pattern||'',value:rule.value??null,flags:rule.flags||'',enabled:rule.enabled!==false,createdAt:rule.createdAt||null,updatedAt:rule.updatedAt||null}}
function restoreDocument(payload,cloud){return{...payload,source:{...(payload.source||{}),relativePath:payload.source?.fileName||''},sync:{version:cloud.version,syncedAt:new Date().toISOString(),cloudUpdatedAt:cloud.updated_at,fingerprint:null,basePayload:clone(payload)},provenance:{...(payload.provenance||{}),originalRemainsLocal:true,cloudSyncedAt:new Date().toISOString()}}}
function restoreRule(payload,cloud){return{...payload,sync:{version:cloud.version,syncedAt:new Date().toISOString(),cloudUpdatedAt:cloud.updated_at,fingerprint:null,basePayload:clone(payload)}}}
async function authenticate(mode){const email=$('syncEmail').value.trim(),password=$('syncPassword').value,status=$('syncAuthStatus');if(!email||password.length<8){status.textContent='Bitte E-Mail und ein Passwort mit mindestens 8 Zeichen eingeben.';return}status.textContent=mode==='signup'?'Konto wird angelegt …':'Anmeldung läuft …';const path=mode==='signup'?'/auth/v1/signup':'/auth/v1/token?grant_type=password',session=await api(path,{method:'POST',body:JSON.stringify({email,password})});if(!session?.access_token){status.textContent='Konto angelegt. Bitte gegebenenfalls die Bestätigungs-E-Mail öffnen und danach anmelden.';return}state.session=session;localStorage.setItem(SESSION_KEY,JSON.stringify(session));$('syncPassword').value='';status.textContent='';await workspace()}
function sessionLoad(){try{const value=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');if(value?.access_token&&value?.user?.id)state.session=value}catch(e){localStorage.removeItem(SESSION_KEY)}}
async function uploadPreview(record){const data=record.content?.previewImage;if(!data?.startsWith('data:image/'))return null;const response=await fetch(data),blob=await response.blob();if(blob.size>2097152)return null;const path=`${state.session.user.id}/${encodeURIComponent(record.id)}.jpg`;await api(`/storage/v1/object/english-kb-previews/${path}`,{method:'POST',json:false,headers:{...headers(false),'Content-Type':blob.type||'image/jpeg','x-upsert':'true'},body:blob});return path}
function flatten(value,prefix='',out={}){if(value&&typeof value==='object'&&!Array.isArray(value)){for(const[key,item]of Object.entries(value))flatten(item,prefix?`${prefix}.${key}`:key,out)}else out[prefix]=value;return out}
function setPath(target,path,value){const parts=path.split('.');let node=target;for(const part of parts.slice(0,-1)){if(!node[part]||typeof node[part]!=='object')node[part]={};node=node[part]}node[parts.at(-1)]=clone(value);return target}
const equal=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
function conflictFields(item){const local=flatten(item.payload),remote=flatten(item.remote.payload||{});return[...new Set([...Object.keys(local),...Object.keys(remote)])].filter(path=>!equal(local[path],remote[path])).map(path=>({path,local:local[path],remote:remote[path]}))}
function localItems(documents,rules){return[...documents.map(record=>({id:record.id,kind:'document',record,payload:sanitizeDocument(record),sync:record.sync||{}})),...rules.map(rule=>({id:`rule:${rule.id}`,kind:'recognition_rule',record:rule,payload:sanitizeRule(rule),sync:rule.sync||{}}))]}
async function buildPlan(){const documents=await Library.records(),rules=$('syncRules').checked?await Library.rules():[],cloud=await api('/rest/v1/english_kb_sync_items?select=*&deleted_at=is.null'),filtered=cloud.filter(row=>row.item_kind==='document'||($('syncRules').checked&&row.item_kind==='recognition_rule')),byCloud=new Map(filtered.map(x=>[x.item_id,x])),push=[],pull=[],conflicts=[],unchanged=[];for(const item of localItems(documents,rules)){const fp=await fingerprint(item.payload),remote=byCloud.get(item.id);if(!remote){push.push({...item,fp,expected:null});continue}const remotePayload=clone(remote.payload||{});delete remotePayload.previewPath;const remoteFp=await fingerprint(remotePayload);if(!item.sync.fingerprint){if(fp===remoteFp)unchanged.push(item);else conflicts.push({...item,remote,reason:'Noch kein gemeinsamer Ausgangsstand'});byCloud.delete(item.id);continue}const localChanged=item.sync.fingerprint!==fp,cloudChanged=Number(item.sync.version)!==Number(remote.version);if(localChanged&&cloudChanged)conflicts.push({...item,remote,reason:'Auf beiden Geräten geändert'});else if(localChanged)push.push({...item,fp,expected:remote.version});else if(cloudChanged)pull.push({remote});else unchanged.push(item);byCloud.delete(item.id)}for(const remote of byCloud.values())pull.push({remote});return{push,pull,conflicts,unchanged}}
function valueLabel(value){const text=typeof value==='string'?value:JSON.stringify(value);return escapeHtml((text??'—').slice(0,180))}
function renderConflict(item,index){return`<details class="sync-conflict" open><summary>${escapeHtml(item.record.source?.fileName||item.record.label||item.id)} · ${escapeHtml(item.reason)}</summary>${conflictFields(item).map(field=>`<fieldset><legend>${escapeHtml(field.path)}</legend><label><input type="radio" name="conflict-${index}-${escapeHtml(field.path)}" data-conflict="${index}" data-path="${escapeHtml(field.path)}" value="local" checked> Dieses Gerät: ${valueLabel(field.local)}</label><label><input type="radio" name="conflict-${index}-${escapeHtml(field.path)}" data-conflict="${index}" data-path="${escapeHtml(field.path)}" value="cloud"> Cloud: ${valueLabel(field.remote)}</label></fieldset>`).join('')}<button type="button" class="button soft resolve-conflict" data-index="${index}">Auswahl übernehmen</button></details>`}
function renderPlan(){const p=state.plan;$('syncPreview').innerHTML=`<div class="stats"><article class="stat"><b>${p.push.length}</b><small>Vom Gerät senden</small></article><article class="stat"><b>${p.pull.length}</b><small>Vom Cloud-Konto laden</small></article><article class="stat"><b>${p.conflicts.length}</b><small>Feldkonflikte</small></article><article class="stat"><b>${p.unchanged.length}</b><small>Unverändert</small></article></div>${p.conflicts.length?`<div class="readiness blocked"><b>Konflikte brauchen eine Auswahl.</b><p>Für jedes abweichende Feld bleibt zunächst der Wert dieses Geräts gewählt.</p></div>${p.conflicts.map(renderConflict).join('')}`:''}<p>Übertragen werden strukturierte Inhalte${$('syncRules').checked?' und ausdrücklich ausgewählte Erkennungsregeln':''} sowie kleine private Vorschaubilder. Keine Original-PDFs oder vollständigen Dokumente.</p>`;$('syncApply').disabled=(!p.push.length&&!p.pull.length)||p.conflicts.length>0;$('syncPreview').querySelectorAll('.resolve-conflict').forEach(button=>button.onclick=()=>resolveConflict(Number(button.dataset.index)))}
async function resolveConflict(index){const item=state.plan.conflicts[index],merged=clone(item.payload),remoteFlat=flatten(item.remote.payload||{});$('syncPreview').querySelectorAll(`[data-conflict="${index}"]:checked`).forEach(input=>{if(input.value==='cloud')setPath(merged,input.dataset.path,remoteFlat[input.dataset.path])});item.payload=merged;item.expected=item.remote.version;item.fp=await fingerprint(merged);state.plan.push.push(item);state.plan.conflicts.splice(index,1);renderPlan()}
async function workspace(){$('syncLogin').hidden=true;$('syncWorkspace').hidden=false;$('syncAccount').textContent=`Angemeldet als ${state.session.user.email||'Kathleen'} · Gerät ${deviceId()}`;state.plan=await buildPlan();renderPlan()}
async function write(item){const previewPath=item.kind==='document'?await uploadPreview(item.record):null,payload=previewPath?{...item.payload,previewPath}:item.payload,body={p_item:{item_id:item.id,item_kind:item.kind,payload,source_sha256:item.kind==='document'?(item.record.source?.sha256||null):null,device_id:deviceId()},p_expected_version:item.expected};const rows=await api('/rest/v1/rpc/english_kb_sync_write',{method:'POST',body:JSON.stringify(body)}),row=Array.isArray(rows)?rows[0]:rows;item.record.sync={version:row.version,syncedAt:new Date().toISOString(),cloudUpdatedAt:row.updated_at,fingerprint:await fingerprint(item.payload),basePayload:clone(item.payload)};if(item.kind==='document')await Library.put(item.record);else await Library.putRule(item.record)}
async function pull(item){if(item.remote.item_kind==='recognition_rule'){const rule=restoreRule(item.remote.payload,item.remote);rule.sync.fingerprint=await fingerprint(sanitizeRule(rule));await Library.putRule(rule)}else{const record=restoreDocument(item.remote.payload,item.remote);record.sync.fingerprint=await fingerprint(sanitizeDocument(record));await Library.put(record)}}
async function apply(){const report={sent:0,loaded:0,conflicts:state.plan.conflicts.length,errors:[]};for(const item of state.plan.push)try{await write(item);report.sent++}catch(error){report.errors.push(`${item.id}: ${error.message}`)}for(const item of state.plan.pull)try{await pull(item);report.loaded++}catch(error){report.errors.push(`${item.remote.item_id}: ${error.message}`)}$('syncPreview').innerHTML=`<div class="readiness ${report.errors.length?'blocked':''}"><b>Synchronisierung abgeschlossen</b><p>${report.sent} gesendet · ${report.loaded} geladen · ${report.conflicts} offene Konflikte · ${report.errors.length} Fehler</p>${report.errors.length?`<ul>${report.errors.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul>`:''}</div>`;if(!report.errors.length)await window.KathleenEnglishKbUi.reload('Synchronisierung abgeschlossen.')}
function signOut(){state.session=null;state.plan=null;localStorage.removeItem(SESSION_KEY);$('syncWorkspace').hidden=true;$('syncLogin').hidden=false;$('syncAccount').textContent=''}
async function open(){sessionLoad();$('syncDialog').showModal();if(state.session)try{await workspace()}catch(error){$('syncPreview').textContent=`Cloud-Synchronisierung nicht verfügbar: ${error.message}`}else{$('syncLogin').hidden=false;$('syncWorkspace').hidden=true;$('syncEmail').focus()}}
function reportAuth(error){$('syncAuthStatus').textContent=`Anmeldung fehlgeschlagen: ${error.message}`}
function init(){$('sync').dataset.unavailable='';$('sync').disabled=false;$('cloudState').textContent='Private Synchronisierung ist eingerichtet. Sie startet nur nach Anmeldung und ausdrücklichem Klick.';$('sync').onclick=open;$('syncClose').onclick=()=>$('syncDialog').close();$('syncSignIn').onclick=()=>authenticate('signin').catch(reportAuth);$('syncSignUp').onclick=()=>authenticate('signup').catch(reportAuth);$('syncRefresh').onclick=()=>workspace().catch(error=>$('syncPreview').textContent=`Vorschau fehlgeschlagen: ${error.message}`);$('syncRules').onchange=()=>$('syncRefresh').focus();$('syncApply').onclick=apply;$('syncSignOut').onclick=signOut}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
