(()=>{'use strict';
const URL_BASE='https://fzqxnjhuvgpgovcovosl.supabase.co',KEY='sb_publishable_GIyyWoyaQXipaA4S9OuTyQ_cZn7LUgV',SESSION_KEY='kathleenEnglishKbSessionV1',DEVICE_KEY='kathleenEnglishKbDeviceV1',$=id=>document.getElementById(id),Library=window.KathleenEnglishBulkLibrary,state={session:null,plan:null};
function deviceId(){let id=localStorage.getItem(DEVICE_KEY);if(!id){id=`device-${crypto.randomUUID?.()||Date.now().toString(36)}`;localStorage.setItem(DEVICE_KEY,id)}return id}
function headers(json=true){return{apikey:KEY,...(state.session?.access_token?{Authorization:`Bearer ${state.session.access_token}`}:{}) ,...(json?{'Content-Type':'application/json'}:{})}}
async function api(path,options={}){const response=await fetch(URL_BASE+path,{...options,headers:{...headers(options.json!==false),...(options.headers||{})}});if(!response.ok)throw Error(`${response.status}: ${await response.text()}`);if(response.status===204)return null;const type=response.headers.get('content-type')||'';return type.includes('json')?response.json():response.blob()}
async function fingerprint(value){const encoded=new TextEncoder().encode(JSON.stringify(value)),digest=await crypto.subtle.digest('SHA-256',encoded);return[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function sanitize(record){return{id:record.id,schemaVersion:record.schemaVersion,classification:record.classification,content:{objects:record.content?.objects||[],analysisSummary:record.content?.analysisV3?{metadata:record.content.analysisV3.metadata,warnings:record.content.analysisV3.warnings}:null},quality:record.quality,source:{fileName:record.source?.fileName||'',sha256:record.source?.sha256||'',size:record.source?.size||0,type:record.source?.type||''},provenance:record.provenance,lifecycle:record.lifecycle||{},managerSchemaVersion:record.managerSchemaVersion||1}}
function restore(payload,cloud){return{...payload,source:{...(payload.source||{}),relativePath:payload.source?.fileName||''},sync:{version:cloud.version,syncedAt:new Date().toISOString(),cloudUpdatedAt:cloud.updated_at,fingerprint:null},provenance:{...(payload.provenance||{}),originalRemainsLocal:true,cloudSyncedAt:new Date().toISOString()}}}
async function signIn(){const email=$('syncEmail').value.trim(),password=$('syncPassword').value;if(!email||!password)return;const session=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});state.session=session;localStorage.setItem(SESSION_KEY,JSON.stringify(session));$('syncPassword').value='';await workspace()}
function sessionLoad(){try{const value=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');if(value?.access_token&&value?.user?.id)state.session=value}catch(e){localStorage.removeItem(SESSION_KEY)}}
async function uploadPreview(record){const data=record.content?.previewImage;if(!data?.startsWith('data:image/'))return null;const response=await fetch(data),blob=await response.blob();if(blob.size>2097152)return null;const path=`${state.session.user.id}/${encodeURIComponent(record.id)}.jpg`;await api(`/storage/v1/object/english-kb-previews/${path}`,{method:'POST',json:false,headers:{...headers(false),'Content-Type':blob.type||'image/jpeg','x-upsert':'true'},body:blob});return path}
async function buildPlan(){const local=await Library.records(),cloud=await api('/rest/v1/english_kb_sync_items?select=*&item_kind=eq.document&deleted_at=is.null'),byCloud=new Map(cloud.map(x=>[x.item_id,x])),push=[],pull=[],conflicts=[],unchanged=[];for(const record of local){const payload=sanitize(record),fp=await fingerprint(payload),remote=byCloud.get(record.id);if(!remote){push.push({record,payload,fp,expected:null});continue}const base=record.sync||{},remotePayload={...(remote.payload||{})};delete remotePayload.previewPath;const remoteFp=await fingerprint(remotePayload);if(!base.fingerprint){if(fp===remoteFp)unchanged.push(record);else conflicts.push({record,remote,reason:'Lokaler und privater Cloud-Eintrag haben noch keinen gemeinsamen Ausgangsstand'});byCloud.delete(record.id);continue}const localChanged=base.fingerprint!==fp,cloudChanged=base.version!=null&&Number(base.version)!==Number(remote.version);if(localChanged&&cloudChanged)conflicts.push({record,remote,reason:'Auf beiden Geräten geändert'});else if(localChanged)push.push({record,payload,fp,expected:remote.version});else if(cloudChanged)pull.push({remote});else unchanged.push(record);byCloud.delete(record.id)}for(const remote of byCloud.values())pull.push({remote});return{push,pull,conflicts,unchanged,totalLocal:local.length,totalCloud:cloud.length}}
function renderPlan(){const p=state.plan;$('syncPreview').innerHTML=`<div class="stats"><article class="stat"><b>${p.push.length}</b><small>Vom Gerät senden</small></article><article class="stat"><b>${p.pull.length}</b><small>Vom Cloud-Konto laden</small></article><article class="stat"><b>${p.conflicts.length}</b><small>Konflikte</small></article><article class="stat"><b>${p.unchanged.length}</b><small>Unverändert</small></article></div>${p.conflicts.length?`<div class="readiness blocked"><b>Konflikte werden nicht automatisch überschrieben.</b><ul>${p.conflicts.map(x=>`<li>${x.record.source?.fileName||x.record.id}: ${x.reason}</li>`).join('')}</ul></div>`:''}<p>Es werden ausschließlich strukturierte Inhalte und kleine private Vorschaubilder übertragen. Keine Original-PDFs oder vollständigen Dokumente.</p>`;$('syncApply').disabled=!p.push.length&&!p.pull.length}
async function workspace(){$('syncLogin').hidden=true;$('syncWorkspace').hidden=false;$('syncAccount').textContent=`Angemeldet als ${state.session.user.email||'Kathleen'} · Gerät ${deviceId()}`;state.plan=await buildPlan();renderPlan()}
async function write(item){const previewPath=await uploadPreview(item.record),payload={...item.payload,previewPath},body={p_item:{item_id:item.record.id,item_kind:'document',payload,source_sha256:item.record.source?.sha256||null,device_id:deviceId()},p_expected_version:item.expected};const rows=await api('/rest/v1/rpc/english_kb_sync_write',{method:'POST',body:JSON.stringify(body)}),row=Array.isArray(rows)?rows[0]:rows;item.record.sync={version:row.version,syncedAt:new Date().toISOString(),cloudUpdatedAt:row.updated_at,fingerprint:await fingerprint(item.payload)};await Library.put(item.record)}
async function apply(){const report={sent:0,loaded:0,conflicts:state.plan.conflicts.length,errors:[]};for(const item of state.plan.push)try{await write(item);report.sent++}catch(error){report.errors.push(`${item.record.id}: ${error.message}`)}for(const item of state.plan.pull)try{const record=restore(item.remote.payload,item.remote);record.sync.fingerprint=await fingerprint(sanitize(record));await Library.put(record);report.loaded++}catch(error){report.errors.push(`${item.remote.item_id}: ${error.message}`)}$('syncPreview').innerHTML=`<div class="readiness ${report.errors.length?'blocked':''}"><b>Synchronisierung abgeschlossen</b><p>${report.sent} gesendet · ${report.loaded} geladen · ${report.conflicts} Konflikte nicht überschrieben · ${report.errors.length} Fehler</p>${report.errors.length?`<ul>${report.errors.map(x=>`<li>${x}</li>`).join('')}</ul>`:''}</div>`;await window.KathleenEnglishKbUi.reload('Synchronisierung abgeschlossen.')}
function signOut(){state.session=null;state.plan=null;localStorage.removeItem(SESSION_KEY);$('syncWorkspace').hidden=true;$('syncLogin').hidden=false;$('syncAccount').textContent=''}
async function open(){sessionLoad();$('syncDialog').showModal();if(state.session)try{await workspace()}catch(error){$('syncPreview').textContent=`Cloud-Synchronisierung nicht verfügbar: ${error.message}`}else{$('syncLogin').hidden=false;$('syncWorkspace').hidden=true;$('syncEmail').focus()}}
function init(){$('sync').dataset.unavailable='';$('sync').disabled=false;$('cloudState').textContent='Private Synchronisierung ist eingerichtet. Sie startet nur nach Anmeldung und ausdrücklichem Klick.';$('sync').onclick=open;$('syncClose').onclick=()=>$('syncDialog').close();$('syncSignIn').onclick=()=>signIn().catch(error=>$('syncLogin').insertAdjacentHTML('beforeend',`<p class="readiness blocked">Anmeldung fehlgeschlagen: ${error.message}</p>`));$('syncApply').onclick=apply;$('syncSignOut').onclick=signOut}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
