(()=>{'use strict';
const $=id=>document.getElementById(id),Library=window.KathleenEnglishBulkLibrary,Core=window.KathleenEnglishKbManagerCore,state={queue:[],index:0,history:[],deferred:new Set(),pointer:null};
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function current(){return state.queue[state.index]||null}
function confidence(unit){const value=Math.round((unit.confidence||0)*100);return{value,label:value>=82?'Sicher':value>=55?'Prüfen':'Problematisch'}}
function render(){const unit=current(),card=$('quickReviewCard');$('quickUndo').disabled=!state.history.length;if(!unit){card.innerHTML=`<div class="review-finished"><h3>Prüfung abgeschlossen</h3><p>${state.history.length} Entscheidungen gespeichert. ${state.deferred.size} Aufgaben wurden zurückgestellt.</p></div>`;$('quickReviewProgress').textContent='Fertig';for(const id of ['quickLater','quickEdit','quickAccept','quickBulk'])$(id).disabled=true;return}const c=confidence(unit),p=unit.payload||{},warnings=[...(!unit.grade?['Klasse fehlt']:[]),...(unit.unit==null?['Unit fehlt']:[]),...(p.solution?[]:['Keine Lösung erkannt'])];$('quickReviewProgress').textContent=`${state.index+1} von ${state.queue.length}`;card.innerHTML=`${p.previewImage?`<img src="${esc(p.previewImage)}" alt="Ausschnitt der erkannten Aufgabe">`:''}<span class="confidence c-${c.label.toLowerCase()}">${c.label} · ${c.value} %</span><h3>${esc(unit.title)}</h3><dl><dt>Klasse / Unit</dt><dd>${esc(unit.grade||'–')} / ${esc(unit.unit??'–')}</dd><dt>Typ</dt><dd>${esc(Core.TYPE_LABELS[unit.type]||unit.type)} · ${esc(p.taskType||'nicht bestimmt')}</dd><dt>Thema</dt><dd>${esc(unit.topic||'–')}</dd><dt>Arbeitsauftrag</dt><dd>${esc(p.instruction||'–')}</dd><dt>Lösung</dt><dd>${esc(p.solution?.text||'Noch nicht erkannt')}</dd><dt>Quelle</dt><dd>${esc(unit.source.fileName)} · Seite ${esc(unit.source.pages.join(', ')||'–')}</dd></dl>${warnings.length?`<div class="review-warnings">${warnings.map(esc).join(' · ')}</div>`:''}`;card.focus({preventScroll:true})}
async function load(){const records=await Library.records();state.queue=records.flatMap(Core.units).filter(x=>!x.lifecycle?.archivedAt&&x.reviewStatus==='needs_review');state.index=0;state.history=[];state.deferred.clear();for(const id of ['quickLater','quickEdit','quickAccept','quickBulk'])$(id).disabled=false;render()}
async function accept(){const unit=current();if(!unit)return;state.history.push({unit,action:'accept',before:{reviewStatus:unit.reviewStatus,approvedUses:unit.approvedUses}});await Library.updateUnit(unit.id,{reviewStatus:'reviewed',approvedUses:[...new Set([...unit.approvedUses,'practice','worksheet'])]});state.index++;$('quickReviewLive').textContent=`${unit.title} bestätigt.`;render()}
function later(){const unit=current();if(!unit)return;state.history.push({unit,action:'later'});state.deferred.add(unit.id);state.queue.splice(state.index,1);state.queue.push(unit);if(state.queue.slice(state.index).every(x=>state.deferred.has(x.id)))state.index=state.queue.length;$('quickReviewLive').textContent=`${unit.title} wurde zurückgestellt.`;render()}
function edit(){const unit=current();if(!unit)return;$('quickReviewDialog').close();window.dispatchEvent(new CustomEvent('english-kb-open-unit',{detail:{id:unit.id}}))}
async function undo(){const action=state.history.pop();if(!action)return;if(action.action==='accept'){await Library.updateUnit(action.unit.id,action.before);state.index=Math.max(0,state.index-1)}else if(action.action==='later'){const at=state.queue.findIndex(x=>x.id===action.unit.id);if(at>=0){state.queue.splice(at,1);state.queue.splice(state.index,0,action.unit)}state.deferred.delete(action.unit.id);state.index=Math.min(state.index,state.queue.length-1)}$('quickReviewLive').textContent='Letzte Aktion rückgängig gemacht.';render()}
async function bulk(){const safe=state.queue.slice(state.index).filter(x=>x.confidence>=.82&&!x.needsOcr&&x.grade&&x.unit!=null&&x.payload?.solution);if(!safe.length){$('quickReviewLive').textContent='Keine weiteren sicheren Treffer vorhanden.';return}if(!confirm(`${safe.length} sichere Treffer als geprüft markieren? Eine Freigabe für Leistungsnachweise erfolgt nicht.`))return;for(const unit of safe){state.history.push({unit,action:'accept',before:{reviewStatus:unit.reviewStatus,approvedUses:unit.approvedUses}});await Library.updateUnit(unit.id,{reviewStatus:'reviewed',approvedUses:[...new Set([...unit.approvedUses,'practice','worksheet'])]})}const ids=new Set(safe.map(x=>x.id));state.queue=state.queue.filter(x=>!ids.has(x.id));state.index=Math.min(state.index,state.queue.length);render()}
function pointerDown(event){state.pointer={x:event.clientX,y:event.clientY};$('quickReviewCard').setPointerCapture?.(event.pointerId)}
function pointerUp(event){if(!state.pointer)return;const dx=event.clientX-state.pointer.x,dy=event.clientY-state.pointer.y;state.pointer=null;if(Math.abs(dx)<70&&Math.abs(dy)<70)return;if(Math.abs(dx)>Math.abs(dy))dx>0?accept():later();else if(dy<0)edit()}
function init(){$('quickReviewStart').onclick=async()=>{const dialog=$('quickReviewDialog');dialog.showModal();await load();$('quickReviewCard').focus({preventScroll:true})};$('quickReviewClose').onclick=()=>$('quickReviewDialog').close();$('quickAccept').onclick=accept;$('quickLater').onclick=later;$('quickEdit').onclick=edit;$('quickUndo').onclick=undo;$('quickBulk').onclick=bulk;const card=$('quickReviewCard');card.addEventListener('pointerdown',pointerDown);card.addEventListener('pointerup',pointerUp);card.addEventListener('keydown',event=>{if(event.key==='ArrowRight')accept();if(event.key==='ArrowLeft')later();if(event.key==='ArrowUp'||event.key==='Enter')edit();if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z')undo()})}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
