(()=>{'use strict';
const $=id=>document.getElementById(id),Library=window.KathleenEnglishBulkLibrary,V3=window.KathleenEnglishExtractorV3Core,state={record:null,analysis:null,diff:null};
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function mergeObjects(oldObjects=[],freshObjects=[]){const oldByTask=new Map(oldObjects.filter(x=>x.taskId).map(x=>[x.taskId,x])),merged=[];for(const fresh of freshObjects){const old=oldByTask.get(fresh.taskId);if(!old){merged.push(fresh);continue}const manual=new Set(old.provenance?.manualFields||[]),next={...fresh,reviewStatus:old.reviewStatus||fresh.reviewStatus,approvedUses:old.approvedUses||fresh.approvedUses,provenance:{...fresh.provenance,...old.provenance,reanalyzedAt:new Date().toISOString()}};for(const field of manual)if(Object.hasOwn(old,field))next[field]=old[field];merged.push(next);oldByTask.delete(fresh.taskId)}for(const old of oldByTask.values())merged.push({...old,provenance:{...(old.provenance||{}),notFoundInLatestAnalysis:true}});return merged}
async function preview(){const unit=window.KathleenEnglishKbUi?.current();if(!unit)return;const record=await Library.get(unit.entryId);if(!record?.content?.pages?.length){alert('Für diesen älteren Eintrag sind keine Seitendaten für eine erneute Analyse gespeichert. Die Originaldatei muss erneut eingelesen werden.');return}state.record=record;state.analysis=V3.analyzeDocument(record.content,record.classification,{id:record.id,...record.source});state.diff=V3.compareReanalysis(record,state.analysis);const d=state.diff;$('reanalyzePreview').innerHTML=`<div class="stats"><article class="stat"><b>${d.old.length}</b><small>Bisherige Aufgaben</small></article><article class="stat"><b>${d.fresh.length}</b><small>Neue Vorschläge</small></article><article class="stat"><b>${d.added.length}</b><small>Neu erkannt</small></article><article class="stat"><b>${d.changed.length}</b><small>Geändert</small></article></div><h3>Neue Vorschläge</h3><ul>${d.fresh.map(x=>`<li><b>${esc(x.title)}</b> · ${esc(x.type)} · Seite ${esc(x.pages.join(', '))}</li>`).join('')||'<li>Keine Aufgabe erkannt</li>'}</ul>`;window.KathleenEnglishKbUi.closeDetail();$('reanalyzeDialog').showModal();$('reanalyzeApply').focus()}
async function apply(){if(!state.record||!state.analysis)return;const fresh=V3.toContentObjects(state.analysis),record=structuredClone(state.record);record.content={...record.content,analysisV3:state.analysis,objects:mergeObjects(record.content.objects||[],fresh)};record.classification={...record.classification,grade:record.classification.grade||state.analysis.metadata.grade,unit:record.classification.unit??state.analysis.metadata.unit,topic:record.classification.topic||state.analysis.metadata.topic,section:record.classification.section==='other'?(state.analysis.metadata.contentType||'exercise'):record.classification.section};record.provenance={...record.provenance,reanalyzedAt:new Date().toISOString(),extractorVersion:V3.VERSION};record.schemaVersion='english-extracted-document/v3';await Library.put(record);$('reanalyzeDialog').close();await window.KathleenEnglishKbUi.reload('V3-Analyse übernommen. Manuelle Angaben blieben erhalten.')}
function init(){$('reanalyzeEntry').onclick=preview;$('reanalyzeClose').onclick=()=>$('reanalyzeDialog').close();$('reanalyzeApply').onclick=apply}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
