(()=>{'use strict';
const $=id=>document.getElementById(id),Library=window.KathleenEnglishBulkLibrary,Core=window.KathleenEnglishRecognitionRulesCore,state={rules:[],editing:null};
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const labels={mapping:'Zuordnung',ignore_text:'Text ignorieren',solution_page:'Lösungsseite'};
function render(){const box=$('rulesList');box.innerHTML=state.rules.length?state.rules.map(rule=>`<article class="rule-card ${rule.enabled?'':'disabled'}"><div><b>${esc(rule.label)}</b><p>${esc(labels[rule.kind]||rule.kind)} · Muster: <code>${esc(rule.pattern)}</code>${rule.kind==='mapping'?` · ${esc(rule.field)} = ${esc(rule.value)}`:''}</p></div><div class="actions"><button type="button" class="button soft" data-toggle="${esc(rule.id)}">${rule.enabled?'Deaktivieren':'Aktivieren'}</button><button type="button" class="button soft" data-edit="${esc(rule.id)}">Bearbeiten</button><button type="button" class="button danger" data-delete="${esc(rule.id)}">Löschen</button></div></article>`).join(''):'<p class="empty">Noch keine lokalen Erkennungsregeln angelegt.</p>';box.querySelectorAll('[data-toggle]').forEach(button=>button.onclick=()=>toggle(button.dataset.toggle));box.querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>edit(button.dataset.edit));box.querySelectorAll('[data-delete]').forEach(button=>button.onclick=()=>remove(button.dataset.delete));$('rulesCount').textContent=`${state.rules.filter(x=>x.enabled).length} aktiv · ${state.rules.length} insgesamt`}
async function load(){state.rules=(await Library.rules()).map(Core.normalize).sort((a,b)=>a.label.localeCompare(b.label,'de'));render()}
function reset(){state.editing=null;$('ruleForm').reset();$('ruleEnabled').checked=true;$('ruleField').value='topic';$('ruleKind').value='mapping';syncFields();$('ruleFormTitle').textContent='Neue Regel'}
function syncFields(){const mapping=$('ruleKind').value==='mapping';$('ruleFieldWrap').hidden=!mapping;$('ruleValueWrap').hidden=!mapping}
function edit(id){const rule=state.rules.find(x=>x.id===id);if(!rule)return;state.editing=id;$('ruleLabel').value=rule.label;$('ruleKind').value=rule.kind;$('rulePattern').value=rule.pattern;$('ruleField').value=rule.field;$('ruleValue').value=rule.value;$('ruleEnabled').checked=rule.enabled;syncFields();$('ruleFormTitle').textContent='Regel bearbeiten';$('ruleLabel').focus()}
async function save(event){event.preventDefault();const current=state.rules.find(x=>x.id===state.editing),check=Core.valid({...(current||{}),id:state.editing||undefined,label:$('ruleLabel').value,kind:$('ruleKind').value,pattern:$('rulePattern').value,field:$('ruleField').value,value:$('ruleValue').value,enabled:$('ruleEnabled').checked,createdAt:current?.createdAt});if(!check.valid){$('rulesLive').textContent=check.errors.join(' ');return}await Library.putRule(check.rule);$('rulesLive').textContent='Erkennungsregel gespeichert. Sie wird bei der nächsten Analyse angewendet.';reset();await load()}
async function toggle(id){const rule=state.rules.find(x=>x.id===id);if(!rule)return;await Library.putRule({...rule,enabled:!rule.enabled});await load()}
async function remove(id){const rule=state.rules.find(x=>x.id===id);if(!rule||!confirm(`Lokale Regel „${rule.label}“ löschen? Bereits gespeicherte Aufgaben werden dadurch nicht verändert.`))return;await Library.removeRule(id);$('rulesLive').textContent='Regel gelöscht.';await load()}
async function open(){reset();await load();$('rulesDialog').showModal();$('ruleLabel').focus()}
function init(){$('rulesManage').onclick=open;$('rulesClose').onclick=()=>$('rulesDialog').close();$('ruleCancel').onclick=reset;$('ruleKind').onchange=syncFields;$('ruleForm').onsubmit=save;load().catch(()=>{})}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
