(function(root){'use strict';
const MIME='application/vnd.openxmlformats-officedocument.wordprocessingml.document',W='http://schemas.openxmlformats.org/wordprocessingml/2006/main';
const esc=s=>String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
const encoder=new TextEncoder();
function para(text,style){const styleXml=style?'<w:pPr><w:pStyle w:val="'+style+'"/></w:pPr>':'';return'<w:p>'+styleXml+'<w:r><w:t xml:space="preserve">'+esc(text)+'</w:t></w:r></w:p>'}
function table(rows){const count=Math.max(1,...rows.map(r=>r.length)),grid=Array.from({length:count},()=>'<w:gridCol w:w="'+Math.floor(9000/count)+'"/>').join(''),body=rows.map(row=>'<w:tr>'+Array.from({length:count},(_,i)=>'<w:tc><w:tcPr><w:tcW w:w="'+Math.floor(9000/count)+'" w:type="dxa"/></w:tcPr>'+para(row[i]||'')+'</w:tc>').join('')+'</w:tr>').join('');return'<w:tbl><w:tblPr><w:tblBorders>'+['top','left','bottom','right','insideH','insideV'].map(x=>'<w:'+x+' w:val="single" w:sz="4" w:space="0" w:color="B8B8B8"/>').join('')+'</w:tblBorders></w:tblPr><w:tblGrid>'+grid+'</w:tblGrid>'+body+'</w:tbl>'}
function studentFields(plan){return Object.assign({name:true,class:true,date:true,points:true,note:true,signature:false},plan.configuration&&plan.configuration.student_fields||{})}
function buildDocument(plan,view){const body=[],tasks=plan.tasks||[],total=tasks.reduce((n,t)=>n+Number(t.points||0),0),fields=studentFields(plan),title=plan.title||'Kurzarbeit';body.push(para(title,'Title'));if(view==='student'){body.push(para(plan.subject+' · Jahrgangsstufe '+plan.grade));if(fields.class)body.push(para('Klasse/Kurs: __________________'));if(fields.date)body.push(para('Datum: __________________'));if(fields.name)body.push(para('Name: ______________________________'));if(fields.points)body.push(para('Erreichte Punkte: ______ / '+total));if(plan.configuration&&plan.configuration.scenario)body.push(para(plan.configuration.scenario+' (fiktives Rahmenszenario)'));body.push(para('Arbeitszeit: '+(plan.configuration&&plan.configuration.duration_minutes||'–')+' Minuten. Lies alle Aufgaben sorgfältig.'));tasks.forEach((t,i)=>{body.push(para((i+1)+'. '+t.focus+' ('+t.points+' Punkte)','Heading1'));body.push(para(t.prompt));(t.materials||[]).forEach((m,j)=>{body.push(para('M'+(j+1)+' · '+(m.name||'Material')));if(m.textContent)body.push(para(m.textContent));else if(m.warning)body.push(para(m.warning));else if(m.provenance!=='generated_content')body.push(para('Anlage: Die Originaldatei ist nicht in diesem Word-Dokument eingebettet.'))});for(let k=0;k<(Number(t.minutes)>7?5:3);k++)body.push(para('________________________________________________________________________________'))});if(fields.note)body.push(para('Note: ______'));if(fields.signature)body.push(para('Unterschrift: ______________________________'))}
else if(view==='teacher'){body.push(para('Erwartungshorizont · Lehrkraft','Heading1'));body.push(para(total+' Punkte'));tasks.forEach((t,i)=>{body.push(para((i+1)+'. '+t.focus+' · '+t.points+' Punkte','Heading1'));body.push(para('Aufgabe: '+t.prompt));body.push(para('Lernziel: '+(t.learning_objective||'–')));body.push(para('Operator / AFB: '+(t.operator||'–')+' · '+(t.afb||'–')+' · '+(t.operator_definition||'')));body.push(para('Kompetenz: '+(t.competency&& (t.competency.text||t.competency.note)||'LehrplanPLUS-KB nicht importiert; Zuordnung offen.')));body.push(para('Erwartete Inhalte: '+(t.expected_performance||'Lösungskriterien ergänzen.')));if(t.source_details&&t.source_details.length)body.push(para('Quellenfundstellen: '+t.source_details.map(x=>(x.source&&(x.source.file||x.source.title)||'Knowledge Base')+' '+(x.locator||'Fundstelle offen')+' '+(x.note||'')).join('; ')));const rows=[['Teilkriterium','Punkte'],...(t.rubric||[]).map(r=>[r.criterion,String(r.points)]),['Maximalpunkte',String(t.points)]];body.push(table(rows));body.push(para('Bei offenen Antworten fachlich tragfähige alternative Argumentationslinien berücksichtigen.'))})}
else{body.push(para('Korrekturbogen'));body.push(para(title+' · Name: ____________________________________'));const rows=[['Aufgabe','Teilkriterium','Max.','Erreicht']];tasks.forEach((t,i)=>(t.rubric&&t.rubric.length?t.rubric:[{criterion:t.focus,points:t.points}]).forEach(r=>rows.push([String(i+1),r.criterion,String(r.points),''])));rows.push(['','Gesamt',String(total),'']);body.push(table(rows));body.push(para('Prozent: ________ %     Note: ________'))}
const document='<w:document xmlns:w="'+W+'"><w:body>'+body.join('')+'<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="900" w:right="900" w:bottom="900" w:left="900" w:header="400" w:footer="400" w:gutter="0"/></w:sectPr></w:body></w:document>';
const styles='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="'+W+'"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:sz w:val="22"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:basedOn w:val="Normal"/><w:rPr><w:b/><w:sz w:val="32"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:rPr><w:b/><w:sz w:val="26"/></w:rPr></w:style></w:styles>';
const types='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>';
const rootRels='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>';
const docRels='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>';
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function u16(n){return Uint8Array.of(n&255,(n>>>8)&255)}
function u32(n){return Uint8Array.of(n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255)}
function join(parts){const n=parts.reduce((a,b)=>a+b.length,0),out=new Uint8Array(n);let offset=0;for(const part of parts){out.set(part,offset);offset+=part.length}return out}
function zip(files){const locals=[],central=[];let offset=0;for(const [name,text] of files){const n=encoder.encode(name),d=encoder.encode(text),crc=crc32(d),flags=0x0800;const local=join([u32(0x04034b50),u16(20),u16(flags),u16(0),u16(0),u16(0),u32(crc),u32(d.length),u32(d.length),u16(n.length),u16(0),n,d]);locals.push(local);central.push(join([u32(0x02014b50),u16(20),u16(20),u16(flags),u16(0),u16(0),u16(0),u32(crc),u32(d.length),u32(d.length),u16(n.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),n]));offset+=local.length}const cd=join(central),local=join(locals);return join([local,cd,u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(cd.length),u32(local.length),u16(0)])}
function build(plan,view){const document=buildDocument(plan,view);return zip([['[Content_Types].xml',types],['_rels/.rels',rootRels],['word/document.xml',document],['word/styles.xml',styles],['word/_rels/document.xml.rels',docRels]])}
function download(plan,view){const data=build(plan,view),blob=new Blob([data],{type:MIME}),url=URL.createObjectURL(blob),a=document.createElement('a'),suffix=view==='student'?'Schuelerfassung':view==='teacher'?'Erwartungshorizont':'Korrekturbogen';a.href=url;a.download=(plan.title||'Kurzarbeit').replace(/[^a-z0-9äöüß_-]+/gi,'_')+'_'+suffix+'.docx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
root.AssessmentDocxV1={build,download};
if(typeof module==='object'&&module.exports)module.exports=root.AssessmentDocxV1;
})(typeof window!=='undefined'?window:globalThis);
