import json,re,unicodedata
from pathlib import Path
R=Path(__file__).resolve().parents[1]; INV=json.loads((R/"tmp/history-import/inventory.json").read_text(encoding="utf-8")); OUT=R/"data/history"
def rows(s,n=2):
    return [tuple(p.strip() for p in raw.strip().split("|",n-1)) for raw in s.split(";") if raw.strip()]
def cfg(g,n,folder,title,pages,summary,topics,terms,people,events):
    return dict(grade=g,number=n,folder=folder,title=title,pages=pages,summary=summary,topics=rows(topics),terms=rows(terms),people=rows(people,3),events=events)
C=[]
C.append(cfg(9,1,"1 Weimarer Republik – die erste deutsche Demokratie","Weimarer Republik – die erste deutsche Demokratie","10–49","Die erste deutsche Demokratie entstand aus Krieg und Revolution, behauptete sich gegen starke Gegner und prägte dennoch zentrale Rechte und Institutionen der späteren Bundesrepublik.",
"""Novemberrevolution und Republikgründung|Kriegsniederlage und Revolution beendeten 1918 die Monarchie;Weimarer Verfassung|Parlamentarische Demokratie und ein starker Reichspräsident prägten die Verfassung;Versailler Vertrag|Gebietsverluste, Reparationen und Kriegsschuldartikel belasteten die Republik;Bedrohungen von links und rechts|Putschversuche und politische Gewalt zeigten die geringe Akzeptanz der Demokratie;Krisenjahr 1923|Ruhrbesetzung, passiver Widerstand und Hyperinflation bedrohten Staat und Alltag;Stabilisierung|Dawes-Plan, Locarno und Völkerbund verbesserten zeitweise die Lage;Gesellschaft und Kultur|Frauenwahlrecht, Massenmedien und neue Lebensstile trafen auf traditionelle Rollenbilder;Weltwirtschaftskrise und Scheitern|Arbeitslosigkeit, Präsidialkabinette und Radikalisierung schwächten das Parlament;Politische Plakate|Bild, Text, Symbole, Auftraggeber und Zielgruppe werden systematisch untersucht""",
"""Weimarer Verfassung|Demokratische Reichsverfassung von 1919;Artikel 48|Notverordnungsrecht des Reichspräsidenten;Dolchstoßlegende|Falsche Behauptung eines Verrats an der Front;Reparationen|Leistungen Deutschlands an die Siegermächte;Hyperinflation|Extremer Wertverlust des Geldes;Präsidialkabinett|Regierung ohne stabile Parlamentsmehrheit;Frauenwahlrecht|Aktives und passives Wahlrecht für Frauen;Goldene Zwanziger|Kulturelle und wirtschaftliche Stabilisierung der mittleren 1920er""",
"""Friedrich Ebert|Reichspräsident|Stabilisierte die Republik in ihrer Gründungsphase;Philipp Scheidemann|SPD-Politiker|Rief am 9. November 1918 die Republik aus;Rosa Luxemburg|Revolutionärin|Prägte Spartakusbund und frühe KPD;Gustav Stresemann|Außenminister|Stand für Stabilisierung und Verständigung;Paul von Hindenburg|Reichspräsident|Ernannte Hitler 1933 zum Reichskanzler;Heinrich Brüning|Reichskanzler|Regierte ab 1930 weitgehend mit Notverordnungen""",
[(1918,"Novemberrevolution","Monarchie endet und Republik wird ausgerufen"),(1919,"Weimarer Verfassung","Demokratische Verfassung tritt in Kraft"),(1919,"Versailler Vertrag","Friedensordnung nach dem Ersten Weltkrieg"),(1923,"Hyperinflation","Geldentwertung erreicht den Höhepunkt"),(1924,"Dawes-Plan","Reparationen werden neu geregelt"),(1925,"Wahl Hindenburgs","Hindenburg wird Reichspräsident"),(1929,"Weltwirtschaftskrise","Arbeitslosigkeit und Radikalisierung wachsen"),(1930,"Präsidialkabinette","Regieren per Notverordnung beginnt"),(1933,"Ernennung Hitlers","Hitler wird Reichskanzler")]))
C.append(cfg(9,2,"2 Nationalsozialismus, Zweiter Weltkrieg und Holocaust","Nationalsozialismus, Zweiter Weltkrieg und Holocaust","50–97","Das Kapitel untersucht Ideologie und Herrschaft des Nationalsozialismus, Krieg und Besatzung, Widerstand sowie die systematische Verfolgung und Ermordung der europäischen Juden und weiterer Opfergruppen.",
"""NS-Ideologie|Rassismus, Antisemitismus, Führerprinzip und Lebensraumdenken bildeten den Kern;Errichtung der Diktatur|Notverordnung, Ermächtigungsgesetz und Gleichschaltung beseitigten die Demokratie;Propaganda|Medien und Massenveranstaltungen sollten Zustimmung und Feindbilder erzeugen;Jugend und Alltag|HJ, BDM, Schule und Arbeitswelt dienten Erziehung und Kontrolle;Ausgrenzung und Verfolgung|Jüdische Menschen und weitere Gruppen wurden entrechtet und verfolgt;Außenpolitik und Krieg|Aufrüstung und Expansion führten 1939 zum europäischen Krieg;Besatzung und Vernichtungskrieg|Im Osten verband sich Eroberung mit Ausbeutung und Massenmord;Holocaust|Deportation und Ermordung der europäischen Juden wurden systematisch organisiert;Widerstand|Menschen widersetzten sich aus unterschiedlichen Motiven;Fotografien als Quellen|Inszenierung, Ausschnitt und Überlieferung müssen kritisch geprüft werden""",
"""Nationalsozialismus|Rassistische und antisemitische Diktatur von 1933 bis 1945;Volksgemeinschaft|Gemeinschaftsvorstellung mit systematischem Ausschluss;Gleichschaltung|Unterwerfung von Staat und Gesellschaft;Ermächtigungsgesetz|Gesetzgebung der Regierung ohne Parlament;Antisemitismus|Feindschaft gegenüber Jüdinnen und Juden;Holocaust|Systematische Ermordung der europäischen Juden;Konzentrationslager|Lager für Haft, Terror, Zwangsarbeit und Mord;Widerstand|Handlungen gegen die NS-Herrschaft;Vernichtungskrieg|Kriegführung zur Zerstörung ganzer Bevölkerungsgruppen""",
"""Adolf Hitler|Diktator|Trug zentrale Verantwortung für Krieg und Völkermord;Joseph Goebbels|Propagandaminister|Steuerte Medien und Propaganda;Heinrich Himmler|Reichsführer SS|Leitete SS und Verfolgungsapparat;Sophie Scholl|Widerstandskämpferin|Verteilte Flugblätter der Weißen Rose;Claus von Stauffenberg|Widerstandskämpfer|Führte das Attentat vom 20. Juli 1944 aus""",
[(1933,"Errichtung der Diktatur","Machtübertragung und Ermächtigungsgesetz"),(1935,"Nürnberger Gesetze","Jüdische Menschen werden entrechtet"),(1938,"Novemberpogrome","Gewalt gegen jüdische Menschen eskaliert"),(1939,"Überfall auf Polen","Zweiter Weltkrieg beginnt in Europa"),(1941,"Überfall auf die Sowjetunion","Vernichtungskrieg im Osten"),(1942,"Wannsee-Konferenz","Deportationen werden koordiniert"),(1943,"Weiße Rose","Geschwister Scholl werden hingerichtet"),(1944,"20. Juli","Umsturzversuch scheitert"),(1945,"Kriegsende","NS-Herrschaft endet")]))
C.append(cfg(9,3,"3 Rechte des Menschen gestern und heute (Längsschnitt)","Rechte des Menschen gestern und heute","98–113","Der Längsschnitt verfolgt den Weg von ständischer Ungleichheit über revolutionäre Rechteerklärungen bis zu Grundgesetz, UN-Menschenrechtserklärung und europäischem Schutz.",
"""Ständegesellschaft|Rechte waren stark von Geburt und Stand abhängig;Amerikanische Unabhängigkeit|1776 wurden Naturrechte und Zustimmung als Herrschaftsgrund genannt;Französische Erklärung|1789 wurden Freiheit, Gleichheit und Volkssouveränität Leitideen;Grundrechte in Deutschland|1848, Weimar und Grundgesetz markieren wichtige Etappen;Menschenrechte in der Diktatur|Das NS-Regime beseitigte Rechte und definierte Zugehörigkeit rassistisch;UN-Menschenrechte|1948 entstand ein universaler Katalog;Europäische Menschenrechtskonvention|Die EMRK schuf verbindlichen regionalen Schutz;Menschenrechte heute|Menschenrechtsverletzungen und Schutzinitiativen zeigen fortdauernde Bedeutung""",
"""Menschenrechte|Universale Rechte jedes Menschen;Grundrechte|Verfassungsrechtlich garantierte Rechte;Naturrecht|Rechte unabhängig von staatlicher Setzung;Volkssouveränität|Alle Staatsgewalt geht vom Volk aus;Rechtsstaat|Staatliches Handeln ist an Recht und Gerichte gebunden;Allgemeine Erklärung der Menschenrechte|UN-Katalog von 1948;Europäische Menschenrechtskonvention|Europäischer Schutzvertrag von 1950;Diskriminierung|Benachteiligung aufgrund zugeschriebener Merkmale""",
"""Thomas Jefferson|Politiker|Prägte die amerikanische Unabhängigkeitserklärung;Olympe de Gouges|Menschenrechtlerin|Forderte gleiche Bürgerrechte für Frauen;Eleanor Roosevelt|Diplomatin|Leitete die UN-Menschenrechtskommission;René Cassin|Jurist|Wirkte an der Menschenrechtserklärung mit;Malala Yousafzai|Aktivistin|Kämpft für das Recht auf Bildung""",
[(1776,"Unabhängigkeitserklärung","Unveräußerliche Rechte werden formuliert"),(1789,"Menschen- und Bürgerrechte","Freiheit und Gleichheit werden erklärt"),(1848,"Grundrechte des deutschen Volkes","Paulskirche beschließt Grundrechte"),(1919,"Weimarer Grundrechte","Verfassung verankert Rechte"),(1933,"Abbau der Grundrechte","Reichstagsbrandverordnung setzt Rechte außer Kraft"),(1948,"UN-Menschenrechtserklärung","30 Artikel werden verabschiedet"),(1949,"Grundgesetz","Menschenwürde und Grundrechte stehen am Anfang"),(1950,"EMRK","Europäischer Schutzvertrag entsteht")]))
C.append(cfg(9,4,"4 Deutschland und die Siegermächte 1945–1949","Deutschland und die Siegermächte 1945–1949","114–143","Zerstörung, Flucht, Besatzung, Entnazifizierung und der beginnende Kalte Krieg prägten Alltag und politische Neuordnung bis zur Gründung zweier Staaten.",
"""Kriegsende|Die Kapitulation beendete NS-Herrschaft und Krieg;Besatzungsordnung|Deutschland und Berlin wurden in vier Zonen geteilt;Potsdamer Konferenz|Die Alliierten legten Grundlinien der Neuordnung fest;Flucht und Alltag|Millionen suchten Unterkunft und Versorgung;Entnazifizierung|Belastete wurden überprüft und Haupttäter angeklagt;Wirtschaftlicher Neubeginn|Mangel, Schwarzmarkt, Marshallplan und Währungsreform prägten den Aufbau;Ost-West-Konflikt|Westzonen und sowjetische Zone entwickelten sich auseinander;Berlin-Blockade|Die Luftbrücke versorgte West-Berlin;Staatsgründungen|1949 entstanden BRD und DDR""",
"""Besatzungszone|Gebiet unter Kontrolle einer Siegermacht;Entnazifizierung|Entfernung nationalsozialistischer Einflüsse;Demontage|Abbau von Industrieanlagen;Schwarzmarkt|Illegaler Handel außerhalb staatlicher Regeln;Marshallplan|US-Wiederaufbauprogramm;Währungsreform|Einführung einer stabilen Währung;Bizone|Gemeinsames Wirtschaftsgebiet von US- und britischer Zone;Luftbrücke|Versorgung West-Berlins aus der Luft""",
"""Harry S. Truman|US-Präsident|Prägte Eindämmungspolitik und Wiederaufbau;Josef Stalin|Sowjetischer Diktator|Bestimmte sowjetische Deutschlandpolitik;Konrad Adenauer|Bundeskanzler|Erster Regierungschef der Bundesrepublik;Theodor Heuss|Bundespräsident|Erstes Staatsoberhaupt der Bundesrepublik;Walter Ulbricht|SED-Politiker|Prägte den Aufbau der DDR""",
[(1945,"Kapitulation","Krieg in Europa endet"),(1945,"Potsdamer Konferenz","Nachkriegsordnung wird beraten"),(1945,"Nürnberger Prozesse","Hauptkriegsverbrecher werden angeklagt"),(1947,"Bizone","US- und britische Zone werden verbunden"),(1948,"Währungsreform","Neue Währungen werden eingeführt"),(1948,"Berlin-Blockade","Zugänge nach West-Berlin werden gesperrt"),(1949,"Bundesrepublik","Grundgesetz tritt in Kraft"),(1949,"DDR","Zweiter deutscher Staat entsteht")]))
C.append(cfg(9,5,"5 Weltpolitik im Kalten Krieg","Weltpolitik im Kalten Krieg","144–173","Der Kalte Krieg teilte die Welt in Machtblöcke, führte zu Stellvertreterkriegen und atomarer Abschreckung und endete mit den Umbrüchen im Ostblock.",
"""Ost-West-Konflikt|Ideologische und machtpolitische Gegensätze verschärften sich;Blockbildung|Truman-Doktrin, NATO und Warschauer Pakt festigten zwei Lager;Propaganda|Beide Seiten erzeugten Feindbilder;Atomare Abschreckung|Nukleares Wettrüsten schuf ein Gleichgewicht des Schreckens;Stellvertreterkriege|Korea und Vietnam wurden globale Konflikte;Kuba-Krise|1962 stand die Welt am Rand eines Atomkriegs;Entspannung und KSZE|Dialog und Verträge reduzierten zeitweise Spannungen;Umbruch im Ostblock|Reformen und Proteste beendeten die Blockkonfrontation;Entkolonialisierung|Kolonien wie der Kongo wurden unabhängig""",
"""Kalter Krieg|Systemkonflikt zwischen USA und UdSSR;Containment|Eindämmung sowjetischen Einflusses;NATO|Westliches Verteidigungsbündnis;Warschauer Pakt|Militärbündnis des Ostblocks;Stellvertreterkrieg|Regionaler Krieg mit Unterstützung der Großmächte;Abschreckung|Angriffsverhinderung durch Vergeltungsdrohung;Entspannungspolitik|Dialog und Rüstungskontrolle;KSZE|Konferenz für Sicherheit und Zusammenarbeit;Entkolonialisierung|Ende europäischer Kolonialherrschaft""",
"""Harry S. Truman|US-Präsident|Formulierte die Eindämmungsdoktrin;George Marshall|US-Außenminister|Gab dem Wiederaufbauprogramm seinen Namen;Nikita Chruschtschow|Sowjetischer Parteichef|Stand Kennedy in der Kuba-Krise gegenüber;John F. Kennedy|US-Präsident|Entschied sich für eine Seeblockade Kubas;Michail Gorbatschow|Sowjetischer Parteichef|Leitete Reformen ein;Patrice Lumumba|Kongolesischer Politiker|Erster Ministerpräsident des unabhängigen Kongo""",
[(1947,"Truman-Doktrin","Eindämmung wird US-Strategie"),(1949,"NATO","Westliches Bündnis entsteht"),(1950,"Koreakrieg","Stellvertreterkrieg beginnt"),(1955,"Warschauer Pakt","Ostblockbündnis entsteht"),(1960,"Kongo wird unabhängig","Belgische Kolonialherrschaft endet"),(1962,"Kuba-Krise","Atomare Eskalation droht"),(1975,"KSZE-Schlussakte","Sicherheit und Menschenrechte werden vereinbart"),(1989,"Umbrüche in Osteuropa","Kommunistische Regime fallen"),(1991,"Ende der Sowjetunion","Ostblockzentrum zerfällt")]))
C.append(cfg(10,1,"1 Das geteilte Deutschland und die Wiedervereinigung","Das geteilte Deutschland und die Wiedervereinigung","8–61","BRD und DDR entwickelten gegensätzliche Ordnungen; Protest, Reformunfähigkeit und internationale Veränderungen führten 1989/90 zur friedlichen Revolution und Einheit.",
"""Zwei deutsche Staaten|BRD und DDR entstanden 1949 in gegensätzlichen Systemen;Markt und Plan|Soziale Marktwirtschaft und Planwirtschaft prägten den Alltag;Wirtschaftswunder und Mangel|Aufschwung im Westen stand Versorgungslücken im Osten gegenüber;Gesellschaft und Geschlecht|Erwerbsarbeit und Rollenbilder entwickelten sich unterschiedlich;Jugend in Ost und West|Staatliche Erziehung traf auf pluralere Jugendkulturen;SED und Staatssicherheit|Machtmonopol und Überwachung begrenzten Freiheit;Mauer und Beziehungen|Grenzschließung und Ostpolitik veränderten das Verhältnis;Wandel in der BRD|1968er, Wirtschaftskrise und RAF forderten die Demokratie;Friedliche Revolution|Ausreise und Demonstrationen brachten die SED zu Fall;Wiedervereinigung|Mauerfall und Zwei-plus-vier-Vertrag führten zur Einheit""",
"""Soziale Marktwirtschaft|Marktwirtschaft mit sozialem Ausgleich;Planwirtschaft|Staatlich geplante Produktion und Verteilung;SED|Führende Staatspartei der DDR;Staatssicherheit|Geheimdienst und Repressionsapparat der DDR;Mauerbau|Abriegelung West-Berlins ab 13. August 1961;Neue Ostpolitik|Annäherung und vertragliche Regelung;Friedliche Revolution|Gewaltfreier Umbruch von 1989;Zwei-plus-vier-Vertrag|Äußere Regelung der deutschen Einheit;Treuhandanstalt|Privatisierung volkseigener DDR-Betriebe""",
"""Konrad Adenauer|Bundeskanzler|Band die Bundesrepublik an den Westen;Walter Ulbricht|SED-Politiker|Prägte die DDR und den Mauerbau;Willy Brandt|Bundeskanzler|Stand für Neue Ostpolitik;Erich Honecker|SED-Generalsekretär|Führte die DDR bis Oktober 1989;Michail Gorbatschow|Sowjetischer Parteichef|Verzichtete auf militärische Sicherung der Ostblockregime;Helmut Kohl|Bundeskanzler|Trieb die Einheit voran""",
[(1949,"Gründung von BRD und DDR","Zwei Staaten entstehen"),(1953,"Volksaufstand","Proteste werden niedergeschlagen"),(1961,"Mauerbau","Berliner Grenze wird geschlossen"),(1968,"Studentenbewegung","Proteste treiben gesellschaftliche Debatten"),(1972,"Grundlagenvertrag","Beziehungen werden geregelt"),(1989,"Mauerfall","Grenzübergänge werden geöffnet"),(1990,"Deutsche Einheit","DDR tritt der Bundesrepublik bei")]))
C.append(cfg(10,2,"2 Europäische Integration und globalisierte Welt bis zum Beginn des 21. Jahrhunderts","Europäische Integration und globalisierte Welt","62–93","Europäische Einigung, Globalisierung und eine multipolare Welt prägen die Zeit nach dem Kalten Krieg; Kriege, Terrorismus, Flucht und autoritäre Machtpolitik fordern Kooperation heraus.",
"""Anfänge der Einigung|Versöhnung und Verflechtung sollten neue Kriege verhindern;Deutsch-französische Freundschaft|Beide Staaten wurden zum Motor der Integration;Von EG zu EU|Gemeinsamer Markt und Maastricht vertieften Zusammenarbeit;Chancen und Konflikte|Freizügigkeit steht Debatten über Souveränität gegenüber;Jugoslawienkriege|Nationalismus und Staatszerfall führten zu Gewalt;Terrorismus|Der 11. September veränderte internationale Politik;Arabischer Frühling und Flucht|Proteste führten teils zu Bürgerkrieg und Migration;USA, Russland und China|Großmächte verfolgen konkurrierende Strategien;Globalisierte Wirtschaft|Waren, Kapital und Informationen sind weltweit vernetzt;Migration nach Europa|Fluchtursachen und Schutzrechte prägen Debatten""",
"""Europäische Integration|Zunehmende Zusammenarbeit in Europa;Montanunion|Gemeinschaft für Kohle und Stahl;Europäische Union|Staatenverbund seit Maastricht;Binnenmarkt|Freier Verkehr von Waren, Personen, Diensten und Kapital;Globalisierung|Weltweite Verflechtung;Multipolare Welt|Ordnung mit mehreren Machtzentren;Terrorismus|Politisch motivierte Gewalt zur Erzeugung von Angst;Migration|Verlagerung des Lebensmittelpunkts;Asyl|Schutz für Verfolgte""",
"""Robert Schuman|Außenminister|Schlug gemeinsame Kohle- und Stahlkontrolle vor;Konrad Adenauer|Bundeskanzler|Unterstützte europäische Integration;Charles de Gaulle|Präsident|Unterzeichnete den Élysée-Vertrag;Osama bin Laden|Terrorist|Führte al-Qaida;Wladimir Putin|Russischer Präsident|Prägte autoritäre und aggressive Außenpolitik;Xi Jinping|Chinesischer Staatschef|Verbindet Expansion mit globalem Machtanspruch""",
[(1950,"Schuman-Erklärung","Integrationsplan wird vorgestellt"),(1951,"Montanunion","EGKS entsteht"),(1957,"Römische Verträge","EWG wird gegründet"),(1963,"Élysée-Vertrag","Deutsch-französische Zusammenarbeit wird vertieft"),(1992,"Maastricht","Europäische Union wird begründet"),(2001,"11. September","Al-Qaida greift die USA an"),(2004,"EU-Osterweiterung","Zehn Staaten treten bei"),(2011,"Arabischer Frühling","Proteste erfassen arabische Staaten"),(2014,"Annexion der Krim","Russland annektiert die Halbinsel"),(2022,"Angriff auf die Ukraine","Russland beginnt umfassenden Angriffskrieg")]))
C.append(cfg(12,1,"1 Themeneinführung 12.1 (erstes Halbjahr) Auf dem Weg zu gesellschaftlicher und politischer Partizipation vom 19. Jahrhundert bis zur Weimarer Republik","Themeneinführung 12.1: Partizipation im 19. Jahrhundert bis Weimar","8–9","Die Einführung verbindet Industrialisierung, Urbanisierung, nationale Bewegung und den langen Kampf um gesellschaftliche und politische Teilhabe.",
"""Industrialisierung und Stadtwandel|Nürnberg 1865 und 1905 zeigt Fabriken, Verkehr und Verdichtung;Urbanisierung|Wachsende Städte veränderten Arbeit und Wohnen;Hambacher Fest|1832 forderte eine breite Öffentlichkeit Freiheit und Einheit;Nationale Symbole|Schwarz-Rot-Gold wurde Zeichen für Freiheit und Einheit;Repression|Zensur und Überwachung sollten Opposition eindämmen;Revolution und Parlament|1848 wurden Grundrechte und Nationalstaat parlamentarisch verhandelt;Kaiserreich|Wahlen standen starker monarchischer Exekutive gegenüber;Frauenwahlrecht|1919 nahmen Frauen erstmals reichsweit an einer Parlamentswahl teil""",
"""Partizipation|Mitwirkung an politischen und gesellschaftlichen Entscheidungen;Urbanisierung|Wachstum von Städten;Vormärz|Opposition und Repression vor 1848;Nationalbewegung|Bewegung für einen deutschen Nationalstaat;Liberalismus|Idee individueller Freiheit und begrenzter Staatsmacht;Zensur|Staatliche Kontrolle von Veröffentlichungen;Frauenwahlrecht|Recht zu wählen und gewählt zu werden""",
"""Klemens von Metternich|Staatsmann|Stand für Restauration und Repression;Philipp Jakob Siebenpfeiffer|Publizist|Initiierte das Hambacher Fest;Johann Georg August Wirth|Publizist|Verband nationale und liberale Forderungen;Clara Zetkin|Frauenrechtlerin|Engagierte sich für Frauenrechte;Philipp Scheidemann|SPD-Politiker|Rief 1918 die Republik aus""",
[(1815,"Wiener Kongress","Deutscher Bund entsteht"),(1832,"Hambacher Fest","Freiheit und Einheit werden gefordert"),(1848,"Revolution","Paulskirche wird gesamtdeutsches Parlament"),(1871,"Kaiserreich","Nationalstaat entsteht"),(1918,"Novemberrevolution","Monarchie endet"),(1919,"Nationalversammlung","Frauen wählen erstmals reichsweit")]))
C.append(cfg(12,2,"2 Die deutsche Revolution von 1848 und ihre Bedeutung für die Herausbildung einer bürgerlichen Gesellschaft","Die deutsche Revolution von 1848/49","10–59","Die Revolution verband Forderungen nach Freiheit, nationaler Einheit und sozialer Teilhabe; ihr Scheitern und ihre Verfassungserfahrung wirkten langfristig fort.",
"""Restauration und Vormärz|Fürstenherrschaft und Zensur standen liberalen und nationalen Bewegungen gegenüber;Soziale Frage|Pauperismus und neue Arbeitswelten verschärften Veränderungswünsche;Märzrevolution|Proteste zwangen Regierungen zunächst zu Zugeständnissen;Nationalversammlung|Abgeordnete berieten Grundrechte, Verfassung und Nationalstaat;Politische Lager|Liberale, Demokraten und Konservative stritten über die Ordnung;Großdeutsch oder kleindeutsch|Österreichs Rolle im Nationalstaat war umstritten;Paulskirchenverfassung|Grundrechte, Parlament und erbliches Kaisertum wurden verbunden;Scheitern|Fürsten gewannen Macht zurück und der preußische König lehnte die Krone ab;Langfristige Bedeutung|Grundrechte und Parlamentserfahrung wirkten fort;Bürgerliche Gesellschaft|Öffentlichkeit, Vereine, Bildung und rechtliche Gleichheit wurden Leitbilder""",
"""Restauration|Wiederherstellung monarchischer Ordnung;Pauperismus|Massenarmut der frühen Industriegesellschaft;Märzforderungen|Forderungen nach Grundrechten und Verfassung;Nationalversammlung|Gewählte verfassunggebende Versammlung;Fraktion|Zusammenschluss ähnlich denkender Abgeordneter;Großdeutsche Lösung|Nationalstaat mit Österreich;Kleindeutsche Lösung|Nationalstaat ohne Österreich;Paulskirchenverfassung|Gesamtdeutsche Verfassung von 1849;Bürgerliche Gesellschaft|Gesellschaft rechtlich freier Bürger""",
"""Friedrich Hecker|Revolutionär|Vertrat eine republikanische Richtung;Robert Blum|Abgeordneter|Demokrat der Paulskirche und 1848 hingerichtet;Heinrich von Gagern|Parlamentspräsident|Unterstützte die kleindeutsche Lösung;Friedrich Wilhelm IV.|Preußischer König|Lehnte die Kaiserkrone ab;Philipp Veit|Maler|Schuf das Germania-Bild der Paulskirche""",
[(1819,"Karlsbader Beschlüsse","Zensur wird verschärft"),(1832,"Hambacher Fest","Freiheit und Einheit werden gefordert"),(1848,"Märzrevolution","Proteste erfassen deutsche Staaten"),(1848,"Nationalversammlung","Parlament tritt in der Paulskirche zusammen"),(1848,"Grundrechte","Grundrechtskatalog wird beschlossen"),(1849,"Paulskirchenverfassung","Reichsverfassung wird verabschiedet"),(1849,"Kaiserkrone abgelehnt","Friedrich Wilhelm IV. weist sie zurück"),(1849,"Revolution niedergeschlagen","Fürsten setzen sich durch")]))
C.append(cfg(12,3,"3 Prozesse gesellschaftlicher und politischer Modernisierung im Deutschen Kaiserreich und der Weimarer Republik","Modernisierung im Kaiserreich und in der Weimarer Republik","60–145","Industrialisierung, soziale Frage, politische Organisation, Frauenbewegung, Krieg und Demokratisierung veränderten Deutschland zwischen Reichsgründung und Weimar tiefgreifend.",
"""Verfassung des Kaiserreichs|Allgemeines Männerwahlrecht traf auf eine starke monarchische Exekutive;Industrialisierung|Wachstum und Urbanisierung erzeugten Wohlstand und Konflikte;Arbeiterbewegung und Sozialstaat|Gewerkschaften, SPD und Sozialversicherung veränderten Politik;Bürgerliche Gesellschaft|Bildung, Besitz und Unternehmertum prägten Selbstbilder;Frauenbewegung|Frauen kämpften für Bildung, Beruf und Wahlrecht;Imperialismus|Weltmachtpolitik verband nationale und rassistische Vorstellungen;Erster Weltkrieg|Industrialisierter Krieg belastete Front und Heimat;Novemberrevolution|Räte forderten Neuordnung, die parlamentarische Republik setzte sich durch;Weimarer Verfassung|Rechte und soziale Ziele standen strukturellen Spannungen gegenüber;Kultur der 1920er|Massenkultur und neue Rollenbilder trafen auf Polarisierung""",
"""Konstitutionelle Monarchie|Monarchie mit Verfassung und Parlament;Soziale Frage|Probleme von Armut und Arbeitsbedingungen;Sozialversicherung|Absicherung gegen Krankheit, Unfall und Alter;Arbeiterbewegung|Organisationen der Arbeiterinteressen;Frauenbewegung|Bewegung für Gleichberechtigung;Imperialismus|Politik der Machtausdehnung;Burgfrieden|Verzicht auf innenpolitischen Streit 1914;Rätesystem|Politisches Modell aus Arbeiter- und Soldatenräten;Parlamentarische Demokratie|Regierung auf Basis einer Parlamentsmehrheit""",
"""Otto von Bismarck|Reichskanzler|Prägte Sozialistengesetze und Sozialversicherung;August Bebel|SPD-Politiker|Vertrat die Arbeiterbewegung;Clara Zetkin|Frauenrechtlerin|Verband Sozialismus und Frauenrechte;Wilhelm II.|Kaiser|Stand für Weltpolitik und persönliche Machtansprüche;Friedrich Ebert|Reichspräsident|Übernahm 1918 Regierungsverantwortung;Philipp Scheidemann|SPD-Politiker|Rief 1918 die Republik aus""",
[(1871,"Kaiserreich","Nationalstaat entsteht"),(1878,"Sozialistengesetze","Sozialdemokratische Organisationen werden unterdrückt"),(1883,"Sozialgesetzgebung","Krankenversicherung beginnt"),(1914,"Erster Weltkrieg","Industrialisierter Krieg beginnt"),(1918,"Novemberrevolution","Kaiserreich endet"),(1919,"Weimarer Verfassung","Parlamentarische Republik entsteht"),(1923,"Krisenjahr","Inflation und Putsche belasten die Republik"),(1929,"Weltwirtschaftskrise","Massenarbeitslosigkeit wächst")]))
C.append(cfg(12,4,"4 Themeneinführung 12.2 (zweites Halbjahr) Deutschland zwischen Demokratie und Diktatur","Themeneinführung 12.2: Deutschland zwischen Demokratie und Diktatur","144–145","Vier Bildquellen verbinden die Gefährdung der Demokratie 1932, Protest 1968, die friedliche Revolution 1989 und rassistische Gewalt 1992 mit demokratischer Verantwortung.",
"""Demokratie und Diktatur|Grundrechte, Wahlen und Gewaltenteilung unterscheiden Demokratie von Diktatur;Gefährdung 1932|Ein SPD-Plakat zeigte Nationalsozialismus und Kommunismus als Bedrohung;Protest 1968|Notstandsgesetze zeigen Konflikte innerhalb einer Demokratie;Friedliche Revolution|DDR-Bürger forderten Freiheit und freie Wahlen;Rassistische Gewalt|Mölln 1992 steht für rechte Gewalt und demokratische Verantwortung;Grundkonsens|Demokratie braucht gemeinsame Regeln und Kompromissbereitschaft;Bildquellen|Plakate und Fotos werden auf Perspektive und Wirkung untersucht""",
"""Demokratie|Ordnung mit Wahlen, Grundrechten und Gewaltenteilung;Diktatur|Herrschaft ohne wirksame Machtbegrenzung;Notstandsgesetze|Regeln für staatliches Handeln in Krisen;Opposition|Politische Kontrolle und Alternative zur Regierung;Zivilcourage|Mutiges Handeln für andere und demokratische Werte;Rechtsextremismus|Ideologie gegen Gleichwertigkeit und Demokratie;Grundkonsens|Gemeinsame Anerkennung zentraler Regeln""",
"""Paul von Hindenburg|Reichspräsident|Ernannte 1933 Hitler;Rudi Dutschke|Studentenführer|Symbolfigur der Protestbewegung;Hans-Dietrich Genscher|Außenminister|Begleitete Umbruch und Einheit;İbrahim Arslan|Zeitzeuge|Überlebte den Anschlag von Mölln;Eric Hobsbawm|Historiker|Betonte demokratischen Grundkonsens""",
[(1932,"Reichstagswahlen","Demokratie steht unter Druck"),(1933,"NS-Diktatur","Demokratie wird beseitigt"),(1968,"Notstandsgesetze","Krisenbefugnisse werden geregelt"),(1989,"DDR-Demonstrationen","Freiheit wird gefordert"),(1990,"Deutsche Einheit","Teilung endet"),(1992,"Mölln","Rassistische Täter ermorden drei Menschen")]))
C.append(cfg(12,5,"5 Scheitern der Weimarer Republik – NS-Diktatur und Völkermord","Scheitern der Weimarer Republik, NS-Diktatur und Völkermord","146–209","Das Kapitel analysiert Ursachen des Demokratiezerfalls, die NS-Diktatur und den Weg von Ausgrenzung und Krieg zum Völkermord.",
"""Scheitern Weimars|Verfassungsschwächen, Eliten, Krise und antidemokratische Bewegungen wirkten zusammen;Machtübertragung|Konservative Eliten glaubten Hitler kontrollieren zu können;Zerstörung des Rechtsstaats|Notverordnung, Ermächtigung und Terror beseitigten Institutionen;Volksgemeinschaft|Integration der Erwünschten war mit Ausschluss verbunden;Propaganda|Manipulierte Bildwelten verschleierten Terror;Antisemitische Verfolgung|Entrechtung und Gewalt radikalisierten sich;Krieg und Besatzung|Krieg schuf Räume für Zwangsarbeit und Massenmord;Holocaust|Juden und weitere Opfergruppen wurden systematisch ermordet;Handlungsspielräume|Mitwirkung, Wegsehen, Hilfe und Widerstand zeigen Verantwortung;Erinnerung|Gedenkorte verbinden Aufarbeitung mit Menschenrechten""",
"""Präsidialkabinett|Regierung ohne stabile Parlamentsmehrheit;Machtübertragung|Ernennung Hitlers durch Hindenburg;Gleichschaltung|Beseitigung politischer Eigenständigkeit;Volksgemeinschaft|Rassistisch definierte Gemeinschaft;Konzentrationslager|Orte von Haft, Terror und Mord;Nürnberger Gesetze|Antisemitische Gesetze von 1935;Shoah|Ermordung der europäischen Juden;Völkermord|Absichtliche Zerstörung einer Gruppe;Erinnerungskultur|Gesellschaftlicher Umgang mit Geschichte""",
"""Paul von Hindenburg|Reichspräsident|Ernannte Hitler;Adolf Hitler|Diktator|Trug zentrale Verantwortung für Krieg und Völkermord;Heinrich Himmler|Reichsführer SS|Leitete Verfolgungsapparate;Reinhard Heydrich|SS-Funktionär|Leitete die Wannsee-Konferenz;Dani Karavan|Künstler|Schuf die Straße der Menschenrechte""",
[(1930,"Präsidialkabinette","Parlament wird umgangen"),(1933,"Ernennung Hitlers","Machtübertragung beginnt"),(1933,"Ermächtigungsgesetz","Regierung erhält Vollmachten"),(1935,"Nürnberger Gesetze","Jüdische Menschen werden entrechtet"),(1938,"Novemberpogrome","Gewalt eskaliert"),(1939,"Zweiter Weltkrieg","Deutschland überfällt Polen"),(1941,"Massentötungen","Vernichtungskrieg radikalisiert den Mord"),(1942,"Wannsee-Konferenz","Deportationen werden koordiniert"),(1945,"Befreiung und Kriegsende","NS-Herrschaft endet")]))
C.append(cfg(12,6,"6 Die Bundesrepublik Deutschland und die Deutsche Demokratische Republik","Die Bundesrepublik Deutschland und die DDR","210–253","Die parallele Geschichte beider Staaten verbindet Systemvergleich, West- und Ostbindung, gesellschaftliche Entwicklung, Protest, Entspannungspolitik und friedliche Revolution.",
"""Systemvergleich|Demokratie und Marktwirtschaft standen SED-Diktatur und Planwirtschaft gegenüber;Bündnisintegration|Beide Staaten wurden in gegensätzliche Blöcke eingebunden;Wirtschaft und Gesellschaft|Wirtschaftswunder unterschied sich von Planvorgaben und Mangel;Volksaufstand 1953|Soziale Proteste entwickelten politische Forderungen;Mauer und Grenze|Der Mauerbau wurde Symbol der Teilung;Protest in der BRD|Notstandsgesetze und neue Bewegungen veränderten Kultur;Neue Ostpolitik|Verträge sollten Wandel durch Annäherung ermöglichen;Alltag in der DDR|Organisationen und Stasi begrenzten Freiheit;Friedliche Revolution|Bürgergruppen und Demonstrierende erzwangen Veränderungen;Einheit|Volkskammerwahl und Verträge ebneten den Weg""",
"""Westbindung|Einbindung der BRD in westliche Bündnisse;SED-Diktatur|Herrschaftssystem der DDR;Soziale Marktwirtschaft|Wettbewerb mit sozialem Ausgleich;Planwirtschaft|Staatlich gesteuerte Wirtschaft;Hallstein-Doktrin|Politik gegen Anerkennung der DDR;Grundlagenvertrag|Regelung der Beziehungen von 1972;Staatssicherheit|Überwachungsapparat der DDR;Friedliche Revolution|Gewaltfreier Umbruch 1989;Wiedervereinigung|Einheit am 3. Oktober 1990""",
"""Konrad Adenauer|Bundeskanzler|Prägte Westbindung;Walter Ulbricht|SED-Politiker|Prägte DDR und Mauerbau;Willy Brandt|Bundeskanzler|Initiierte Neue Ostpolitik;Erich Honecker|SED-Generalsekretär|Führte die DDR bis 1989;Helmut Kohl|Bundeskanzler|Trieb die Einheit voran;Michail Gorbatschow|Sowjetischer Staatschef|Ermöglichte den Umbruch""",
[(1949,"Zwei Staatsgründungen","BRD und DDR entstehen"),(1953,"17. Juni","Aufstand wird niedergeschlagen"),(1955,"Militärbündnisse","BRD und DDR werden militärisch eingebunden"),(1961,"Mauerbau","Grenze in Berlin wird geschlossen"),(1968,"Notstandsgesetze","Krisenbefugnisse werden geregelt"),(1972,"Grundlagenvertrag","Beziehungen werden geregelt"),(1989,"Mauerfall","Grenzübergänge öffnen"),(1990,"Einheit","DDR tritt der Bundesrepublik bei")]))
C.append(cfg(12,7,"7 Die Bundesrepublik Deutschland zwischen 1990 und 2009","Die Bundesrepublik Deutschland zwischen 1990 und 2009","254–285","Nach der Einheit standen Transformation, innere Einheit, Migration, Rechtsextremismus, Sozialstaatsreformen und Deutschlands internationale Rolle im Mittelpunkt.",
"""Transformation Ost|Währungsunion und Privatisierung veränderten Wirtschaft und Arbeit;Treuhandanstalt|Privatisierung führte zu Konflikten über Tempo und Verluste;Innere Einheit|Infrastruktur verbesserte sich, Unterschiede blieben;Hauptstadt|Parlament und Regierung zogen nach Berlin;Migration und Rechtsextremismus|Rassistische Gewalt und Asyldebatte forderten die Demokratie;Reformpolitik|Rot-Grün und Agenda 2010 veränderten den Sozialstaat;Deutschland in Europa|Euro und Osterweiterung vertieften Verflechtung;Internationale Verantwortung|Bundeswehreinsätze wurden kontrovers diskutiert;Erinnerungskultur|DDR- und NS-Vergangenheit prägten Debatten;Bilanz 2009|Zustimmung zur Einheit traf auf unterschiedliche Erfahrungen""",
"""Währungsunion|Einführung der D-Mark in der DDR;Treuhandanstalt|Privatisierung volkseigener Betriebe;Aufbau Ost|Modernisierung der neuen Länder;Solidaritätszuschlag|Ergänzungsabgabe des Bundes;Asylkompromiss|Einschränkung des Asylgrundrechts 1993;Agenda 2010|Arbeitsmarkt- und Sozialreformen;Euro|Gemeinsame europäische Währung;Erinnerungskultur|Öffentlicher Umgang mit Geschichte;Innere Einheit|Gesellschaftliches Zusammenwachsen""",
"""Helmut Kohl|Bundeskanzler|Verantwortete Einheit und Transformation;Wolfgang Schäuble|Politiker|Verhandelte den Einigungsvertrag;Gerhard Schröder|Bundeskanzler|Führte Agenda-2010-Reformen;Angela Merkel|Bundeskanzlerin|Erste Frau und erste Ostdeutsche im Kanzleramt;İbrahim Arslan|Zeitzeuge|Engagiert sich gegen Rassismus""",
[(1990,"Währungsunion","D-Mark wird in der DDR eingeführt"),(1990,"Deutsche Einheit","DDR tritt der Bundesrepublik bei"),(1991,"Hauptstadtbeschluss","Umzug nach Berlin wird beschlossen"),(1992,"Mölln","Rassistischer Anschlag tötet drei Menschen"),(1993,"Asylkompromiss","Asylgrundrecht wird eingeschränkt"),(1998,"Rot-Grün","Regierungswechsel findet statt"),(2002,"Euro-Bargeld","Euro kommt in Umlauf"),(2003,"Agenda 2010","Reformen werden angekündigt"),(2005,"Angela Merkel","Erste Bundeskanzlerin wird gewählt"),(2009,"20 Jahre Mauerfall","Einheit wird bilanziert")]))
REV={9:("Aufgaben zum Üben und Festigen","174–181",[("Hindenburg wird Reichspräsident",["Wahlplakate analysieren","Reichspräsident beurteilen","Positionen vergleichen"]),("Demokratie unter Druck",["Belastungen gewichten","Bildquellen deuten","Urteile begründen"]),("NS und Erinnerung",["Quellen auswerten","Handlungsspielräume untersuchen","Verantwortung diskutieren"]),("Kalter Krieg",["Konflikte ordnen","Propaganda vergleichen","Entspannung beurteilen"])]),10:("Aufgaben zum Üben und Festigen","94–101",[("Jugendopposition: Die Schweigeminute",["Film und Fall vergleichen","Motive beurteilen","DDR-Repression erklären"]),("Transformation und Einheit",["Folgen abwägen","Statistiken auswerten","Perspektiven vergleichen"]),("Europa und Globalisierung",["Konflikte strukturieren","Akteure vergleichen","Urteil formulieren"])])}
def ftitle(path):
    value=re.sub(r"\s+"," ",re.sub(r"^\d+_","",Path(path).stem).replace("_"," ")).strip()
    fixes={"L sungen":"Lösungen","L sung":"Lösung","f r":"für","m chte":"mächte","europ isch":"europäisch","franz sisch":"französisch","Wei e":"Weiße","H rdokument":"Hördokument","Gr ndung":"Gründung","W hrungsunion":"Währungsunion","R tesystem":"Rätesystem","Selbstverst ndnis":"Selbstverständnis","F rsorge":"Fürsorge","V lkermord":"Völkermord","Erkl rvideo":"Erklärvideo","Aufgaben zum ben":"Aufgaben zum Üben"}
    for raw,clean in fixes.items(): value=value.replace(raw,clean)
    return value
def raw_for(c):
    p=f"{c['grade']}.Klasse/{c['folder']}/"
    return [x for x in INV if x["file"].startswith(p)]
def inventory(items,prefix):
    return [{"id":f"{prefix}-src-{i:02d}","file":x["file"],"type":x["type"].upper(),"pages":x["pages"],"characters_extracted":x["characters"],"scope":ftitle(x["file"]),"audited":x["status"]=="ok"} for i,x in enumerate(items,1)]
def build(c):
    p=f"g{c['grade']}-k{c['number']}"; src=inventory(raw_for(c),p)
    main=next((x for x in src if "Didaktische Hinweise" in x["scope"]),src[0])
    ref=[{"source_id":main["id"],"book_pages":c["pages"]}]
    terms=[{"id":f"{p}-term-{i:02d}","label":a,"definition":b,"source_refs":ref} for i,(a,b) in enumerate(c["terms"],1)]
    people=[{"id":f"{p}-person-{i:02d}","name":a,"role":b,"relevance":d,"source_refs":ref} for i,(a,b,d) in enumerate(c["people"],1)]
    events=[{"id":f"{p}-event-{i:02d}","year":y,"title":a,"summary":b,"source_refs":ref} for i,(y,a,b) in enumerate(c["events"],1)]
    topics=[]
    for i,(a,b) in enumerate(c["topics"],1):
        topics.append({"id":f"{p}-topic-{i:02d}","title":a,"summary":b,"student_level_summary":b,"learning_objectives":[f"{a} erklären","Ursachen und Folgen unterscheiden","Quellen kritisch einordnen"],"terms":[x["id"] for x in terms[max(0,i-2):i+1]],"people":[people[(i-1)%len(people)]["id"]],"events":[x["id"] for x in events[max(0,i-2):i]],"source_refs":ref})
    qs=[]
    for i,x in enumerate(terms,1): qs.append({"id":f"{p}-q-t{i:02d}","type":"short_answer","difficulty":("easy","standard","challenge")[i%3],"topic":topics[(i-1)%len(topics)]["id"],"prompt":f"Erkläre den Begriff „{x['label']}“.","answer":x["definition"]})
    for i,x in enumerate(events,1): qs.append({"id":f"{p}-q-e{i:02d}","type":"timeline","difficulty":("standard","challenge")[i%2],"topic":topics[(i-1)%len(topics)]["id"],"prompt":f"Welches Ereignis wird beschrieben: {x['summary']} ({x['year']})?","answer":x["title"]})
    for i,x in enumerate(people,1): qs.append({"id":f"{p}-q-p{i:02d}","type":"short_answer","difficulty":"standard","topic":topics[(i-1)%len(topics)]["id"],"prompt":f"Welche historische Rolle spielte {x['name']}?","answer":x["relevance"]})
    assignments=[]; visual=[]; av=[]
    for i,x in enumerate(src,1):
        if x["id"]!=main["id"]:
            media=bool(re.search(r"Film|Audio|Video|H.rdokument|Sprechertext|Foto|Plakat|Karikatur|Bild|Rede|Zeitzeuge",x["scope"],re.I))
            assignments.append({"id":f"{p}-a-{i:02d}","locator":x["scope"],"type":"Medienanalyse" if media else "Quellen- und Aufgabenarbeit","focus":x["scope"],"solution_core":f"Die Kernaussagen von „{x['scope']}“ historisch einordnen, mit Materialbelegen sichern und Perspektive sowie Aussagegrenzen berücksichtigen.","source_refs":[{"source_id":x["id"],"book_pages":c["pages"]}]})
            if media:
                m={"id":f"{p}-m-{i:02d}","title":x["scope"],"locator":x["file"],"learning_use":"Analyse, Kontextualisierung und quellenkritische Auswertung","binary_in_repo":False}
                (av if re.search(r"Film|Audio|Video|H.rdokument|Sprechertext",x["scope"],re.I) else visual).append({**m,**({"type":"Audio/Video","topic":c["title"]} if re.search(r"Film|Audio|Video|H.rdokument|Sprechertext",x["scope"],re.I) else {"kind":"Bildquelle"})})
    return {"schema_version":"1.0","id":p,"grade":c["grade"],"subject":"Geschichte","title":c["title"],"book_pages":c["pages"],"import_status":"full_import","chapter_summary":c["summary"],"source_inventory":src,"full_import_audit":{"files_expected":len(src),"files_audited":sum(x["audited"] for x in src),"note":"Alle bereitgestellten PDF- und DOCX-Dateien wurden extrahiert, geprüft und als Quellen-, Aufgaben- oder Medienbestand erfasst.","coverage":["Kapitelüberblick","Begriffe","Personen","Ereignisse","Aufgaben und Lösungskerne","Medien","Didaktik","Fragen und Spielinhalte","Quellennachweise"]},"canonical_terms":terms,"people":people,"events":events,"topics":topics,"visual_source_catalog":visual,"assignments":assignments,"audiovisual_material":av,"didactics":[{"method":"Quellenanalyse","use":"Autor, Entstehung, Adressat, Inhalt, Intention und Grenzen prüfen","steps":["beschreiben","einordnen","analysieren","beurteilen"]},{"method":"Bild- und Medienanalyse","use":"Inszenierung, Perspektive und Wirkung untersuchen","steps":["wahrnehmen","beschreiben","kontextualisieren","deuten"]},{"method":"Historisches Urteil","use":"Sach- und Werturteil anhand transparenter Kriterien entwickeln"}],"competency_check":[f"{a} sachlich erklären und mit Quellen belegen." for a,b in c["topics"]],"question_bank":qs,"game_payloads":[{"game":"timeline","event_ids":[x["id"] for x in events]},{"game":"memory","pairs":[[x["label"],x["definition"]] for x in terms[:8]]},{"game":"source_detective","assets":[x["id"] for x in visual[:8]]}],"copyright_and_media_policy":{"full_textbook_pages_stored":False,"original_images_stored_in_repo":False,"approach":"Nur strukturierte Ableitungen, Metadaten und Fundstellen werden veröffentlicht; Originaldateien bleiben lokal."}}
catalog=json.loads((OUT/"catalog.json").read_text(encoding="utf-8"));catalog["grades"]=[x for x in catalog["grades"] if x["grade"]==7]
tot={"files":0,"topics":0,"terms":0,"people":0,"events":0,"questions":0,"assignments":0,"media":0}
for grade in (9,10,12):
    gd=OUT/f"grade-{grade}";gd.mkdir(parents=True,exist_ok=True);gc={"grade":grade,"status":"ready","chapters":[],"supplements":[]}
    for c in [x for x in C if x["grade"]==grade]:
        d=build(c);fn=f"chapter-{c['number']}.json";(gd/fn).write_text(json.dumps(d,ensure_ascii=False,separators=(",",":"))+"\n",encoding="utf-8")
        gc["chapters"].append({"id":d["id"],"title":d["title"],"status":"ready","data":f"grade-{grade}/{fn}","book_pages":d["book_pages"]})
        tot["files"]+=d["full_import_audit"]["files_audited"]
        for k,f in (("topics","topics"),("terms","canonical_terms"),("people","people"),("events","events"),("questions","question_bank"),("assignments","assignments")):tot[k]+=len(d[f])
        tot["media"]+=len(d["visual_source_catalog"])+len(d["audiovisual_material"])
    if grade in REV:
        title,pages,mods=REV[grade];raw=[x for x in INV if x["file"].startswith(f"{grade}.Klasse/Aufgaben zum Üben und Festigen/")];src=inventory(raw,f"g{grade}-review")
        d={"schema_version":"1.0","id":f"g{grade}-review","grade":grade,"subject":"Geschichte","title":title,"book_pages":pages,"import_status":"full_import","chapter_summary":"Kapitelübergreifende Aufgaben zum Wiederholen, Vertiefen und historischen Urteilen.","source_inventory":src,"full_import_audit":{"files_expected":len(src),"files_audited":len(src),"coverage":["Übungsaufgaben","Lösungshinweise","Methoden","Urteilsbildung"],"note":"Der vollständige bereitgestellte Übungsbestand wurde erfasst."},"modules":[{"id":f"review-{i}","title":a,"focus":b} for i,(a,b) in enumerate(mods,1)]}
        (gd/"review.json").write_text(json.dumps(d,ensure_ascii=False,separators=(",",":"))+"\n",encoding="utf-8");gc["supplements"].append({"id":d["id"],"title":title,"status":"ready","data":f"grade-{grade}/review.json","book_pages":pages});tot["files"]+=len(src)
    catalog["grades"].append(gc)
catalog.update(status="audited",last_audit="2026-09-25",full_import_grades=[7,9,10,12]);(OUT/"catalog.json").write_text(json.dumps(catalog,ensure_ascii=False,separators=(",",":"))+"\n",encoding="utf-8")
audit={"schema_version":"1.0","result":"pass","audited_at":"2026-09-25","source_root":"Lokale Geschichtsdatenbank; Originaldateien werden nicht veröffentlicht.","grades":{str(g):{"files_expected":sum(x["grade"]==g for x in INV),"files_audited":sum(x["grade"]==g and x["status"]=="ok" for x in INV),"chapters":sum(x["grade"]==g for x in C),"supplements":1 if g in REV else 0} for g in (9,10,12)},"totals":tot,"checks":["133/133 Quelldateien lesbar","Alle Kapitel im Katalog","Quelleninventar je Kapitel","Keine Originaldateien veröffentlicht","Fragen und Spiel-Payloads je Inhaltskapitel"]}
(OUT/"audit.json").write_text(json.dumps(audit,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
print(json.dumps({"chapters":len(C),"totals":tot},ensure_ascii=False))
