(()=>{'use strict';
const $=s=>document.querySelector(s),BASE='../../data/vocabulary/';
const S={catalog:null,entries:[],pool:[],deck:[],duel:0,score:[0,0],position:0,target:3,phase:'setup',started:0,timer:null,names:['Team Rose','Team Lila'],lastGoal:false};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function read(k,f=null){try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch(e){return f}}
async function get(path){const r=await fetch(BASE+path);if(!r.ok)throw Error(path);return r.json()}
function shuffle(a){const x=[...a];for(let i=x.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
async function load(){try{S.catalog=await get('catalog.json');const paths=[];for(const g of S.catalog.grades){if(g.supplementary)paths.push(g.supplementary.data);paths.push(...g.units.map(u=>u.data))}const docs=await Promise.all(paths.map(get));S.entries=docs.flatMap(d=>d.entries.map(x=>({...x,grade:d.grade})));setupUnits();restoreSelection();updatePool()}catch(e){$('#poolInfo').textContent='Die Vokabeldaten konnten nicht geladen werden.';$('#poolInfo').classList.add('error');$('#setupForm button').disabled=true}}
function meta(){return S.catalog.grades.find(x=>x.grade===Number($('#grade').value))}
function setupUnits(){const g=meta(),o=['<option value="all">Alle Units</option>'];if(g.supplementary)o.push('<option value="0">Zusatzmaterial</option>');g.units.forEach(u=>o.push(`<option value="${u.unit}">Unit ${u.unit} · ${esc(u.title)}</option>`));$('#unit').innerHTML=o.join('');setupSections()}
function setupSections(){const grade=Number($('#grade').value),unit=$('#unit').value,sections=[...new Set(S.entries.filter(x=>x.grade===grade&&(unit==='all'||String(x.unit??0)===unit)).map(x=>x.section))].sort((a,b)=>a.localeCompare(b,'de'));$('#section').innerHTML='<option value="all">Alle Abschnitte</option>'+sections.map(x=>`<option>${esc(x)}</option>`).join('')}
function filtered(){const grade=Number($('#grade').value),unit=$('#unit').value,section=$('#section').value;return S.entries.filter(x=>x.grade===grade&&(unit==='all'||String(x.unit??0)===unit)&&(section==='all'||x.section===section))}
function restoreSelection(){const payload=read('kathleenVocabularyFootballPayloadV1');if(new URLSearchParams(location.search).get('selection')==='1'&&payload?.ids?.length){const chosen=S.entries.filter(x=>payload.ids.includes(x.id));if(chosen.length>=2){S.pool=chosen;$('#grade').value=String(chosen[0].grade);setupUnits();$('#poolInfo').textContent=`Eigene Auswahl · ${chosen.length} Vokabeln`;$('#poolInfo').dataset.selection='1'}}}
function updatePool(){if($('#poolInfo').dataset.selection==='1')return;S.pool=filtered();$('#poolInfo').textContent=`${S.pool.length.toLocaleString('de-DE')} Vokabeln im Kader`}
function makeQuestion(entry,index){let direction=$('#direction').value;if(direction==='mixed')direction=index%2?'de-en':'en-de';return direction==='de-en'?{prompt:entry.german,answer:entry.english,label:'ÜBERSETZT INS ENGLISCHE',say:entry.english,entry}:{prompt:entry.english,answer:entry.german,label:'ÜBERSETZT INS DEUTSCHE',say:entry.english,entry}}
function kickoff(e){e.preventDefault();S.names=[$('#teamA').value.trim()||'Team Rose',$('#teamB').value.trim()||'Team Lila'];S.target=Number($('#goalTarget').value);const base=$('#poolInfo').dataset.selection==='1'?S.pool:filtered();if(base.length<2){$('#poolInfo').textContent='Bitte eine Auswahl mit mindestens zwei Vokabeln wählen.';return}S.pool=base;S.deck=shuffle(base);S.duel=0;S.score=[0,0];S.position=0;S.started=Date.now();S.phase='question';$('#setup').classList.add('hidden');$('#result').classList.add('hidden');$('#game').classList.remove('hidden');$('#nameA').textContent=S.names[0];$('#nameB').textContent=S.names[1];clearInterval(S.timer);S.timer=setInterval(updateClock,1000);updateClock();showQuestion()}
function updateClock(){const n=Math.floor((Date.now()-S.started)/1000);$('#clock').textContent=String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function currentQuestion(){if(S.duel&&S.duel%S.deck.length===0)S.deck=shuffle(S.pool);return makeQuestion(S.deck[S.duel%S.deck.length],S.duel)}
function showQuestion(){S.phase='question';S.lastGoal=false;const q=currentQuestion();S.question=q;$('#roundLabel').textContent=`DUELL ${S.duel+1}`;$('#pairLabel').textContent=`Paarung ${S.duel+1}`;$('#prompt').textContent=q.prompt;$('#directionLabel').textContent=q.label;$('#answerText').textContent=q.answer;$('#phonetic').textContent=q.entry.phonetic?`[${q.entry.phonetic}]`:'';$('#source').textContent=`${q.entry.unit?'Unit '+q.entry.unit:'Zusatzmaterial'} · ${q.entry.section} · Seite ${q.entry.page}`;$('#answer').classList.add('hidden');$('#reveal').classList.remove('hidden');$('#teamAWin').classList.add('hidden');$('#teamBWin').classList.add('hidden');$('#nobody').classList.add('hidden');$('#next').classList.add('hidden');$('#next').textContent='Nächstes Paar →';$('#pitchMessage').className='pitch-message';$('#pitchMessage').textContent=positionText();updatePitch();updateScore();syncLive()}
function positionText(){return S.position===0?'Der Ball liegt in der Mitte.':S.position===1?`${S.names[0]} greift an – noch ein Duell bis zum Tor.`:`${S.names[1]} greift an – noch ein Duell bis zum Tor.`}
function reveal(){if(S.phase!=='question')return;S.phase='answer';$('#answer').classList.remove('hidden');$('#reveal').classList.add('hidden');$('#teamAWin').textContent=`${S.names[0]} war schneller →`;$('#teamBWin').textContent=`← ${S.names[1]} war schneller`;$('#teamAWin').classList.remove('hidden');$('#teamBWin').classList.remove('hidden');$('#nobody').classList.remove('hidden');$('#status').textContent='WER WAR SCHNELLER?';tone(520,.08)}
function award(team){if(S.phase!=='answer')return;S.phase='result';const delta=team===0?1:-1,next=S.position+delta;hideDecision();if(next>1||next<-1){S.score[team]++;S.position=0;S.lastGoal=true;$('#pitchMessage').className='pitch-message goal';$('#pitchMessage').textContent=`TOR FÜR ${S.names[team].toUpperCase()}!`;$('#status').textContent='TOR';goalSound();confetti();try{window.KathleenGamification?.action?.('learning_game','','Vokabel-Fußball')}catch(e){}}else{S.position=next;$('#pitchMessage').textContent=positionText();$('#status').textContent=S.position===0?'ABGEWEHRT · BALLMITTE':`ANGRIFF ${S.names[team].toUpperCase()}`;whistle()}updatePitch();updateScore();const won=S.score[team]>=S.target;$('#next').textContent=won?'Zum Endergebnis →':'Nächstes Paar →';$('#next').classList.remove('hidden');syncLive(won)}
function skip(){if(S.phase!=='answer')return;S.phase='result';hideDecision();$('#pitchMessage').textContent='Keine Wertung · Ball bleibt liegen.';$('#status').textContent='NEUE VOKABEL';$('#next').classList.remove('hidden');syncLive()}
function hideDecision(){$('#teamAWin').classList.add('hidden');$('#teamBWin').classList.add('hidden');$('#nobody').classList.add('hidden')}
function updatePitch(){const p=$('#pitch');p.classList.remove('position-left','position-center','position-right','goal-flash');p.classList.add(S.position<0?'position-left':S.position>0?'position-right':'position-center');if(S.lastGoal){void p.offsetWidth;p.classList.add('goal-flash')}}
function updateScore(){$('#scoreA').textContent=S.score[0];$('#scoreB').textContent=S.score[1]}
function next(){const winner=S.score.findIndex(x=>x>=S.target);if(winner>=0)return finish(winner);S.duel++;showQuestion()}
function finish(winner){clearInterval(S.timer);$('#game').classList.add('hidden');$('#result').classList.remove('hidden');$('#finalA').textContent=S.score[0];$('#finalB').textContent=S.score[1];$('#winner').textContent=S.names[winner]+' gewinnt!';$('#resultText').textContent=`${S.duel+1} Vokabelduelle gespielt · zuerst ${S.target} Tore erreicht.`;confetti(90);syncLive(true)}
function replay(){$('#result').classList.add('hidden');$('#setup').classList.remove('hidden')}
function speak(){const q=S.question;if(!q||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(q.say);u.lang='en-GB';u.rate=.88;speechSynthesis.speak(u)}
let audioCtx;function tone(freq,duration){try{audioCtx ||= new AudioContext();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;o.connect(g);g.connect(audioCtx.destination);g.gain.setValueAtTime(.1,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.start();o.stop(audioCtx.currentTime+duration)}catch(e){}}
function whistle(){tone(950,.08);setTimeout(()=>tone(1250,.1),80)}function goalSound(){[523,659,784,1047].forEach((n,i)=>setTimeout(()=>tone(n,.22),i*90))}
function confetti(n=48){const root=$('#confetti'),colors=['#f6d276','#ec94bd','#a894ef','#fff'];for(let i=0;i<n;i++){const c=document.createElement('i');c.className='confetti';c.style.left=Math.random()*100+'vw';c.style.background=colors[i%colors.length];c.style.setProperty('--drift',(Math.random()*180-90)+'px');c.style.animationDelay=Math.random()*.4+'s';root.appendChild(c);setTimeout(()=>c.remove(),3000)}}
function syncLive(done=false){try{localStorage.setItem('kathleenVocabularyFootballLiveV1',JSON.stringify({names:S.names,score:S.score,position:S.position,duel:S.duel+1,target:S.target,status:done?'finished':S.phase,updatedAt:Date.now()}));window.dispatchEvent(new CustomEvent('kathleen:game-action',{detail:{source:'vocabulary-football',type:S.phase}}))}catch(e){}}
$('#grade').onchange=()=>{delete $('#poolInfo').dataset.selection;setupUnits();updatePool()};$('#unit').onchange=()=>{delete $('#poolInfo').dataset.selection;setupSections();updatePool()};$('#section').onchange=()=>{delete $('#poolInfo').dataset.selection;updatePool()};$('#setupForm').onsubmit=kickoff;$('#reveal').onclick=reveal;$('#teamAWin').onclick=()=>award(0);$('#teamBWin').onclick=()=>award(1);$('#nobody').onclick=skip;$('#next').onclick=next;$('#replay').onclick=replay;$('#speak').onclick=speak;$('#fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();addEventListener('keydown',e=>{if(e.key===' '&&S.phase==='question'){e.preventDefault();reveal()}if(e.key==='ArrowRight')award(0);if(e.key==='ArrowLeft')award(1)});load();
})();
