(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],BASE='../../data/vocabulary/';
const S={catalog:null,entries:[],pool:[],questions:[],round:0,total:10,score:[0,0],team:0,phase:'setup',started:0,timer:null,names:['Team Rose','Team Lila']};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function read(k,f=null){try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch(e){return f}}
async function get(path){const r=await fetch(BASE+path);if(!r.ok)throw Error(path);return r.json()}
function shuffle(a){const x=[...a];for(let i=x.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
async function load(){try{S.catalog=await get('catalog.json');const paths=[];for(const g of S.catalog.grades){if(g.supplementary)paths.push(g.supplementary.data);paths.push(...g.units.map(u=>u.data))}const docs=await Promise.all(paths.map(get));S.entries=docs.flatMap(d=>d.entries.map(x=>({...x,grade:d.grade})));setupUnits();restoreSelection();updatePool()}catch(e){$('#poolInfo').textContent='Die Vokabeldaten konnten nicht geladen werden.';$('#poolInfo').classList.add('error');$('#setupForm button').disabled=true}}
function meta(){return S.catalog.grades.find(x=>x.grade===Number($('#grade').value))}
function setupUnits(){const g=meta(),o=['<option value="all">Alle Units</option>'];if(g.supplementary)o.push('<option value="0">Zusatzmaterial</option>');g.units.forEach(u=>o.push(`<option value="${u.unit}">Unit ${u.unit} · ${esc(u.title)}</option>`));$('#unit').innerHTML=o.join('');setupSections()}
function setupSections(){const grade=Number($('#grade').value),unit=$('#unit').value,sections=[...new Set(S.entries.filter(x=>x.grade===grade&&(unit==='all'||String(x.unit??0)===unit)).map(x=>x.section))].sort((a,b)=>a.localeCompare(b,'de'));$('#section').innerHTML='<option value="all">Alle Abschnitte</option>'+sections.map(x=>`<option>${esc(x)}</option>`).join('')}
function filtered(){const grade=Number($('#grade').value),unit=$('#unit').value,section=$('#section').value;return S.entries.filter(x=>x.grade===grade&&(unit==='all'||String(x.unit??0)===unit)&&(section==='all'||x.section===section))}
function restoreSelection(){const payload=read('kathleenVocabularyFootballPayloadV1');if(new URLSearchParams(location.search).get('selection')==='1'&&payload?.ids?.length){const chosen=S.entries.filter(x=>payload.ids.includes(x.id));if(chosen.length>=2){S.pool=chosen;$('#grade').value=String(chosen[0].grade);setupUnits();$('#poolInfo').textContent=`Eigene Auswahl · ${chosen.length} Vokabeln`;$('#poolInfo').dataset.selection='1'}}}
function updatePool(){if($('#poolInfo').dataset.selection==='1')return;S.pool=filtered();$('#poolInfo').textContent=`${S.pool.length.toLocaleString('de-DE')} Vokabeln im Kader`}
function question(x,i){let direction=$('#direction').value;if(direction==='mixed')direction=i%2?'de-en':'en-de';return direction==='de-en'?{prompt:x.german,answer:x.english,label:'ÜBERSETZT INS ENGLISCHE',say:x.english,entry:x}:{prompt:x.english,answer:x.german,label:'ÜBERSETZT INS DEUTSCHE',say:x.english,entry:x}}
function kickoff(e){e.preventDefault();S.names=[$('#teamA').value.trim()||'Team Rose',$('#teamB').value.trim()||'Team Lila'];S.total=Number($('#rounds').value);const base=$('#poolInfo').dataset.selection==='1'?S.pool:filtered();if(base.length<2){$('#poolInfo').textContent='Bitte eine Auswahl mit mindestens zwei Vokabeln wählen.';return}const shuffled=shuffle(base);S.questions=Array.from({length:S.total},(_,i)=>question(shuffled[i%shuffled.length],i));S.round=0;S.score=[0,0];S.started=Date.now();S.phase='question';$('#setup').classList.add('hidden');$('#result').classList.add('hidden');$('#game').classList.remove('hidden');$('#nameA').textContent=S.names[0];$('#nameB').textContent=S.names[1];clearInterval(S.timer);S.timer=setInterval(updateClock,1000);showQuestion()}
function updateClock(){const n=Math.floor((Date.now()-S.started)/1000);$('#clock').textContent=String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function showQuestion(){S.team=S.round%2;S.phase='question';const q=S.questions[S.round];$('#roundLabel').textContent=`RUNDE ${S.round+1} / ${S.total}`;$('#status').textContent='AM BALL';$('#turnTeam').textContent=S.names[S.team];$('#teamDot').style.background=S.team?'var(--lilac)':'var(--rose)';$('#prompt').textContent=q.prompt;$('#directionLabel').textContent=q.label;$('#answerText').textContent=q.answer;$('#phonetic').textContent=q.entry.phonetic?`[${q.entry.phonetic}]`:'';$('#source').textContent=`${q.entry.unit?'Unit '+q.entry.unit:'Zusatzmaterial'} · ${q.entry.section} · Seite ${q.entry.page}`;$('#answer').classList.add('hidden');$('#reveal').classList.remove('hidden');$('#correct').classList.add('hidden');$('#wrong').classList.add('hidden');$('#next').classList.add('hidden');$('#pitch').classList.remove('shooting');$('#pitchMessage').className='pitch-message';$('#pitchMessage').textContent='Erst richtig antworten, dann schießen.';$('#keeper').className='keeper';$('#ball').className='ball';updateScore();syncLive()}
function reveal(){S.phase='answer';$('#answer').classList.remove('hidden');$('#reveal').classList.add('hidden');$('#correct').classList.remove('hidden');$('#wrong').classList.remove('hidden');$('#status').textContent='ANTWORT PRÜFEN';tone(520,.08)}
function correct(){S.phase='shoot';$('#correct').classList.add('hidden');$('#wrong').classList.add('hidden');$('#pitch').classList.add('shooting');$('#pitchMessage').textContent=`${S.names[S.team]}: Ecke wählen · 1, 2 oder 3`;$('#status').textContent='TORSCHUSS';whistle()}
function wrong(){S.phase='done';$('#correct').classList.add('hidden');$('#wrong').classList.add('hidden');$('#pitchMessage').textContent='Ballverlust · kein Torschuss';$('#status').textContent='BALLVERLUST';$('#next').classList.remove('hidden');tone(170,.22);syncLive()}
function shoot(side){if(S.phase!=='shoot')return;S.phase='done';$('#pitch').classList.remove('shooting');const keeper=['left','center','right'][Math.floor(Math.random()*3)],goal=keeper!==side;$('#keeper').className='keeper '+keeper;$('#ball').className='ball '+side;setTimeout(()=>{if(goal){S.score[S.team]++;$('#pitchMessage').className='pitch-message goal';$('#pitchMessage').textContent='TOOOR!';$('#status').textContent='TOR';goalSound();confetti();try{window.KathleenGamification?.action?.('learning_game','','Vokabel-Fußball')}catch(e){}}else{$('#pitchMessage').textContent='GEHALTEN!';$('#status').textContent='PARADE';tone(210,.35)}updateScore();$('#next').classList.remove('hidden');syncLive()},620)}
function updateScore(){$('#scoreA').textContent=S.score[0];$('#scoreB').textContent=S.score[1]}
function next(){if(++S.round>=S.total)return finish();showQuestion()}
function finish(){clearInterval(S.timer);$('#game').classList.add('hidden');$('#result').classList.remove('hidden');$('#finalA').textContent=S.score[0];$('#finalB').textContent=S.score[1];const winner=S.score[0]===S.score[1]?null:S.score[0]>S.score[1]?0:1;$('#winner').textContent=winner===null?'Unentschieden!':S.names[winner]+' gewinnt!';$('#resultText').textContent=`${S.total} Vokabelrunden gespielt · ${S.score[0]+S.score[1]} Tore erzielt.`;if(winner!==null)confetti(90);syncLive(true)}
function replay(){$('#result').classList.add('hidden');$('#setup').classList.remove('hidden')}
function speak(){const q=S.questions[S.round];if(!q||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(q.say);u.lang='en-GB';u.rate=.88;speechSynthesis.speak(u)}
let audioCtx;function tone(freq,duration){try{audioCtx ||= new AudioContext();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;o.connect(g);g.connect(audioCtx.destination);g.gain.setValueAtTime(.12,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.start();o.stop(audioCtx.currentTime+duration)}catch(e){}}
function whistle(){tone(1200,.08);setTimeout(()=>tone(1550,.16),85)}function goalSound(){[523,659,784,1047].forEach((n,i)=>setTimeout(()=>tone(n,.22),i*90))}
function confetti(n=48){const root=$('#confetti'),colors=['#f6d276','#ec94bd','#a894ef','#fff'];for(let i=0;i<n;i++){const c=document.createElement('i');c.className='confetti';c.style.left=Math.random()*100+'vw';c.style.background=colors[i%colors.length];c.style.setProperty('--drift',(Math.random()*180-90)+'px');c.style.animationDelay=Math.random()*.4+'s';root.appendChild(c);setTimeout(()=>c.remove(),3000)}}
function syncLive(done=false){try{localStorage.setItem('kathleenVocabularyFootballLiveV1',JSON.stringify({names:S.names,score:S.score,round:S.round+1,total:S.total,status:done?'finished':S.phase,updatedAt:Date.now()}));window.dispatchEvent(new CustomEvent('kathleen:game-action',{detail:{source:'vocabulary-football',type:S.phase}}))}catch(e){}}
$('#grade').onchange=()=>{delete $('#poolInfo').dataset.selection;setupUnits();updatePool()};$('#unit').onchange=()=>{delete $('#poolInfo').dataset.selection;setupSections();updatePool()};$('#section').onchange=()=>{delete $('#poolInfo').dataset.selection;updatePool()};$('#setupForm').onsubmit=kickoff;$('#reveal').onclick=reveal;$('#correct').onclick=correct;$('#wrong').onclick=wrong;$$('[data-shot]').forEach(b=>b.onclick=()=>shoot(b.dataset.shot));$('#next').onclick=next;$('#replay').onclick=replay;$('#speak').onclick=speak;$('#fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();addEventListener('keydown',e=>{if(e.key===' '&&S.phase==='question'){e.preventDefault();reveal()}if(['1','2','3'].includes(e.key))shoot(['left','center','right'][Number(e.key)-1])});load();
})();
