-- ============================================================
-- Kathleens Classroom Board · V22.7 LIVE POLL
-- Run once AFTER V21 Classroom Stability.
-- Non-destructive: adds poll tables + RPCs only.
-- ============================================================

begin;

create table if not exists public.classroom_polls (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.classroom_sessions(id) on delete cascade,
  poll_key text not null,
  question text not null default '',
  options jsonb not null default '[]'::jsonb,
  is_open boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(session_id,poll_key)
);

create table if not exists public.classroom_poll_votes (
  poll_id bigint not null references public.classroom_polls(id) on delete cascade,
  participant_id uuid not null references public.classroom_participants(id) on delete cascade,
  choice integer not null,
  updated_at timestamptz not null default now(),
  primary key(poll_id,participant_id)
);

alter table public.classroom_polls enable row level security;
alter table public.classroom_poll_votes enable row level security;

create index if not exists classroom_polls_session_idx on public.classroom_polls(session_id);
create index if not exists classroom_poll_votes_poll_idx on public.classroom_poll_votes(poll_id);

create or replace function public.classroom_poll_open(
  p_session uuid,
  p_teacher_token uuid,
  p_poll_key text,
  p_question text,
  p_options jsonb
)
returns boolean language plpgsql security definer set search_path=public,pg_catalog as $$
declare
  v_poll_id bigint;
  v_key text:=left(trim(coalesce(p_poll_key,'')),120);
  v_question text:=left(trim(coalesce(p_question,'')),300);
begin
  if not exists(
    select 1 from public.classroom_sessions
    where id=p_session and teacher_token=p_teacher_token and status='open'
  ) then return false; end if;

  if length(v_key)<1 or length(v_question)<1
     or p_options is null or jsonb_typeof(p_options)<>'array'
     or jsonb_array_length(p_options)<2 or jsonb_array_length(p_options)>8
     or octet_length(p_options::text)>8000
  then return false; end if;

  insert into public.classroom_polls(session_id,poll_key,question,options,is_open,updated_at)
  values(p_session,v_key,v_question,p_options,true,now())
  on conflict(session_id,poll_key) do update
    set question=excluded.question,
        options=excluded.options,
        is_open=true,
        updated_at=now()
  returning id into v_poll_id;

  delete from public.classroom_poll_votes where poll_id=v_poll_id;
  return true;
end $$;

create or replace function public.classroom_poll_close(
  p_session uuid,
  p_teacher_token uuid,
  p_poll_key text
)
returns boolean language plpgsql security definer set search_path=public,pg_catalog as $$
begin
  if not exists(
    select 1 from public.classroom_sessions
    where id=p_session and teacher_token=p_teacher_token
  ) then return false; end if;

  update public.classroom_polls
     set is_open=false,updated_at=now()
   where session_id=p_session and poll_key=left(trim(coalesce(p_poll_key,'')),120);

  return found;
end $$;

create or replace function public.classroom_poll_results(
  p_session uuid,
  p_teacher_token uuid,
  p_poll_key text
)
returns jsonb language plpgsql security definer set search_path=public,pg_catalog as $$
declare
  v_poll public.classroom_polls;
  v_counts jsonb;
  v_total integer;
begin
  if not exists(
    select 1 from public.classroom_sessions
    where id=p_session and teacher_token=p_teacher_token
  ) then return jsonb_build_object('ok',false); end if;

  select * into v_poll
    from public.classroom_polls
   where session_id=p_session and poll_key=left(trim(coalesce(p_poll_key,'')),120)
   limit 1;

  if v_poll.id is null then
    return jsonb_build_object('ok',false,'error','poll_not_found');
  end if;

  select coalesce(jsonb_agg(coalesce(v.cnt,0) order by i.n),'[]'::jsonb)
    into v_counts
    from generate_series(0,jsonb_array_length(v_poll.options)-1) as i(n)
    left join (
      select choice,count(*)::integer as cnt
        from public.classroom_poll_votes
       where poll_id=v_poll.id
       group by choice
    ) v on v.choice=i.n;

  select count(*)::integer into v_total
    from public.classroom_poll_votes
   where poll_id=v_poll.id;

  return jsonb_build_object(
    'ok',true,
    'open',v_poll.is_open,
    'question',v_poll.question,
    'options',v_poll.options,
    'counts',v_counts,
    'total',v_total
  );
end $$;

create or replace function public.classroom_student_poll_vote(
  p_student_token uuid,
  p_poll_key text,
  p_choice integer
)
returns boolean language plpgsql security definer set search_path=public,pg_catalog as $$
declare
  v_participant public.classroom_participants;
  v_poll public.classroom_polls;
begin
  select * into v_participant
    from public.classroom_participants
   where student_token=p_student_token
   limit 1;

  if v_participant.id is null then return false; end if;

  select * into v_poll
    from public.classroom_polls
   where session_id=v_participant.session_id
     and poll_key=left(trim(coalesce(p_poll_key,'')),120)
     and is_open=true
   limit 1;

  if v_poll.id is null
     or p_choice is null
     or p_choice<0
     or p_choice>=jsonb_array_length(v_poll.options)
  then return false; end if;

  insert into public.classroom_poll_votes(poll_id,participant_id,choice,updated_at)
  values(v_poll.id,v_participant.id,p_choice,now())
  on conflict(poll_id,participant_id) do update
    set choice=excluded.choice,updated_at=now();

  update public.classroom_participants
     set last_seen=now()
   where id=v_participant.id;

  return true;
end $$;

revoke all on table public.classroom_polls from anon,authenticated;
revoke all on table public.classroom_poll_votes from anon,authenticated;

revoke execute on function public.classroom_poll_open(uuid,uuid,text,text,jsonb) from public;
revoke execute on function public.classroom_poll_close(uuid,uuid,text) from public;
revoke execute on function public.classroom_poll_results(uuid,uuid,text) from public;
revoke execute on function public.classroom_student_poll_vote(uuid,text,integer) from public;

grant execute on function public.classroom_poll_open(uuid,uuid,text,text,jsonb) to anon,authenticated;
grant execute on function public.classroom_poll_close(uuid,uuid,text) to anon,authenticated;
grant execute on function public.classroom_poll_results(uuid,uuid,text) to anon,authenticated;
grant execute on function public.classroom_student_poll_vote(uuid,text,integer) to anon,authenticated;

commit;
notify pgrst,'reload schema';

select
  to_regclass('public.classroom_polls') is not null as poll_table_ok,
  to_regclass('public.classroom_poll_votes') is not null as poll_votes_ok,
  to_regprocedure('public.classroom_poll_open(uuid,uuid,text,text,jsonb)') is not null as poll_open_ok,
  to_regprocedure('public.classroom_student_poll_vote(uuid,text,integer)') is not null as poll_vote_ok;
