(()=>{
'use strict';
if(window.KathleenClassroomSession)return;
const script=document.currentScript,TOOLS=new URL('./',script?.src||location.href),HOME=new URL('../',TOOLS);
const SB='https://fzqxnjhuvgpgovcovosl.supabase.co/rest/v1/rpc/';
const KEY='sb_publishable_GIyyWoyaQXipaA4S9OuTyQ_cZn7LUgV';
const ADMIN_KEY='kathleenAdminPass',QR_NEXT='kathleenShowQrOnNextPageV53';
const loadScript=src=>new Promise((resolve,reject)=>{const absolute=new URL(src,TOOLS),old=[...document.scripts].find(s=>{try{return new URL(s.src).pathname===absolute.pathname}catch(e){return false}});if(old){if(old.dataset.loaded==='1'||old.readyState==='complete')return resolve();let done=false;const finish=()=>{if(done)return;done=true;resolve()};old.addEventListener('load',finish,{once:true});old.addEventListener('error',reject,{once:true});setTimeout(finish,50);return}const s=document.createElement('script');s.src=absolute.href;s.onload=()=>{s.dataset.loaded='1';resolve()};s.onerror=reject;document.head.appendChild(s)});
async function deps(){if(!window.KathleenClassLists)await loadScript('classroom-tools-shared.js?v=20260923-session1');if(!window.KathleenLessonMode)await loadScript('lesson-mode.js?v=20260923-session1');if(!window.KathleenTeacherRuntime)await loadScript('teacher-runtime-v54.js?v=20260923-v54')}
async function rpc(name,body){const r=await fetch(SB+name,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(body||{})});if(!r.ok)throw new Error(name+' '+r.status+' '+await r.text());return r.json()}
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
function get(){try{return window.KathleenClassLists?.getClassroomState?.()||JSON.parse(sessionStorage.getItem('kathleenClassroom')||'null')}catch(e){return null}}
function studentUrl(room=get()?.room_code){const u=new URL('tools/classroom-board/student.html',HOME);if(room)u.searchParams.set('room',room);return u.href}
function classByEntry(entry,lists){const id=String(entry?.classId||''),name=String(entry?.className||entry?.class||'').trim().toLocaleLowerCase('de-DE');return lists.find(c=>String(c.id)===id)||lists.find(c=>String(c.name).trim().toLocaleLowerCase('de-DE')===name)||null}
async function authenticate(pass){if(!pass)throw new Error('Adminpasswort fehlt');const ok=!!(await rpc('classroom_authenticate',{p_passphrase:pass}));if(!ok){sessionStorage.removeItem(ADMIN_KEY);throw new Error('Adminpasswort falsch')}sessionStorage.setItem(ADMIN_KEY,pass);return true}
async function close(opts={}){await deps();const room=get();if(!room?.session_id){window.KathleenClassLists?.clearClassroomState?.();return true}try{await rpc('classroom_teacher_command',{p_session:room.session_id,p_teacher_token:room.teacher_token,p_command:'close',p_participant:null,p_value:{}})}catch(e){if(!opts.silent)throw e}try{sessionStorage.removeItem('kathleenClassroom');window.KathleenClassLists?.clearClassroomState?.()}catch(e){}window.dispatchEvent(new CustomEvent('kathleen:classroomsession',{detail:null}));return true}
async function create(entry,{classId,className,subject,room,pass}={}){await deps();if(!await window.KathleenClassLists.requireUnlock())throw new Error('Klassenlisten gesperrt');const lists=window.KathleenClassLists.load(),base=classByEntry(entry,lists),cl=lists.find(c=>String(c.id)===String(classId||''))||base;if(!cl)throw new Error('Bitte eine Klasse auswählen');const existing=get();if(existing?.session_id){const same=String(existing.classId||'')===String(cl.id);if(!same)await close({silent:true});else{const lesson=window.KathleenLessonMode?.get?.();if(!lesson){window.KathleenLessonMode?.start?.({...entry,classId:cl.id,className:cl.name,subject:subject||entry?.subject||'',room:room||entry?.room||''},{navigate:false})}return existing}}
 const admin=String(pass||sessionStorage.getItem(ADMIN_KEY)||'');await authenticate(admin);
 const created=await rpc('classroom_create',{p_passphrase:admin,p_title:(subject||entry?.subject||'Unterricht')+' · '+cl.name,p_class_name:cl.name});
 const roster=await rpc('classroom_set_roster',{p_session:created.session_id,p_teacher_token:created.teacher_token,p_class_name:cl.name,p_names:cl.students});if(!roster)throw new Error('Klassenliste konnte nicht übertragen werden');
 window.KathleenClassLists.setGlobalClass?.(cl.id,cl.name);const state=window.KathleenClassLists.setClassroomState?.(created,{classId:cl.id,className:cl.name,rosterCount:cl.students.length,connectedCount:0,sessionState:'open'})||created;sessionStorage.setItem('kathleenClassroom',JSON.stringify(state));
 const fullEntry={...(entry||{}),classId:cl.id,className:cl.name,subject:String(subject||entry?.subject||''),room:String(room||entry?.room||'')};window.KathleenLessonMode?.start?.(fullEntry,{navigate:false});
 window.dispatchEvent(new CustomEvent('kathleen:classroomsession',{detail:state}));return state}
async function teacherState(){await deps();const room=get();if(!room?.session_id||!room?.teacher_token)return null;try{const s=await rpc('classroom_teacher_state',{p_session:room.session_id,p_teacher_token:room.teacher_token});if(!s?.ok||s.session_state!=='open'){await close({silent:true});return null}window.KathleenClassLists.updateClassroomState?.({className:s.class_name||room.className||'',classId:room.classId||'',connectedCount:(s.participants||[]).filter(p=>p.online).length,rosterCount:Number(s.roster_count)||Number(room.rosterCount)||0,sessionState:s.session_state||'open'});return s}catch(e){return null}}
function ensureQrLib(){if(window.QRCode)return Promise.resolve();return new Promise((resolve,reject)=>{const old=[...document.scripts].find(s=>s.src.includes('qrcodejs'));if(old){old.addEventListener('load',resolve,{once:true});old.addEventListener('error',reject,{once:true});if(window.QRCode)resolve();return}const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
async function showQr(room=get()){if(!room?.room_code)return;document.getElementById('kdsQrOverlay')?.remove();const o=document.createElement('div');o.id='kdsQrOverlay';o.className='kds-qr-overlay';const url=studentUrl(room.room_code);o.innerHTML='<div class="kds-qr-card"><button class="kds-qr-close" type="button">×</button><div class="kds-qr-kicker">KLASSENSESSION AKTIV</div><h2>Schüler einwählen</h2><p>QR-Code scannen oder den Raumcode eingeben.</p><div class="kds-qr-code" id="kdsQrCode"></div><div class="kds-room-code">'+esc(room.room_code)+'</div><div class="kds-qr-actions"><button data-copy type="button">Schülerlink kopieren</button><a href="'+url+'" target="_blank" rel="noopener">Schüleransicht öffnen</a></div></div>';document.body.appendChild(o);const close=()=>o.remove();o.querySelector('.kds-qr-close').onclick=close;o.onclick=e=>{if(e.target===o)close()};o.querySelector('[data-copy]').onclick=async()=>{try{await navigator.clipboard.writeText(url);o.querySelector('[data-copy]').textContent='Kopiert ✓'}catch(e){prompt('Schülerlink:',url)}};try{await ensureQrLib();new QRCode(document.getElementById('kdsQrCode'),{text:url,width:220,height:220,colorDark:'#55455e',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M})}catch(e){document.getElementById('kdsQrCode').innerHTML='<a href="'+url+'" target="_blank">Schülerlink öffnen</a>'}}
async function openStartDialog(entry={}){await deps();if(!await window.KathleenClassLists.requireUnlock())return;document.getElementById('kdsStartLesson')?.remove();const lists=window.KathleenClassLists.load(),hit=classByEntry(entry,lists)||window.KathleenClassLists.get?.(window.KathleenClassLists.getGlobalClass?.()?.id)||lists[0]||null;const passSaved=!!sessionStorage.getItem(ADMIN_KEY),d=document.createElement('div');d.id='kdsStartLesson';d.className='kds-start-overlay';d.innerHTML='<form class="kds-start-card"><div class="kds-start-kicker">UNTERRICHT STARTEN</div><h2>Stunde starten</h2><p>Klasse, Fach und Raum prüfen. Danach wird die Klassensession erstellt und der Sitzplan geöffnet.</p><label>Klasse<select name="classId">'+lists.map(c=>'<option value="'+esc(c.id)+'"'+(hit?.id===c.id?' selected':'')+'>'+esc(c.name)+'</option>').join('')+'</select></label><div class="kds-start-grid"><label>Fach<input name="subject" value="'+esc(entry.subject||'')+'" placeholder="z. B. Englisch"></label><label>Raum<input name="room" value="'+esc(entry.room||'')+'" placeholder="z. B. A-101"></label></div><label>Classroom-Adminpasswort<input name="pass" type="password" autocomplete="current-password" placeholder="'+(passSaved?'Gespeichert – leer lassen':'für die Session-Erstellung')+'"></label><label class="kds-start-check"><input name="qr" type="checkbox" checked> QR-Code nach dem Start direkt anzeigen</label><div class="kds-start-actions"><button type="button" data-cancel>Abbrechen</button><button class="primary" type="submit">Session starten</button></div><div class="kds-start-status" aria-live="polite"></div></form>';document.body.appendChild(d);const form=d.querySelector('form'),status=d.querySelector('.kds-start-status');d.querySelector('[data-cancel]').onclick=()=>d.remove();d.onclick=e=>{if(e.target===d)d.remove()};form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form),btn=form.querySelector('[type="submit"]');btn.disabled=true;status.textContent='Klassensession wird gestartet …';try{await create(entry,{classId:fd.get('classId'),subject:fd.get('subject'),room:fd.get('room'),pass:fd.get('pass')});if(fd.get('qr'))sessionStorage.setItem(QR_NEXT,'1');d.remove();location.href=new URL('tools/seating-plan/',HOME).href}catch(err){status.textContent=err?.message||'Session konnte nicht gestartet werden.';btn.disabled=false}}}
function consumeQrRequest(){if(sessionStorage.getItem(QR_NEXT)!=='1')return false;sessionStorage.removeItem(QR_NEXT);return true}
window.KathleenClassroomSession={deps,rpc,get,create,close,teacherState,studentUrl,showQr,openStartDialog,consumeQrRequest,keys:{qrNext:QR_NEXT}};
})();