(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.KathleenEnglishAiCore=api})(typeof window!=='undefined'?window:globalThis,function(){
'use strict';
const ACTIONS=['analyze_task','suggest_solution','generate_variant','generate_replacement_image'];
const PROVIDERS=['openai','anthropic'];
const text=(value,max=12000)=>String(value??'').replace(/\u0000/g,'').trim().slice(0,max);
const arr=value=>Array.isArray(value)?value:[];
function taskText(unit={}){const payload=unit.payload||{},blocks=arr(payload.blocks).map(x=>x?.text).filter(Boolean),tasks=arr(payload.tasks).map(x=>typeof x==='string'?x:JSON.stringify(x));return text([payload.instruction,payload.prompt,payload.sourceText,payload.text,...blocks,...tasks].filter(Boolean).join('\n'),12000)}
function imageData(unit={}){const candidates=[unit.payload?.imagePreview,unit.record?.content?.previewImage,unit.record?.content?.imagePreview];return candidates.find(x=>/^data:image\/(?:png|jpeg|webp);base64,/i.test(String(x||''))&&String(x).length<=2100000)||null}
function buildRequest(unit={},options={}){const action=ACTIONS.includes(options.action)?options.action:'analyze_task',provider=PROVIDERS.includes(options.provider)?options.provider:'openai',includeImage=!!options.includeImage&&action!=='generate_replacement_image',image=includeImage?imageData(unit):null;return{action,provider,purpose:text(options.purpose||labels(action).purpose,240),task:{id:text(unit.id,240),title:text(unit.title,300),grade:Number(unit.grade)||null,unit:text(unit.unit,80)||null,topic:text(unit.topic,240),type:text(unit.type,80),taskType:text(unit.payload?.taskType,100),instruction:text(unit.payload?.instruction||unit.payload?.prompt,2000),content:taskText(unit),source:{fileName:text(unit.source?.fileName,300),pages:arr(unit.source?.pages).map(Number).filter(Number.isFinite).slice(0,30)}},image:image?{dataUrl:image,description:'Lokaler Aufgabenausschnitt; nur für diese ausdrücklich bestätigte Anfrage.'}:null}}
function labels(action){return({analyze_task:{title:'Aufgabe genauer analysieren',purpose:'Fachliche Struktur, Titel, Thema und Aufgabentyp als Vorschlag erkennen.'},suggest_solution:{title:'Lösung vorschlagen',purpose:'Eine überprüfbare Musterlösung und Warnungen als Vorschlag erzeugen.'},generate_variant:{title:'Neue Variante erzeugen',purpose:'Eine neue, fachlich vergleichbare Aufgabenvariante als ungeprüften Entwurf erzeugen.'},generate_replacement_image:{title:'Neues Bild erzeugen',purpose:'Ein neues, getrennt gekennzeichnetes Unterrichtsbild auf Grundlage des Aufgabeninhalts erzeugen.'}})[action]||{title:'KI-Unterstützung',purpose:'Einen gekennzeichneten Vorschlag erzeugen.'}}
function proposalPatch(result={},request={}){const now=new Date().toISOString(),base={action:request.action,provider:result.provider||request.provider,model:result.model||'',createdAt:now,reviewed:false,externalProcessing:true,proposal:result.proposal||null,warnings:arr(result.warnings),usage:result.usage||null};if(request.action==='generate_replacement_image'&&result.image?.dataUrl)return{generatedMedia:{id:`generated-${Date.now().toString(36)}`,kind:'image',dataUrl:result.image.dataUrl,mimeType:result.image.mimeType||'image/webp',prompt:text(result.image.prompt,2000),provider:base.provider,model:base.model,generatedAt:now,generated:true,reviewed:false,sourceTaskId:request.task?.id||null,rightsNote:'KI-generiertes Bild; getrennt von der Originalquelle gespeichert.'}};return{aiProposal:base}}
return{ACTIONS,PROVIDERS,text,taskText,imageData,buildRequest,labels,proposalPatch};
});
