(()=>{'use strict';
const TOOLS=new URL('./',document.currentScript.src);
const K='kathleenGamificationV3',OLD='kathleenGamificationV2',FLAG='kathleenGamificationPreviewV1',SEC='gamification-v3',XP=250;
const LEVELS=['Funke','Entdecker','Abenteurer','Quiz-Profi','Wissensjäger','Kisten-Champion','Quest-Meister','Legende'];
const ACTIONS={quiz_correct:{label:'Quiz richtig',xp:10,icon:'🧠'},participation:{label:'Mitarbeit',xp:15,icon:'🙋'},challenge:{label:'Challenge',xp:25,icon:'⚡'},learning_game:{label:'Lernspiel',xp:20,icon:'🎮'},teamwork:{label:'Teamwork',xp:15,icon:'🤝'},bonus:{label:'Bonus',xp:10,icon:'✨'}};
const BADGES=[['first','✨','Erster Funke',x=>x.xp>=1],['100','🌟','100 XP Club',x=>x.xp>=100],['l3','🚀','Level 3',x=>x.level>=3],['s3','🔥','3er Streak',x=>x.streak>=3],['s5','💫','5er Streak',x=>x.streak>=5],['500','💎','Diamantwissen',x=>x.xp>=500,true],['l5','👑','Kisten-Champion',x=>x.level>=5,true],['secret','🕵️','Geheimnis gelüftet',x=>(x.events||[]).filter(e=>e.type==='xp').length>=7,true,true]];
const MISSIONS=[{id:'p3',icon:'🙋',title:'Melde-Meister',action:'participation',target:3,reward:30},{id:'q3',icon:'🧠',title:'Quiz-Spürnase',action:'quiz_correct',target:3,reward:35},{id:'t2',icon:'🤝',title:'Teamplayer',action:'teamwork',target:2,reward:30}];
const POWERS={boost:{icon:'⚡',title:'XP Boost'},shield:{icon:'🛡️',title:'Combo Shield'},key:{icon:'🗝️',title:'Mystery Key'}};
const dflt=()=>({version:3,activeClassId:'',classes:{},settings:{sound:false,haptics:true,betaSafe:true},updatedAt:new Date().toISOString()});
const cd=(id,n='')=>({id,name:n,classXp:0,level:1,combo:0,streak:0,students:{},teams:[],weekly:{title:'Gemeinsam 500 XP sammeln',target:500,progress:0,reward:100,week:weekKey()},boss:{title:'Boss Challenge',target:10,progress:0,active:false,reward:150},events:[]});
const sd=(id,n='')=>({id,name:n,xp:0,level:1,streak:0,lastLesson:'',badges:[],missions:{},powerups:[],rewards:[],events:[]});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const norm=s=>String(s||'').trim().toLocaleLowerCase('de-DE').normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function sid(cid,name){return cid+':'+norm(name)}
function lvl(x){return Math.max(1,Math.floor(Math.max(0,x)/XP)+1)} function lname(l){return LEVELS[Math.min(LEVELS.length-1,Math.max(0,l-1))]}
function weekKey(){const d=new Date(),x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return x.getUTCFullYear()+'-W'+String(Math.ceil((((x-y)/86400000)+1)/7)).padStart(2,'0')}
function load(){try{let s=JSON.parse(localStorage.getItem(K)||'null');if(s)return Object.assign(dflt(),s);let o=JSON.parse(localStorage.getItem(OLD)||'null');if(o){o.version=3;localStorage.setItem(K,JSON.stringify(o));return Object.assign(dflt(),o)}}catch(e){}return dflt()}
let timer=0;function save(s){s.updatedAt=new Date().toISOString();localStorage.setItem(K,JSON.stringify(s));clearTimeout(timer);timer=setTimeout(()=>secureSave(s),250);window.dispatchEvent(new CustomEvent('kathleen:gamification',{detail:s}));return s}
async function secureSave(s){try{if(window.KathleenClassLists?.isUnlocked?.())await window.KathleenClassLists.secureSet(SEC,s)}catch(e){}}
async function restore(){try{if(!window.KathleenClassLists?.isUnlocked?.())return false;const remote=await window.KathleenClassLists.secureGet(SEC,null),local=load();if(remote?.version===3&&(!localStorage.getItem(K)||new Date(remote.updatedAt||0)>new Date(local.updatedAt||0)))localStorage.setItem(K,JSON.stringify(remote));else if(localStorage.getItem(K)&&local.version===3)await window.KathleenClassLists.secureSet(SEC,local);return true}catch(e){return false}}
function visible(){return new URLSearchParams(location.search).get('gamification')==='preview'||sessionStorage.getItem(FLAG)==='1'}
function roster(){try{return window.KathleenClassLists?.load?.()||[]}catch(e){return[]}} function activeRoster(){const g=window.KathleenClassLists?.getGlobalClass?.();if(!g)return null;return roster().find(x=>x.id===g.id)||null}
function ensure(s,r=activeRoster()){if(!r)return null;let c=s.classes[r.id]||(s.classes[r.id]=cd(r.id,r.name));c.name=r.name;c.weekly=c.weekly||cd(r.id).weekly;c.boss=c.boss||cd(r.id).boss;c.teams=c.teams||[];c.students=c.students||{};c.events=c.events||[];const old=Object.values(c.students),next={};(r.students||[]).forEach(name=>{const id=sid(r.id,name),prev=c.students[id]||old.find(x=>norm(x.name)===norm(name));next[id]=Object.assign(sd(id,name),prev||{},{id,name});next[id].level=lvl(next[id].xp)});c.students=next;c.level=lvl(c.classXp);if(c.weekly.week!==weekKey())c.weekly=cd(r.id).weekly;s.activeClassId=r.id;return c}
function current(){const s=load();return ensure(s)}
function activate(){const s=load(),before=JSON.stringify(s),c=ensure(s);if(c&&JSON.stringify(s)!==before)save(s);return c}
function remember(c){const {undoHistory,...before}=c;c.undoHistory=[...(undoHistory||[]),JSON.parse(JSON.stringify(before))].slice(-20)}
function changed(c){delete c.undoHistory}
function fx(type,text){try{const e=document.createElement('div');e.className='kg-toast '+type;e.textContent=text;document.body.appendChild(e);requestAnimationFrame(()=>e.classList.add('on'));setTimeout(()=>e.remove(),1900);const s=load().settings||{};if(s.haptics!==false&&navigator.vibrate)navigator.vibrate(type==='level'?[40,40,70]:20);if(s.sound){const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=type==='level'?720:520;g.gain.value=.035;o.start();o.stop(a.currentTime+.08)}}catch(e){}}
function lessonToken(){return window.KathleenLessonMode?.get?.()?.id||new Date().toISOString().slice(0,10)}
function streak(st){const t=lessonToken();if(st.lastLesson===t)return;st.streak=Number(st.streak||0)+1;st.lastLesson=t}
function badges(st){const fresh=[];BADGES.forEach(([id,icon,title,test,rare,hidden])=>{if(test(st)&&!st.badges.some(x=>x.id===id)){const b={id,icon,title,rare:!!rare,hidden:!!hidden,at:new Date().toISOString()};st.badges.push(b);fresh.push(b)}});return fresh}
function mission(st,a){const done=[];MISSIONS.filter(m=>m.action===a).forEach(m=>{let x=st.missions[m.id]||(st.missions[m.id]={progress:0,done:false});if(!x.done&&++x.progress>=m.target){x.progress=m.target;x.done=true;st.xp+=m.reward;done.push(m)}});return done}
function addXP({amount,action='bonus',reason='Unterricht',studentId='',classId=''}={}){const s=load(),c=ensure(s);if(!c||(classId&&c.id!==classId)||(studentId&&!c.students[studentId]))return s;let n=Number(amount??ACTIONS[action]?.xp);if(!Number.isFinite(n)||n<=0)return s;remember(c);c.classXp+=n;c.combo++;c.weekly.progress+=n;if(c.boss.active&&['quiz_correct','learning_game','challenge'].includes(action))c.boss.progress=Math.min(c.boss.target,c.boss.progress+1);const ev={type:'xp',action,amount:n,reason,studentId,at:new Date().toISOString()};c.events.push(ev);if(studentId){const st=c.students[studentId],old=st.level;if(st.powerups.includes('boost')){n+=10;st.powerups=st.powerups.filter(x=>x!=='boost')}st.xp+=n;streak(st);st.events.push({...ev,amount:n});const md=mission(st,action);st.level=lvl(st.xp);const bd=badges(st);if(md.length)fx('badge',md[0].icon+' Mission geschafft · +'+md[0].reward+' XP');else if(st.level>old)fx('level','Level '+st.level+' · '+lname(st.level));else if(bd.length)fx('badge',bd[0].icon+' '+bd[0].title);else fx('xp','+'+n+' XP')}else fx('xp','+'+n+' Klassen-XP');checkGoals(c);c.level=lvl(c.classXp);return save(s)}
function checkGoals(c){if(c.weekly.progress>=c.weekly.target&&!c.weekly.done){c.weekly.done=true;c.classXp+=c.weekly.reward;fx('level','🏆 Wochen-Challenge geschafft · +'+c.weekly.reward+' Klassen-XP')}if(c.boss.active&&c.boss.progress>=c.boss.target&&!c.boss.done){c.boss.done=true;c.boss.active=false;c.classXp+=c.boss.reward;fx('level','👾 Boss besiegt · +'+c.boss.reward+' Klassen-XP')}}
function action(a,id='',r=''){if(!ACTIONS[a])return load();return addXP({amount:ACTIONS[a]?.xp||0,action:a,studentId:id,reason:r||ACTIONS[a]?.label})}
function resetCombo(){const s=load(),c=ensure(s);if(c){changed(c);const st=Object.values(c.students).find(x=>x.powerups.includes('shield'));if(st){st.powerups=st.powerups.filter(x=>x!=='shield');fx('badge','🛡️ Combo geschützt')}else c.combo=0}return save(s)}
function mystery(id){const s=load(),c=ensure(s),st=c?.students[id];if(!st||st.level<3)return;changed(c);const pool=[['xp',25,'✨ +25 XP'],['power','boost','⚡ XP Boost'],['power','shield','🛡️ Combo Shield'],['voucher',1,'🎟️ Homework Voucher']];const p=pool[Math.floor(Math.random()*pool.length)];if(p[0]==='xp'){st.xp+=p[1];st.level=lvl(st.xp)}if(p[0]==='power'&&!st.powerups.includes(p[1]))st.powerups.push(p[1]);if(p[0]==='voucher')st.rewards.push({type:'homework-voucher',status:'claimable',at:new Date().toISOString()});save(s);fx('level','🎁 '+p[2]);render();return p}
function boss(on=true){const s=load(),c=ensure(s);if(c){changed(c);c.boss={title:'Boss Challenge',target:10,progress:0,active:on,done:false,reward:150};save(s);render()}return c?.boss}
function teams(count=4){const s=load(),c=ensure(s);if(!c)return[];changed(c);const arr=Object.values(c.students),ts=Array.from({length:Math.max(2,Math.min(6,count))},(_,i)=>({id:'t'+(i+1),name:'Team '+(i+1),xp:0,members:[]}));arr.forEach((st,i)=>ts[i%ts.length].members.push(st.id));c.teams=ts;save(s);render();return ts}
function adjust(id,n){const s=load(),c=ensure(s),st=c?.students[id];if(!st||!Number.isFinite(Number(n)))return;changed(c);st.xp=Math.max(0,st.xp+Number(n||0));st.level=lvl(st.xp);save(s);render()}
function backup(){const s=load(),blob={kind:'KathleenQuestBackup',createdAt:new Date().toISOString(),state:s};localStorage.setItem('kathleenGamificationBackupV1',JSON.stringify(blob));return blob}
function undo(){const s=load(),c=ensure(s);if(!c?.undoHistory?.length)return false;const history=c.undoHistory,previous=history.pop();s.classes[c.id]={...previous,undoHistory:history};ensure(s);save(s);render();fx('xp','↩ Letzte XP-Aktion rückgängig');return true}
function resetBeta(){backup();const s=load(),r=activeRoster(),fresh=dflt();if(r)ensure(fresh,r);save(fresh);render();return true}
function voucher(st,c){const u=new URL('homework-vouchers/',TOOLS);u.searchParams.set('gamification','1');u.searchParams.set('source','Gamification');u.searchParams.set('student',st.name);u.searchParams.set('class',c.name);u.searchParams.set('reason','Quest Mode Belohnung');location.href=u}
function settings(k,v){const s=load();s.settings=s.settings||{};s.settings[k]=v;return save(s)}
function css(){if(document.getElementById('kg3'))return;const x=document.createElement('style');x.id='kg3';x.textContent=`.kg-launch{position:fixed;right:18px;bottom:18px;z-index:24500;border:1px solid #eadde9;border-radius:999px;padding:10px 14px;background:#fff;color:#654e68;font:950 10px Inter;box-shadow:0 14px 40px #74507029}.kg-panel{position:fixed;inset:0;z-index:24600;display:none;place-items:center;padding:16px;background:#46304847;backdrop-filter:blur(10px)}.kg-panel.show{display:grid}.kg-card{width:min(1180px,97vw);max-height:94vh;overflow:auto;padding:22px;border-radius:28px;background:radial-gradient(circle at 90% 0,#eee8ff,transparent 28%),radial-gradient(circle at 0 0,#ffe2ef,transparent 30%),#fffafd;color:#503d51}.kg-head,.kg-row,.kg-top{display:flex;justify-content:space-between;gap:10px;align-items:center}.kg-head h2{margin:4px 0;font-size:31px}.kg-head small{color:#987f96}.kg-btn{border:1px solid #eadde9;border-radius:11px;padding:9px 10px;background:#fff;color:#654e68;font-weight:900;cursor:pointer}.kg-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:12px}.kg-box{border:1px solid #eadde9;border-radius:18px;padding:14px;background:#ffffffd9}.kg-box h3{margin:0 0 8px;font-size:12px}.kg-big{font-size:28px;font-weight:1000}.kg-bar{height:9px;background:#f0e7ef;border-radius:99px;overflow:hidden;margin:8px 0}.kg-bar i{display:block;height:100%;background:linear-gradient(90deg,#efa5c7,#b9a6e8)}.kg-students{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.kg-player{border:1px solid #eadde9;border-radius:15px;padding:11px;background:#fff}.kg-player small{display:block;color:#8d788f;font-size:9px}.kg-tags{display:flex;flex-wrap:wrap;gap:4px;margin-top:6px}.kg-tags span{font-size:8px;padding:4px 6px;border:1px solid #e8def7;border-radius:999px;background:#f8f3ff}.kg-actions{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}.kg-actions button{font-size:8px}.kg-toast{position:fixed;z-index:27000;left:50%;top:18%;transform:translate(-50%,-12px);opacity:0;transition:.2s;padding:13px 18px;border-radius:999px;background:#fff;box-shadow:0 18px 55px #52375438;color:#654e68;font:950 13px Inter}.kg-toast.on{opacity:1;transform:translate(-50%,0)}.kg-toast.level{background:linear-gradient(135deg,#ffe2ef,#eee8ff)}@media(max-width:760px){.kg-panel{align-items:end;padding:0}.kg-card{width:100%;border-radius:25px 25px 0 0;padding:16px 12px calc(18px + env(safe-area-inset-bottom))}.kg-grid,.kg-students{grid-template-columns:1fr}.kg-launch{bottom:calc(76px + env(safe-area-inset-bottom));right:12px}}`;document.head.appendChild(x)}
function render(){document.getElementById('kgLaunch')?.remove();document.getElementById('kgPanel')?.remove();if(!visible()||/\/(quest-mode|gamification-beamer|gamification-student)\//.test(location.pathname)||document.getElementById('questBetaCard'))return;css();const b=document.createElement('a');b.id='kgLaunch';b.className='kg-launch';b.textContent='✧ Quest Mode';b.href=new URL('quest-mode/',TOOLS);document.body.appendChild(b)}
function studentView(studentId){const s=load(),c=ensure(s),st=c?.students[studentId];if(!st)return null;return {className:c.name,student:{name:st.name,xp:st.xp,level:st.level,levelName:lname(st.level),streak:st.streak,badges:st.badges,missions:st.missions,powerups:st.powerups},classProgress:{xp:c.classXp,level:c.level,weekly:c.weekly,boss:c.boss}}}
function game(e){if(!visible())return;const d=e.detail||{};if(d.source==='kalter-krieg'&&d.type==='correct')action('learning_game');if(d.source==='kalter-krieg'&&d.type==='game-finished')addXP({amount:Math.max(25,Math.min(100,Math.round((d.score||0)/50))),action:'challenge',reason:'Kalter Krieg Abschluss'});if(d.source==='english-world-quiz'&&d.type==='correct')action('quiz_correct');if(d.source==='english-world-quiz'&&d.type==='wrong')resetCombo();if(d.source==='live-poll'&&d.type==='poll-finished')addXP({amount:Math.min(40,10+(d.responses||0)),action:'participation',reason:'Live Poll'});if(d.source==='escape-room'&&d.type==='game-finished')addXP({amount:100,action:'challenge',reason:'Escape Room Victory'})}
window.addEventListener('kathleen:game-action',game);window.addEventListener('kathleen:globalclass',render);window.addEventListener('kathleen:classlists',render);window.addEventListener('kathleen:classlists-unlocked',async()=>{await restore();render()});window.addEventListener('kathleen:lessonevent',e=>{if(e.detail?.type==='lesson_end'){const s=load(),c=ensure(s);if(c){changed(c);c.streak++;save(s)}}});
window.KathleenGamification={load,save,restore,current,activate,backup,undo,resetBeta,visible,preview:on=>{on?sessionStorage.setItem(FLAG,'1'):sessionStorage.removeItem(FLAG);render()},render,addXP,action,resetCombo,mystery,boss,teams,adjust,studentView,settings,actions:ACTIONS,missions:MISSIONS,voucher,key:K};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render,{once:true});else render();
})();
