(()=>{'use strict';
const KEY='kathleenGamificationV1', FLAG='kathleenGamificationPreviewV1';
const palette={pink:'#efa5c7',pinkSoft:'#ffe2ef',lilac:'#b9a6e8',lilacSoft:'#eee8ff',mint:'#bee5d7',peach:'#ffd3b7',ink:'#503d51',muted:'#8d788f'};
const defaults=()=>({version:1,enabled:false,classId:'',className:'',xp:0,level:1,combo:0,streak:0,teams:[],achievements:[],events:[],updatedAt:new Date().toISOString()});
function load(){try{return {...defaults(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(_){return defaults()}}
function save(s){s.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent('kathleen:gamification',{detail:s}));return s}
function visible(){const p=new URLSearchParams(location.search);return p.get('gamification')==='preview'||sessionStorage.getItem(FLAG)==='1'}
function preview(on=true){on?sessionStorage.setItem(FLAG,'1'):sessionStorage.removeItem(FLAG);render();return on}
function addXP(amount,reason='Unterricht'){const s=load(),n=Math.max(0,Number(amount)||0);s.xp+=n;s.level=Math.max(1,Math.floor(s.xp/250)+1);s.combo+=1;s.events.push({type:'xp',amount:n,reason,at:new Date().toISOString()});s.events=s.events.slice(-300);return save(s)}
function resetCombo(){const s=load();s.combo=0;return save(s)}
function award(id,title){const s=load();if(!s.achievements.some(a=>a.id===id))s.achievements.push({id,title,at:new Date().toISOString()});return save(s)}
function css(){if(document.getElementById('kgStyle'))return;const x=document.createElement('style');x.id='kgStyle';x.textContent=`
.kg-launch{position:fixed;right:18px;bottom:18px;z-index:24500;border:1px solid #eadde9;border-radius:999px;padding:10px 14px;background:rgba(255,255,255,.94);box-shadow:0 14px 40px rgba(116,76,112,.16);color:#654e68;font:950 10px Inter,Arial}.kg-panel{position:fixed;inset:0;z-index:24600;display:none;place-items:center;padding:18px;background:rgba(70,48,72,.28);backdrop-filter:blur(10px)}.kg-panel.show{display:grid}.kg-card{width:min(980px,96vw);max-height:92vh;overflow:auto;border:1px solid #eadde9;border-radius:28px;padding:22px;background:radial-gradient(circle at 92% 3%,#eee8ff 0,transparent 28%),radial-gradient(circle at 4% 5%,#ffe2ef 0,transparent 30%),#fffafd;box-shadow:0 32px 100px rgba(82,55,84,.25);color:#503d51}.kg-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.kg-kicker{font:950 9px Inter;letter-spacing:.14em;color:#9b7b96}.kg-head h2{margin:5px 0 4px;font-size:32px;letter-spacing:-.04em}.kg-head p{margin:0;color:#8d788f;font-size:11px}.kg-close{border:1px solid #eadde9;background:#fff;border-radius:12px;padding:9px 11px;color:#684f6b;font-weight:950}.kg-hero{display:grid;grid-template-columns:1.25fr .75fr;gap:12px;margin-top:18px}.kg-xp,.kg-combo{border:1px solid #eadde9;border-radius:22px;padding:18px;background:rgba(255,255,255,.84)}.kg-xp-top{display:flex;justify-content:space-between;font-weight:950}.kg-bar{height:14px;margin:13px 0 7px;border-radius:999px;background:#f0e7ef;overflow:hidden}.kg-fill{height:100%;border-radius:inherit;background:linear-gradient(90deg,#efa5c7,#b9a6e8);transition:.3s}.kg-combo{display:grid;place-items:center;text-align:center;background:linear-gradient(145deg,#fff,#fff1f7)}.kg-combo b{font-size:42px}.kg-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:12px}.kg-tile{border:1px solid #eadde9;border-radius:18px;padding:15px;background:#fff;min-height:118px}.kg-tile i{font-style:normal;font-size:25px}.kg-tile b{display:block;margin:9px 0 4px}.kg-tile span{font-size:9px;line-height:1.45;color:#8d788f}.kg-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:14px}.kg-actions button{border:1px solid #eadde9;border-radius:11px;padding:10px 12px;background:#fff;color:#654e68;font-weight:950}.kg-actions .primary{border:0;color:#fff;background:linear-gradient(135deg,#d58eb4,#a98bdd)}.kg-hidden-note{margin-top:13px;font-size:9px;color:#a28da1}@media(max-width:700px){.kg-launch{right:12px;bottom:calc(76px + env(safe-area-inset-bottom))}.kg-panel{align-items:end;padding:0}.kg-card{width:100%;border-radius:26px 26px 0 0;padding:18px 14px calc(18px + env(safe-area-inset-bottom))}.kg-hero,.kg-grid{grid-template-columns:1fr}.kg-grid{grid-template-columns:1fr 1fr}.kg-head h2{font-size:27px}}`;document.head.appendChild(x)}
function render(){document.getElementById('kgLaunch')?.remove();document.getElementById('kgPanel')?.remove();if(!visible())return;css();const s=load(),into=s.xp%250,pct=Math.round(into/250*100);const b=document.createElement('button');b.id='kgLaunch';b.className='kg-launch';b.textContent='✨ Quest Mode';document.body.appendChild(b);const p=document.createElement('div');p.id='kgPanel';p.className='kg-panel';p.innerHTML=`<section class="kg-card"><header class="kg-head"><div><div class="kg-kicker">KATHLEENS MAGISCHE KISTE · PREVIEW</div><h2>Quest Mode</h2><p>Gamification für die Klasse. Noch nicht im normalen Kathleen-Interface sichtbar.</p></div><button class="kg-close">Schließen</button></header><div class="kg-hero"><div class="kg-xp"><div class="kg-xp-top"><span>Klassen-XP</span><span>Level ${s.level}</span></div><div class="kg-bar"><div class="kg-fill" style="width:${pct}%"></div></div><small>${into} / 250 XP bis Level ${s.level+1}</small></div><div class="kg-combo"><span>🔥 COMBO</span><b>${s.combo}×</b><small>Streak ${s.streak}</small></div></div><div class="kg-grid"><div class="kg-tile"><i>🎁</i><b>Mystery Box</b><span>Belohnung nach gemeinsam erreichten Meilensteinen.</span></div><div class="kg-tile"><i>👾</i><b>Boss Battle</b><span>Gemeinsames Finale mit Klassenfortschritt.</span></div><div class="kg-tile"><i>⚔️</i><b>Team Battles</b><span>Teams sammeln Punkte ohne Schüler-Ranking.</span></div><div class="kg-tile"><i>🕵️</i><b>Secret Mission</b><span>Verdeckte Zusatzmission für die Stunde.</span></div><div class="kg-tile"><i>⚡</i><b>Power-ups</b><span>Kleine Unterrichtsvorteile als freischaltbare Karten.</span></div><div class="kg-tile"><i>🏅</i><b>Achievements</b><span>Klassen-Erfolge für Zusammenarbeit und Streaks.</span></div></div><div class="kg-actions"><button class="primary" data-xp="25">+25 XP</button><button data-xp="50">+50 XP</button><button data-reset>Combo zurücksetzen</button></div><div class="kg-hidden-note">Preview-Schalter: ?gamification=preview · wird nicht in Navigation, Tools oder Service-Worker verlinkt.</div></section>`;document.body.appendChild(p);b.onclick=()=>p.classList.add('show');p.querySelector('.kg-close').onclick=()=>p.classList.remove('show');p.onclick=e=>{if(e.target===p)p.classList.remove('show')};p.querySelectorAll('[data-xp]').forEach(x=>x.onclick=()=>{addXP(x.dataset.xp,'Preview');render();document.getElementById('kgPanel')?.classList.add('show')});p.querySelector('[data-reset]').onclick=()=>{resetCombo();render();document.getElementById('kgPanel')?.classList.add('show')}}
window.KathleenGamification={load,save,preview,visible,addXP,resetCombo,award,render,key:KEY};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render,{once:true});else render();
})();