(()=>{'use strict';
if(window.KathleenHelp)return;const Registry=window.KathleenHelpRegistry?.create(window.KathleenHelpCatalog),SEEN='kathleenHelpSeenV1',NEVER='kathleenHelpNeverV1',LAST='kathleenHelpLastV1';if(!Registry)return;
let panel,backdrop,body,search,lastFocus,tour=null;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),seen=()=>{try{return JSON.parse(localStorage.getItem(SEEN)||'{}')}catch{return{}}},saveSeen=x=>localStorage.setItem(SEEN,JSON.stringify(x));
function current(){return Registry.context(location.pathname,location.hash)[0]||Registry.get('getting-started')}
function setDeepLink(id){const u=new URL(location.href);id?u.searchParams.set('help',id):u.searchParams.delete('help');history.replaceState(history.state,'',u)}
function ensure(){if(panel)return;backdrop=document.createElement('div');backdrop.className='k-help-backdrop';backdrop.onclick=close;panel=document.createElement('aside');panel.className='k-help-panel';panel.id='kHelpCenter';panel.setAttribute('role','dialog');panel.setAttribute('aria-label','Hilfe');panel.innerHTML='<header class="k-help-head"><div class="k-help-head-row"><div><small>HILFE</small><h2>Wobei kann ich dir helfen?</h2></div><button class="k-help-close" aria-label="Hilfe schließen">×</button></div><label class="k-help-search"><span class="sr-only">Hilfe durchsuchen</span><input type="search" placeholder="Funktion oder Problem suchen …" aria-label="Hilfe durchsuchen"></label></header><div class="k-help-body" tabindex="-1"></div>';document.body.append(backdrop,panel);body=panel.querySelector('.k-help-body');search=panel.querySelector('input');panel.querySelector('.k-help-close').onclick=close;search.oninput=()=>renderSearch(search.value);panel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();close()}if(e.key==='Tab')trap(e)})}
function trap(e){const items=[...panel.querySelectorAll('button,input,a,[tabindex]:not([tabindex="-1"])')].filter(x=>!x.disabled),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}
function cards(items){return items.map(x=>`<button class="k-help-card" data-help-id="${esc(x.id)}"><b>${esc(x.title)}</b><p>${esc(x.shortDescription)}</p></button>`).join('')}
function bind(root=body){root.querySelectorAll('[data-help-id]').forEach(x=>x.onclick=()=>open(x.dataset.helpId));root.querySelector('[data-help-tour]')?.addEventListener('click',e=>startGuide(e.currentTarget.dataset.helpTour))}
function renderHome(){const ctx=Registry.context(location.pathname,location.hash),entry=ctx[0]||Registry.get('getting-started'),categories=['Erste Schritte','Unterricht','Klassen & Organisation','Inhalte','Leistungsnachweise','Spiele','Probleme lösen'];body.innerHTML=`<section class="k-help-context"><small>AKTUELLES TOOL</small><h3>${esc(entry.tool)}</h3><p>${esc(entry.shortDescription)}</p><div class="k-help-actions"><button class="k-help-btn" data-help-id="${esc(entry.id)}">Hilfe öffnen</button>${entry.guide?`<button class="k-help-btn soft" data-help-tour="${esc(entry.id)}">Schritt für Schritt</button>`:''}</div></section><h3 class="k-help-section-title">SCHNELLZUGRIFF</h3><div class="k-help-grid">${cards([Registry.get('getting-started'),Registry.get('assessment-create'),Registry.get('material-import'),Registry.get('classes'),Registry.get('connection-troubleshooting'),Registry.get('quick-games')].filter(Boolean))}</div><h3 class="k-help-section-title">ALLE BEREICHE</h3><div class="k-help-results">${categories.map(cat=>`<button class="k-help-result" data-help-category="${esc(cat)}"><b>${esc(cat)}</b><small>${Registry.entries.filter(x=>x.category===cat).length} Artikel</small></button>`).join('')}</div>`;body.querySelectorAll('[data-help-category]').forEach(b=>b.onclick=()=>renderCategory(b.dataset.helpCategory));bind()}
function renderCategory(category){const items=Registry.entries.filter(x=>x.category===category);body.innerHTML=`<button class="k-help-back">← Hilfe-Start</button><h2>${esc(category)}</h2><div class="k-help-results">${items.map(x=>`<button class="k-help-result" data-help-id="${esc(x.id)}"><small>${esc(x.tool)}</small><b>${esc(x.title)}</b><span>${esc(x.shortDescription)}</span></button>`).join('')}</div>`;body.querySelector('.k-help-back').onclick=renderHome;bind()}
function renderSearch(q){if(!q.trim()){renderHome();return}const items=Registry.search(q);body.innerHTML=`<h2>Suchergebnisse</h2><p>${items.length} Treffer für „${esc(q)}“</p><div class="k-help-results">${items.slice(0,30).map(x=>`<button class="k-help-result" data-help-id="${esc(x.id)}"><small>${esc(x.tool)} · ${esc(x.category)}</small><b>${esc(x.title)}</b><span>${esc(x.shortDescription)}</span></button>`).join('')||'<p>Kein passender Artikel. Versuche einen allgemeineren Begriff.</p>'}</div>`;bind()}
function renderArticle(entry){localStorage.setItem(LAST,entry.id);const related=(entry.relatedArticles||[]).map(id=>Registry.get(id)).filter(Boolean);body.innerHTML=`<article class="k-help-article"><button class="k-help-back">← Zurück</button><small>${esc(entry.tool)} · ${esc(entry.category)}</small><h1>${esc(entry.title)}</h1><p class="lead">${esc(entry.shortDescription)}</p><p>${esc(entry.content)}</p>${entry.steps?.length?`<h3>So gehst du vor</h3><ol class="k-help-steps">${entry.steps.map(x=>`<li>${esc(x.text)}</li>`).join('')}</ol>`:''}${entry.tips?.length?entry.tips.map(x=>`<div class="k-help-tip"><b>Tipp</b><br>${esc(x)}</div>`).join(''):''}${entry.troubleshooting?.length?`<h3>Problem lösen</h3>${entry.troubleshooting.map(x=>`<div class="k-help-tip"><b>${esc(x.problem)}</b><p><b>Mögliche Ursache:</b> ${esc(x.cause)}</p><p><b>Lösung:</b> ${esc(x.solution)}</p></div>`).join('')}`:''}${entry.guide?`<div class="k-help-actions"><button class="k-help-btn" data-help-tour="${esc(entry.id)}">Schritt-für-Schritt starten</button></div>`:''}${related.length?`<h3>Passende Artikel</h3><div class="k-help-results">${related.map(x=>`<button class="k-help-result" data-help-id="${esc(x.id)}"><b>${esc(x.title)}</b></button>`).join('')}</div>`:''}</article>`;body.querySelector('.k-help-back').onclick=renderHome;bind()}
function open(id){ensure();lastFocus=document.activeElement;const entry=Registry.get(id);search.value='';entry?renderArticle(entry):renderHome();panel.classList.add('open');backdrop.classList.add('open');document.documentElement.classList.add('k-help-visible');panel.querySelector('.k-help-close').focus();setDeepLink(entry?.id||'')}
function close(){if(!panel)return;panel.classList.remove('open');backdrop.classList.remove('open');document.documentElement.classList.remove('k-help-visible');setDeepLink('');lastFocus?.focus?.()}
function guideStep(index){if(!tour)return;document.querySelector('.k-help-tour-target')?.classList.remove('k-help-tour-target');document.querySelector('.k-help-tour')?.remove();const steps=tour.entry.steps||[];if(index>=steps.length){finishGuide();return}if(index<0)index=0;let step=steps[index],target=step.target?document.querySelector(step.target):null;if(step.target&&!target){tour.index=index+1;guideStep(tour.index);return}tour.index=index;if(target){target.classList.add('k-help-tour-target');target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'})}const box=document.createElement('section');box.className='k-help-tour';box.setAttribute('role','dialog');box.setAttribute('aria-live','polite');box.innerHTML=`<small>Schritt ${index+1} von ${steps.length}</small><p>${esc(step.text)}</p><div class="k-help-tour-actions"><button class="k-help-btn soft" data-skip>Beenden</button><span><button class="k-help-btn soft" data-prev ${index?'':'disabled'}>Zurück</button> <button class="k-help-btn" data-next>${index===steps.length-1?'Fertig':'Weiter'}</button></span></div>`;document.body.append(box);if(target){const r=target.getBoundingClientRect(),w=box.offsetWidth,h=box.offsetHeight;box.style.left=Math.max(12,Math.min(innerWidth-w-12,r.left))+'px';box.style.top=(r.bottom+h+16<innerHeight?r.bottom+12:Math.max(12,r.top-h-12))+'px'}else{box.style.left='50%';box.style.top='50%';box.style.transform='translate(-50%,-50%)'}box.querySelector('[data-skip]').onclick=finishGuide;box.querySelector('[data-prev]').onclick=()=>guideStep(index-1);box.querySelector('[data-next]').onclick=()=>guideStep(index+1);box.querySelector('[data-next]').focus()}
function startGuide(id){const entry=Registry.get(id);if(!entry?.steps?.length)return;close();tour={entry,index:0};guideStep(0)}
function finishGuide(){if(!tour)return;document.querySelector('.k-help-tour-target')?.classList.remove('k-help-tour-target');document.querySelector('.k-help-tour')?.remove();const s=seen();s[tour.entry.id]=true;saveSeen(s);tour=null}
function onboarding(){const entry=current(),never=JSON.parse(localStorage.getItem(NEVER)||'{}');if(!entry?.firstUse||seen()[entry.id]||never[entry.id]||document.querySelector('.k-help-onboard'))return;const card=document.createElement('section');card.className='k-help-onboard';card.setAttribute('role','dialog');card.setAttribute('aria-label','Einführung');card.innerHTML=`<h2>Neu hier?</h2><p>Ich zeige dir kurz, wie „${esc(entry.tool)}“ funktioniert.</p><div class="k-help-actions"><button class="k-help-btn soft" data-later>Später</button><button class="k-help-btn soft" data-never>Nicht mehr anzeigen</button><button class="k-help-btn" data-show>Zeig es mir</button></div>`;document.body.append(card);card.querySelector('[data-later]').onclick=()=>card.remove();card.querySelector('[data-never]').onclick=()=>{never[entry.id]=true;localStorage.setItem(NEVER,JSON.stringify(never));card.remove()};card.querySelector('[data-show]').onclick=()=>{card.remove();entry.guide?startGuide(entry.id):open(entry.id)}}
function tooltips(){const pairs=[['.kds-present','Für den Beamer optimieren'],['.kds-sidebar-toggle','Seitenleiste ein- oder ausklappen'],['#fullBtn','Vollbild umschalten'],['.difficulty-tag','Schwierigkeit ändern']];for(const [sel,label] of pairs)document.querySelectorAll(sel).forEach(el=>{el.dataset.helpTip=label;if(!el.getAttribute('aria-label'))el.setAttribute('aria-label',label)})}
function init(){document.querySelectorAll('.kds-help-btn,[data-kds-help]').forEach(b=>b.onclick=()=>open());tooltips();const id=new URL(location.href).searchParams.get('help');if(id&&Registry.get(id))open(id);setTimeout(onboarding,900)}
window.addEventListener('kathleen:help',e=>open(e.detail?.articleId));window.KathleenHelp={init,open,close,search:q=>Registry.search(q),startGuide,registry:Registry};
})();
