(()=>{
'use strict';
const KEY='kathleenLessonModeV1',SNAP='kathleenTimetableSnapshotV1';
const pad=n=>String(n).padStart(2,'0'),mins=t=>{const[a,b]=String(t||'0:0').split(':').map(Number);return a*60+b},norm=s=>String(s||'').trim().toLowerCase();
function schedule(){try{const x=JSON.parse(localStorage.getItem(SNAP)||'null');return Array.isArray(x?.entries)?x.entries:[]}catch(e){return[]}}
function get(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){return null}}
function put(x){if(x)localStorage.setItem(KEY,JSON.stringify(x));else localStorage.removeItem(KEY);window.dispatchEvent(new CustomEvent('kathleen:lessonmode',{detail:x}));return x}
function classRef(e){let meta=[];try{meta=JSON.parse(localStorage.getItem('kathleenClassMetaV1')||'[]')}catch(_){}const hit=meta.find(x=>String(x.id)===String(e.classId))||meta.find(x=>norm(x.name)===norm(e.className));return{id:String(hit?.id||e.classId||('name:'+e.className)),name:hit?.name||e.className||''}}
function start(entry,opts={}){if(!entry)return null;const ref=classRef(entry),x={id:'lesson-'+Date.now().toString(36),lessonId:String(entry.id||''),classId:ref.id,className:ref.name,subject:entry.subject||'',room:entry.room||'',start:entry.start||'',end:entry.end||'',startedAt:new Date().toISOString(),status:'active'};put(x);try{localStorage.setItem('kathleenGlobalClassV1',JSON.stringify({id:ref.id,name:ref.name,updatedAt:new Date().toISOString()}));localStorage.setItem('kathleenGlobalClassId',ref.id);localStorage.setItem('kathleenGlobalClassName',ref.name);localStorage.setItem('kathleenActiveSubjectV1',x.subject)}catch(_){}window.KathleenI18n?.setSubject?.(x.subject);window.KathleenI18n?.apply?.();if(opts.navigate!==false)location.href=opts.route||'tools/classroom-board/';return x}
function end(){const x=get();if(x){x.status='ended';x.endedAt=new Date().toISOString();localStorage.setItem('kathleenLastLessonV1',JSON.stringify(x))}put(null)}
function currentSchedule(now=new Date()){const d=now.getDay()===0?7:now.getDay(),m=now.getHours()*60+now.getMinutes();return schedule().filter(e=>Number(e.day)===d).find(e=>mins(e.start)<=m&&mins(e.end)>m)||null}
function remaining(x){if(!x?.end)return'';const [h,m]=x.end.split(':').map(Number),now=new Date(),end=new Date(now);end.setHours(h,m,0,0);const n=Math.ceil((end-now)/60000);return n>0?n+' min':'Ende'}
function ensureBar(){if(document.getElementById('lessonModeBar'))return;const s=document.createElement('style');s.textContent='.lesson-mode-bar{position:fixed;z-index:23500;left:50%;top:max(10px,env(safe-area-inset-top));transform:translateX(-50%);display:none;align-items:center;gap:8px;max-width:calc(100vw - 24px);padding:7px 8px 7px 11px;border:1px solid #e6d7e5;border-radius:999px;background:rgba(255,255,255,.96);box-shadow:0 12px 35px rgba(73,50,76,.18);backdrop-filter:blur(12px);color:#5e4962;font:850 9px/1.1 Inter,Arial,sans-serif}.lesson-mode-bar.show{display:flex}.lesson-mode-bar b{font-size:10px;white-space:nowrap}.lesson-mode-bar span{white-space:nowrap;color:#8b778d}.lesson-mode-bar button{border:0;border-radius:999px;padding:7px 9px;background:#f4edf5;color:#684f6b;font:900 8px/1 Inter,Arial,sans-serif}.lesson-mode-bar .end{background:#fff0f3;color:#a45468}@media(max-width:650px){.lesson-mode-bar{left:10px;right:10px;top:max(7px,env(safe-area-inset-top));transform:none;overflow:auto}.lesson-mode-bar span.room{display:none}}';document.head.appendChild(s);const d=document.createElement('div');d.id='lessonModeBar';d.className='lesson-mode-bar';d.innerHTML='<b id="lessonModeTitle"></b><span class="room" id="lessonModeRoom"></span><span id="lessonModeTime"></span><button data-lm="board">✨ Board</button><button data-lm="seating">🪑</button><button class="end" data-lm="end">Beenden</button>';document.body.appendChild(d);d.querySelector('[data-lm="board"]').onclick=()=>location.href=(location.pathname.includes('/tools/')?'../classroom-board/':'tools/classroom-board/');d.querySelector('[data-lm="seating"]').onclick=()=>location.href=(location.pathname.includes('/tools/')?'../seating-plan/':'tools/seating-plan/');d.querySelector('[data-lm="end"]').onclick=()=>{if(confirm('Unterrichtsmodus beenden?')){end();render()}}}
function render(){ensureBar();const d=document.getElementById('lessonModeBar'),x=get();if(!x||x.status!=='active'){d.classList.remove('show');return}d.classList.add('show');document.getElementById('lessonModeTitle').textContent=(x.subject||'Unterricht')+' · '+(x.className||'');document.getElementById('lessonModeRoom').textContent=x.room?'📍 '+x.room:'';document.getElementById('lessonModeTime').textContent=remaining(x)}
function init(){render();setInterval(render,30000);window.addEventListener('storage',e=>{if(e.key===KEY)render()});const e=currentSchedule();const x=get();if(e&&!x&&location.pathname.endsWith('/index.html')||e&&!x&&location.pathname.endsWith('/')){/* start stays explicit */}}
window.KathleenLessonMode={get,start,end,currentSchedule,render,key:KEY};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();