(()=>{'use strict';
if(window.KathleenTeacherShell)return;
const script=document.currentScript,TOOLS=new URL('./',script?.src||location.href),HOME=new URL('../',TOOLS).toString();
const path=location.pathname.toLowerCase();
if(document.body?.dataset?.kdsNoShell!==undefined||/(\/student(?:\.html|\/)|\/present\.html|gamification-(?:student|beamer|remote))/.test(path))return;
const ICON={home:'<path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10v10h13V10M9.5 20v-6h5v6"/>',calendar:'<rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4M16 3v4M4 9h16"/>',users:'<circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M3 20c.4-4 2.5-6 6-6s5.6 2 6 6M15 15c3.5 0 5.5 1.7 6 5"/>',board:'<rect x="3" y="4" width="18" height="14" rx="2"/><path d="M8 22h8M12 18v4M7 14l3-3 2 2 5-5"/>',spark:'<path d="M12 2l1.8 5.2L19 9l-5.2 1.8L12 16l-1.8-5.2L5 9l5.2-1.8L12 2Z"/><path d="M19 16l.9 2.1L22 19l-2.1.9L19 22l-.9-2.1L16 19l2.1-.9L19 16Z"/>',eye:'<path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.5"/>',doc:'<path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h5M9 13h6M9 17h6"/>',game:'<path d="M7 9h10a5 5 0 0 1 4.7 6.7l-1 2.7a2 2 0 0 1-3.2.8L15 17H9l-2.5 2.2a2 2 0 0 1-3.2-.8l-1-2.7A5 5 0 0 1 7 9Z"/><path d="M7 12v4M5 14h4M16 13h.01M19 15h.01"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M4 12a8 8 0 0 1 .2-1.7L2.7 9.1l2-3.4 1.9.7A8 8 0 0 1 9.5 4L10 2h4l.5 2a8 8 0 0 1 2.9 2.4l1.9-.7 2 3.4-1.5 1.2A8 8 0 0 1 20 12c0 .6-.1 1.1-.2 1.7l1.5 1.2-2 3.4-1.9-.7a8 8 0 0 1-2.9 2.4L14 22h-4l-.5-2a8 8 0 0 1-2.9-2.4l-1.9.7-2-3.4 1.5-1.2A8 8 0 0 1 4 12Z"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',grid:'<rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>'};
const svg=k=>'<svg viewBox="0 0 24 24" aria-hidden="true">'+(ICON[k]||ICON.spark)+'</svg>';
const ROUTES=[['/timetable/','timetable','Stundenplan'],['/class-cockpit/','classes','Meine Klassen'],['/class-lists/','classes','Klassenlisten'],['/classroom-board/','whiteboard','Whiteboard'],['/quest-mode/','quest','Quest Mode'],['/mobile-observations/','observations','Beobachtungen'],['/homework-strikes/','material','Hausaufgaben'],['/homework-vouchers/','material','Hausaufgaben-Gutscheine'],['/live-poll/','games','Live Poll'],['/english-world-quiz/','games','Quiz & Spiele'],['/randomizer/','games','Zufall'],['/team-generator/','tools','Team Generator'],['/classroom-timer/','tools','Timer'],['/seating-plan/','classes','Sitzplan'],['/push-center/','tools','Push Center'],['/schulaufgabenrechner/','tools','Schulaufgabenrechner'],['/escape-room/','games','Escape Room'],['/teacher-command/','tools','Lehrerzentrale'],['/kalter-krieg/lehrer','material','Kalter Krieg']];
const current=ROUTES.find(r=>path.includes(r[0]))||['','tools',document.title.split('·')[0].trim()||'Werkzeug'];
function go(p=''){location.href=new URL(p,HOME).toString()}
function setLang(lang){if(window.KathleenI18n){lang==='auto'?window.KathleenI18n.auto():window.KathleenI18n.setLanguage(lang,true);return}lang==='auto'?localStorage.removeItem('kathleenUiLanguageOverrideV1'):localStorage.setItem('kathleenUiLanguageOverrideV1',lang);location.reload()}
function presentation(){if(window.KathleenPresentation){window.KathleenPresentation.isActive()?window.KathleenPresentation.exit():window.KathleenPresentation.enter();return}const s=document.createElement('script');s.src=new URL('presentation-mode.js?v=20260923-premium1',TOOLS);s.onload=()=>window.KathleenPresentation?.enter?.();document.head.appendChild(s)}
function link(key,icon,label,dest){return '<a href="'+dest+'" data-kds-key="'+key+'"'+(current[1]===key?' aria-current="page"':'')+'>'+svg(icon)+'<span>'+label+'</span></a>'}
function closeMore(){document.getElementById('kdsMore')?.remove()}
function openMore(){closeMore();const d=document.createElement('div');d.id='kdsMore';d.className='kds-more-sheet';d.innerHTML='<div class="kds-more-card"><div class="kds-more-head"><div><small>DEINE KISTE</small><h2>Weitere Werkzeuge</h2></div><button class="kds-close" data-close>×</button></div><div class="kds-more-grid">'+more('Sitzplan','seating-plan/','users')+more('Hausaufgaben','homework-strikes/','doc')+more('Gutscheine','homework-vouchers/','spark')+more('Randomizer','randomizer/','spark')+more('Team Generator','team-generator/','users')+more('Timer','classroom-timer/','clock')+more('Push Center','push-center/','spark')+more('Klassenlisten','class-lists/','users')+more('Schulaufgaben','schulaufgabenrechner/','doc')+more('Live Poll','live-poll/','grid')+more('Escape Room','escape-room/','game')+more('Lehrerzentrale','teacher-command/','settings')+'</div><div class="kds-more-section">SPRACHE</div><div class="kds-lang"><button data-lang="de">Deutsch</button><button data-lang="en">English</button><button data-lang="auto">Auto</button></div><button class="kds-present" data-present>⛶ Präsentationsmodus</button></div>';document.body.appendChild(d);d.onclick=e=>{if(e.target===d)closeMore()};d.querySelector('[data-close]').onclick=closeMore;d.querySelectorAll('[data-tool]').forEach(a=>a.onclick=e=>{e.preventDefault();go('tools/'+a.dataset.tool)});d.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>setLang(b.dataset.lang));d.querySelector('[data-present]').onclick=()=>{presentation();closeMore()}}
function more(label,dest,icon){return '<a href="'+new URL('tools/'+dest,HOME)+'" data-tool="'+dest+'">'+svg(icon)+'<span>'+label+'</span></a>'}
function inject(){if(document.querySelector('.kds-sidebar'))return;const css=document.createElement('link');css.rel='stylesheet';css.href=new URL('teacher-design-v50.css?v=20260923-premium1',TOOLS);document.head.appendChild(css);document.documentElement.classList.add('k-teacher-shell');document.body.classList.add('kds-content-offset');
 const side=document.createElement('aside');side.className='kds-sidebar';side.innerHTML='<a class="kds-brand" href="'+HOME+'"><span class="kds-brandmark">'+svg('spark')+'</span><span>Kathleens<br><strong>magische Kiste</strong></span></a><span class="kds-navlabel">MEIN UNTERRICHT</span><nav>'+link('home','home','Start',HOME)+link('timetable','calendar','Stundenplan',new URL('tools/timetable/',HOME))+link('classes','users','Meine Klassen',new URL('tools/class-cockpit/',HOME))+link('whiteboard','board','Whiteboard',new URL('tools/classroom-board/',HOME))+link('quest','spark','Quest Mode',new URL('tools/quest-mode/',HOME))+link('observations','eye','Beobachtungen',new URL('tools/mobile-observations/',HOME))+link('material','doc','Material & Aufgaben',HOME+'#library')+link('games','game','Quiz & Spiele',HOME+'#tools')+'</nav><div class="kds-sidebar-foot">'+link('manage','settings','Einstellungen',HOME+'#manage')+'<small>Gemeinsam lernen.<br>Gemeinsam wachsen.</small></div>';document.body.prepend(side);
 const top=document.createElement('header');top.className='kds-topbar';top.innerHTML='<div class="kds-crumb"><span>Meine Kiste</span><span>/</span><strong>'+current[2]+'</strong></div><div class="kds-top-actions"><label class="kds-search">'+svg('search')+'<input placeholder="In deiner Kiste suchen …"></label><span class="kds-avatar">K</span><span class="kds-teacher">Kathleen</span><button class="kds-more-btn">Mehr</button></div>';document.body.prepend(top);top.querySelector('.kds-more-btn').onclick=openMore;top.querySelector('input').onkeydown=e=>{if(e.key==='Enter'&&e.target.value.trim())go('#library')};
 const mobile=document.createElement('nav');mobile.className='kds-mobile-nav';mobile.innerHTML='<button data-home class="'+(current[1]==='home'?'active':'')+'">'+svg('home')+'<span>Start</span></button><button data-go="classroom-board/" class="'+(current[1]==='whiteboard'?'active':'')+'">'+svg('board')+'<span>Board</span></button><button data-go="class-cockpit/" class="'+(current[1]==='classes'?'active':'')+'">'+svg('users')+'<span>Klasse</span></button><button data-more>'+svg('grid')+'<span>Mehr</span></button>';document.body.appendChild(mobile);mobile.querySelector('[data-home]').onclick=()=>go();mobile.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go('tools/'+b.dataset.go));mobile.querySelector('[data-more]').onclick=openMore}
window.KathleenTeacherShell={home:()=>go(),more:openMore,presentation,setLanguage:setLang};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject,{once:true});else inject();
})();