(()=>{
'use strict';
if(window.KathleenTeacherShell)return;
const script=document.currentScript,TOOLS=new URL('./',script?.src||location.href),HOME=new URL('../',TOOLS),path=location.pathname.toLowerCase();
if(document.body?.dataset?.kdsNoShell!==undefined||/(\/student(?:\.html|\/)|\/present\.html|gamification-(?:student|beamer|remote))/.test(path))return;
const COLLAPSE='kathleenSidebarCollapsedV53',BAR_POS='kathleenSessionBarPositionV53',BAR_MIN='kathleenSessionBarMinimizedV53';
const ICON={home:'<path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10v10h13V10M9.5 20v-6h5v6"/>',calendar:'<rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4M16 3v4M4 9h16"/>',users:'<circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M3 20c.4-4 2.5-6 6-6s5.6 2 6 6M15 15c3.5 0 5.5 1.7 6 5"/>',board:'<rect x="3" y="4" width="18" height="14" rx="2"/><path d="M8 22h8M12 18v4M7 14l3-3 2 2 5-5"/>',spark:'<path d="M12 2l1.8 5.2L19 9l-5.2 1.8L12 16l-1.8-5.2L5 9l5.2-1.8L12 2Z"/><path d="M19 16l.9 2.1L22 19l-2.1.9L19 22l-.9-2.1L16 19l2.1-.9L19 16Z"/>',eye:'<path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.5"/>',doc:'<path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h5M9 13h6M9 17h6"/>',game:'<path d="M7 9h10a5 5 0 0 1 4.7 6.7l-1 2.7a2 2 0 0 1-3.2.8L15 17H9l-2.5 2.2a2 2 0 0 1-3.2-.8l-1-2.7A5 5 0 0 1 7 9Z"/><path d="M7 12v4M5 14h4M16 13h.01M19 15h.01"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M4 12a8 8 0 0 1 .2-1.7L2.7 9.1l2-3.4 1.9.7A8 8 0 0 1 9.5 4L10 2h4l.5 2a8 8 0 0 1 2.9 2.4l1.9-.7 2 3.4-1.5 1.2A8 8 0 0 1 20 12c0 .6-.1 1.1-.2 1.7l1.5 1.2-2 3.4-1.9-.7a8 8 0 0 1-2.9 2.4l-1.9.7-2-3.4 1.5-1.2A8 8 0 0 1 4 12Z"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',grid:'<rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',seat:'<path d="M7 12h10a2 2 0 0 1 2 2v3H5v-3a2 2 0 0 1 2-2Z"/><path d="M7 12V8a5 5 0 0 1 10 0v4M7 17v4M17 17v4"/>',qr:'<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><path d="M14 14h3v3h-3zM18 18h3v3h-3zM14 20h2M20 14h1"/>',chev:'<path d="m9 6 6 6-6 6"/>',minus:'<path d="M5 12h14"/>',play:'<path d="m9 7 8 5-8 5z"/>',move:'<path d="M12 2v20M2 12h20M8 6l4-4 4 4M8 18l4 4 4-4M6 8l-4 4 4 4M18 8l4 4-4 4"/>'};
const svg=k=>'<svg viewBox="0 0 24 24" aria-hidden="true">'+(ICON[k]||ICON.spark)+'</svg>';
const ROUTES=[['/timetable/','timetable','Stundenplan'],['/class-cockpit/','classes','Meine Klassen'],['/class-lists/','classes','Klassenlisten'],['/classroom-board/','whiteboard','Whiteboard'],['/quest-mode/','quest','Quest Mode'],['/mobile-observations/','observations','Beobachtungen'],['/homework-strikes/','material','Hausaufgaben'],['/homework-vouchers/','material','Hausaufgaben-Gutscheine'],['/live-poll/','games','Live Poll'],['/english-world-quiz/','games','Quiz & Spiele'],['/randomizer/','games','Zufall'],['/team-generator/','tools','Team Generator'],['/classroom-timer/','tools','Timer'],['/seating-plan/','classes','Sitzplan'],['/push-center/','tools','Push Center'],['/schulaufgabenrechner/','tools','Schulaufgabenrechner'],['/escape-room/','games','Escape Room'],['/teacher-command/','tools','Lehrerzentrale'],['/kalter-krieg/lehrer','material','Kalter Krieg']];
const atRoot=!path.includes('/tools/'),rootView=location.hash.includes('library')?['','material','Material & Aufgaben']:location.hash.includes('manage')?['','manage','Einstellungen']:location.hash.includes('tools')?['','games','Quiz & Spiele']:['','home','Start'];
const current=atRoot?rootView:(ROUTES.find(r=>path.includes(r[0]))||['','tools',document.title.split('·')[0].trim()||'Werkzeug']);
function go(p=''){location.href=new URL(p,HOME).toString()}
function loadScript(name){const src=new URL(name,TOOLS).href,old=[...document.scripts].find(s=>s.src===src);if(old)return Promise.resolve();return new Promise((res,rej)=>{const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
function ensureCss(){for(const [id,file] of [['kdsDesign','teacher-design-v50.css?v=20260923-v53'],['kdsAdapters','teacher-page-adapters-v50.css?v=20260923-v53']])if(!document.getElementById(id)){const l=document.createElement('link');l.id=id;l.rel='stylesheet';l.href=new URL(file,TOOLS);document.head.appendChild(l)}}
async function sessionApi(){if(!window.KathleenClassroomSession)await loadScript('classroom-session.js?v=20260923-v53');await window.KathleenClassroomSession.deps();return window.KathleenClassroomSession}
function setLang(lang){if(window.KathleenI18n){lang==='auto'?window.KathleenI18n.auto():window.KathleenI18n.setLanguage(lang,true);return}lang==='auto'?localStorage.removeItem('kathleenUiLanguageOverrideV1'):localStorage.setItem('kathleenUiLanguageOverrideV1',lang);location.reload()}
function presentation(){if(window.KathleenPresentation){window.KathleenPresentation.isActive()?window.KathleenPresentation.exit():window.KathleenPresentation.enter();return}const s=document.createElement('script');s.src=new URL('presentation-mode.js?v=20260923-v53',TOOLS);s.onload=()=>window.KathleenPresentation?.enter?.();document.head.appendChild(s)}
function rootLink(view,label,icon){const href=new URL(view==='home'?'':('#'+view),HOME);return link(view,icon,label,href,view)}
function link(key,icon,label,dest,rootTarget=''){return '<a href="'+dest+'" data-kds-key="'+key+'"'+(rootTarget?' data-root-view="'+rootTarget+'"':'')+(current[1]===key?' aria-current="page"':'')+'>'+svg(icon)+'<span>'+label+'</span></a>'}
function closeMore(){document.getElementById('kdsMore')?.remove()}
function more(label,dest,icon){return '<a href="'+new URL('tools/'+dest,HOME)+'" data-tool="'+dest+'">'+svg(icon)+'<span>'+label+'</span></a>'}
function openMore(){closeMore();const d=document.createElement('div');d.id='kdsMore';d.className='kds-more-sheet';d.innerHTML='<div class="kds-more-card"><div class="kds-more-head"><div><small>DEINE KISTE</small><h2>Weitere Werkzeuge</h2></div><button class="kds-close" data-close>×</button></div><div class="kds-more-grid">'+more('Sitzplan','seating-plan/','seat')+more('Hausaufgaben','homework-strikes/','doc')+more('Gutscheine','homework-vouchers/','spark')+more('Randomizer','randomizer/','spark')+more('Team Generator','team-generator/','users')+more('Timer','classroom-timer/','clock')+more('Push Center','push-center/','spark')+more('Klassenlisten','class-lists/','users')+more('Schulaufgaben','schulaufgabenrechner/','doc')+more('Live Poll','live-poll/','grid')+more('Escape Room','escape-room/','game')+more('Lehrerzentrale','teacher-command/','settings')+'</div><div class="kds-more-section">SPRACHE</div><div class="kds-lang"><button data-lang="de">Deutsch</button><button data-lang="en">English</button><button data-lang="auto">Auto</button></div><button class="kds-present" data-present>⛶ Präsentationsmodus</button></div>';document.body.appendChild(d);d.onclick=e=>{if(e.target===d)closeMore()};d.querySelector('[data-close]').onclick=closeMore;d.querySelectorAll('[data-tool]').forEach(a=>a.onclick=e=>{e.preventDefault();go('tools/'+a.dataset.tool)});d.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>setLang(b.dataset.lang));d.querySelector('[data-present]').onclick=()=>{presentation();closeMore()}}
function activateRootView(view){if(!atRoot)return false;const map={home:'home',material:'library',games:'tools',manage:'manage'},v=map[view];if(!v)return false;const btn=document.querySelector('.nav-btn[data-view="'+v+'"]');if(btn){btn.click();history.replaceState(null,'',view==='home'?location.pathname:'#'+v);document.querySelectorAll('.kds-sidebar [aria-current]').forEach(a=>a.removeAttribute('aria-current'));document.querySelector('.kds-sidebar [data-kds-key="'+view+'"]')?.setAttribute('aria-current','page');return true}return false}
function bindRootLinks(root){root.querySelectorAll('[data-root-view]').forEach(a=>a.onclick=e=>{if(atRoot&&activateRootView(a.dataset.rootView))e.preventDefault()})}
function sidebarCollapsed(v){document.documentElement.classList.toggle('kds-sidebar-collapsed',v);localStorage.setItem(COLLAPSE,v?'1':'0');const b=document.querySelector('.kds-sidebar-toggle');if(b){b.setAttribute('aria-pressed',String(v));b.title=v?'Seitenleiste ausklappen':'Seitenleiste einklappen'}}
function toggleSidebar(){sidebarCollapsed(!document.documentElement.classList.contains('kds-sidebar-collapsed'))}
function createShell(){if(document.querySelector('.kds-sidebar'))return;ensureCss();document.documentElement.classList.add('k-teacher-shell');document.documentElement.dataset.kdsPage=current[1];document.body.classList.add('kds-content-offset');if(localStorage.getItem(COLLAPSE)==='1')document.documentElement.classList.add('kds-sidebar-collapsed');
 const side=document.createElement('aside');side.className='kds-sidebar';side.innerHTML='<a class="kds-brand" href="'+HOME+'"><span class="kds-brandmark">'+svg('spark')+'</span><span>Kathleens<br><strong>magische Kiste</strong></span></a><button class="kds-sidebar-toggle" type="button" aria-label="Seitenleiste ein-/ausklappen">'+svg('chev')+'</button><span class="kds-navlabel">MEIN UNTERRICHT</span><nav>'+rootLink('home','Start','home')+link('timetable','calendar','Stundenplan',new URL('tools/timetable/',HOME))+link('classes','users','Meine Klassen',new URL('tools/class-cockpit/',HOME))+link('whiteboard','board','Whiteboard',new URL('tools/classroom-board/',HOME))+link('quest','spark','Quest Mode',new URL('tools/quest-mode/',HOME))+link('observations','eye','Beobachtungen',new URL('tools/mobile-observations/',HOME))+rootLink('material','Material & Aufgaben','doc')+rootLink('games','Quiz & Spiele','game')+'</nav><div class="kds-sidebar-foot">'+rootLink('manage','Einstellungen','settings')+'<small>Gemeinsam lernen.<br>Gemeinsam wachsen.</small></div>';document.body.prepend(side);bindRootLinks(side);side.querySelector('.kds-sidebar-toggle').onclick=toggleSidebar;
 const top=document.createElement('header');top.className='kds-topbar';top.innerHTML='<div class="kds-crumb"><span>Meine Kiste</span><span>/</span><strong>'+current[2]+'</strong></div><div class="kds-top-actions"><button class="kds-start-now" type="button" hidden>'+svg('play')+'<span>Stunde starten</span></button><label class="kds-search">'+svg('search')+'<input placeholder="In deiner Kiste suchen …"></label><span class="kds-avatar">K</span><span class="kds-teacher">Kathleen</span><button class="kds-more-btn">Mehr</button></div>';document.body.prepend(top);top.querySelector('.kds-more-btn').onclick=openMore;top.querySelector('input').onkeydown=e=>{if(e.key!=='Enter'||!e.target.value.trim())return;sessionStorage.setItem('kathleenHomeSearchV53',e.target.value.trim());if(atRoot){const search=document.getElementById('search');if(search){search.value=e.target.value.trim();search.dispatchEvent(new Event('input'));activateRootView('material')}}else go('#library')};
 const mobile=document.createElement('nav');mobile.className='kds-mobile-nav';mobile.innerHTML='<button data-home class="'+(current[1]==='home'?'active':'')+'">'+svg('home')+'<span>Start</span></button><button data-go="classroom-board/" class="'+(current[1]==='whiteboard'?'active':'')+'">'+svg('board')+'<span>Board</span></button><button data-go="class-cockpit/" class="'+(current[1]==='classes'?'active':'')+'">'+svg('users')+'<span>Klasse</span></button><button data-more>'+svg('grid')+'<span>Mehr</span></button>';document.body.appendChild(mobile);mobile.querySelector('[data-home]').onclick=()=>go();mobile.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go('tools/'+b.dataset.go));mobile.querySelector('[data-more]').onclick=openMore}
function remaining(x){if(!x?.end)return'';const [h,m]=String(x.end).split(':').map(Number),now=new Date(),end=new Date(now);end.setHours(h,m,0,0);const n=Math.ceil((end-now)/60000);return n>0?n+' min':'Ende'}
function barPosition(bar){if(matchMedia('(max-width:560px)').matches)return;try{const p=JSON.parse(localStorage.getItem(BAR_POS)||'null');if(p&&Number.isFinite(p.x)&&Number.isFinite(p.y)){bar.style.left=Math.min(innerWidth-bar.offsetWidth-12,Math.max(12,p.x))+'px';bar.style.top=Math.min(innerHeight-bar.offsetHeight-12,Math.max(76,p.y))+'px';bar.style.right='auto';bar.style.bottom='auto'}}catch(e){}}
function dragBar(bar,handle){let drag=null;handle.addEventListener('pointerdown',e=>{if(matchMedia('(max-width:560px)').matches)return;drag={dx:e.clientX-bar.getBoundingClientRect().left,dy:e.clientY-bar.getBoundingClientRect().top};handle.setPointerCapture?.(e.pointerId);bar.classList.add('dragging')});handle.addEventListener('pointermove',e=>{if(!drag)return;const x=Math.min(innerWidth-bar.offsetWidth-12,Math.max(12,e.clientX-drag.dx)),y=Math.min(innerHeight-bar.offsetHeight-12,Math.max(76,e.clientY-drag.dy));bar.style.left=x+'px';bar.style.top=y+'px';bar.style.right='auto';bar.style.bottom='auto'});const end=()=>{if(!drag)return;localStorage.setItem(BAR_POS,JSON.stringify({x:parseFloat(bar.style.left)||12,y:parseFloat(bar.style.top)||84}));drag=null;bar.classList.remove('dragging')};handle.addEventListener('pointerup',end);handle.addEventListener('pointercancel',end)}
async function endSession(){const api=await sessionApi(),lesson=window.KathleenLessonMode?.get?.();if(!lesson){if(confirm('Klassensession beenden?')){await api.close({silent:true});renderSessionBar()}return}window.KathleenLessonMode.end();setTimeout(()=>{const finish=document.querySelector('#lessonEndModal [data-le="finish"]'),prep=document.querySelector('#lessonEndModal [data-le="prep"]');if(finish)finish.onclick=async()=>{finish.disabled=true;await api.close({silent:true});window.KathleenLessonMode.finish();renderSessionBar()};if(prep)prep.onclick=async()=>{prep.disabled=true;await api.close({silent:true});if(window.KathleenLessonMode.finish())go()}},0)}
let stateTimer=null;
async function renderSessionBar(){const api=await sessionApi(),lesson=window.KathleenLessonMode?.get?.(),room=api.get();let bar=document.getElementById('kdsSessionBar');if(!lesson&&!room){bar?.remove();return}if(!bar){bar=document.createElement('section');bar.id='kdsSessionBar';bar.className='kds-session-bar';bar.innerHTML='<button class="kds-session-drag" type="button" title="Verschieben">'+svg('move')+'</button><span class="kds-session-dot"></span><div class="kds-session-main"><b data-session-title></b><span data-session-meta></span></div><span class="kds-session-online" data-session-online></span><div class="kds-session-tools"><button data-session="seat">'+svg('seat')+'<span>Sitzplan</span></button><button data-session="board">'+svg('board')+'<span>Board</span></button><button data-session="observe">'+svg('eye')+'<span>Beobachten</span></button><button data-session="quest">'+svg('spark')+'<span>Quest</span></button><button data-session="qr">'+svg('qr')+'<span>QR</span></button><button data-session="present">⛶<span>Präsentieren</span></button></div><button class="kds-session-min" type="button" data-session="min">'+svg('minus')+'</button><button class="kds-session-end" type="button" data-session="end">Beenden</button>';document.body.appendChild(bar);bar.querySelector('[data-session="seat"]').onclick=()=>go('tools/seating-plan/');bar.querySelector('[data-session="board"]').onclick=()=>go('tools/classroom-board/');bar.querySelector('[data-session="observe"]').onclick=()=>go('tools/mobile-observations/');bar.querySelector('[data-session="quest"]').onclick=()=>go('tools/quest-mode/');bar.querySelector('[data-session="qr"]').onclick=()=>api.showQr();bar.querySelector('[data-session="present"]').onclick=presentation;bar.querySelector('[data-session="end"]').onclick=endSession;bar.querySelector('[data-session="min"]').onclick=()=>{const v=!bar.classList.contains('minimized');bar.classList.toggle('minimized',v);localStorage.setItem(BAR_MIN,v?'1':'0')};if(localStorage.getItem(BAR_MIN)==='1')bar.classList.add('minimized');dragBar(bar,bar.querySelector('.kds-session-drag'));requestAnimationFrame(()=>barPosition(bar))}
 const title=(lesson?.subject||'Unterricht')+' · '+(lesson?.className||room?.className||room?.class_name||'');bar.querySelector('[data-session-title]').textContent=title;const meta=[lesson?.room||'',remaining(lesson)].filter(Boolean).join(' · ');bar.querySelector('[data-session-meta]').textContent=meta;const connected=Number(room?.connectedCount??0),roster=Number(room?.rosterCount??0);bar.querySelector('[data-session-online]').textContent=room?.session_id?(connected+(roster?'/'+roster:'')+' online'):'Lesson Mode';bar.classList.toggle('has-classroom',!!room?.session_id)}
async function pollSession(){const api=await sessionApi(),room=api.get();if(room?.session_id)await api.teacherState();await renderSessionBar()}
async function startLesson(entry){const api=await sessionApi();return api.openStartDialog(entry||window.KathleenLessonMode?.currentSchedule?.()||{})}
async function bootSession(){try{await sessionApi();await renderSessionBar();const lesson=window.KathleenLessonMode?.get?.(),now=window.KathleenLessonMode?.currentSchedule?.(),b=document.querySelector('.kds-start-now');if(b&&now&&!lesson){b.hidden=false;b.onclick=()=>startLesson(now)}const api=window.KathleenClassroomSession;if(api.consumeQrRequest())setTimeout(()=>api.showQr(),420);clearInterval(stateTimer);stateTimer=setInterval(()=>{if(document.visibilityState==='visible')pollSession()},4000);for(const ev of ['kathleen:lessonmode','kathleen:classroomsession','kathleen:classroom'])window.addEventListener(ev,()=>renderSessionBar())}catch(e){console.warn('Session UI unavailable',e)}}
function inject(){createShell();bootSession()}
window.KathleenTeacherShell={home:()=>go(),more:openMore,presentation,setLanguage:setLang,startLesson,toggleSidebar,refreshSession:renderSessionBar,session:sessionApi};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject,{once:true});else inject();
})();