(()=>{'use strict';
if(window.KathleenTodoStore)return;
const KEY='kathleen-home-todos-v1',BACKUP='kathleen-home-todos-backup-v3',TOMBS='kathleen-home-todos-tombstones-v1',DB='kathleenTeacherDataV3',STORE='kv',CLOUD='todos-2026-27',SB='https://fzqxnjhuvgpgovcovosl.supabase.co/rest/v1/rpc/',API='sb_publishable_GIyyWoyaQXipaA4S9OuTyQ_cZn7LUgV',AAD='KathleenTodoVaultV3';
const enc=new TextEncoder(),dec=new TextDecoder();const now=()=>new Date().toISOString();
const parse=s=>{try{const x=JSON.parse(s||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}};const uid=(p='todo')=>p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);
function normalizeStep(x={}){return{id:String(x.id||uid('step')),text:String(x.text||''),done:!!x.done,createdAt:x.createdAt||now(),updatedAt:x.updatedAt||x.createdAt||now()}}
function normalizeMaterial(x={}){return{id:String(x.id||uid('mat')),title:String(x.title||x.name||'Material'),href:String(x.href||x.url||''),type:String(x.type||'link'),sourceId:String(x.sourceId||''),createdAt:x.createdAt||now()}}
function normalize(x={}){const ids=Array.isArray(x.classIds)?x.classIds.map(String).filter(Boolean):(x.classId?[String(x.classId)]:[]),names=Array.isArray(x.classNames)?x.classNames.map(String).filter(Boolean):(x.className?[String(x.className)]:[]);return{id:String(x.id||uid()),text:String(x.text||''),done:!!x.done,important:!!x.important,classIds:[...new Set(ids)],classNames:[...new Set(names)],classId:ids[0]||'',className:names[0]||'',subject:String(x.subject||''),due:x.due||'',priority:x.priority||'normal',repeat:x.repeat||'none',push:!!x.push,pushReminderId:x.pushReminderId||'',notes:String(x.notes||''),steps:(Array.isArray(x.steps)?x.steps:[]).map(normalizeStep),materials:(Array.isArray(x.materials)?x.materials:[]).map(normalizeMaterial).filter(m=>m.title||m.href),createdAt:x.createdAt||now(),updatedAt:x.updatedAt||x.createdAt||now()}}
const norm=a=>(Array.isArray(a)?a:[]).map(normalize);const tombs=()=>{try{return JSON.parse(localStorage.getItem(TOMBS)||'{}')||{}}catch(e){return{}}};const setTombs=t=>localStorage.setItem(TOMBS,JSON.stringify(t));
function merge(...sets){const t=tombs(),m=new Map();for(const a of sets)for(const x of norm(a)){const dead=t[x.id];if(dead&&String(dead)>=String(x.updatedAt||x.createdAt))continue;const old=m.get(x.id);if(!old||String(x.updatedAt||x.createdAt)>=String(old.updatedAt||old.createdAt))m.set(x.id,x)}return[...m.values()]}
function load(){let a=parse(localStorage.getItem(KEY));if(!a.length){const b=parse(localStorage.getItem(BACKUP));if(b.length){a=b;localStorage.setItem(KEY,JSON.stringify(b))}}return merge(a)}
function idb(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE)};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function idbGet(){try{const db=await idb();return await new Promise((res,rej)=>{const q=db.transaction(STORE,'readonly').objectStore(STORE).get(KEY);q.onsuccess=()=>res(norm(q.result||[]));q.onerror=()=>rej(q.error)})}catch(e){return[]}}
async function idbSet(a){try{const db=await idb();await new Promise((res,rej)=>{const q=db.transaction(STORE,'readwrite').objectStore(STORE).put(norm(a),KEY);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)})}catch(e){}}
function b64(a){let s='';for(let i=0;i<a.length;i+=8192)s+=String.fromCharCode(...a.subarray(i,i+8192));return btoa(s)}function unb64(s){const x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a}
async function derive(pass,salt,it=250000){const m=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:it,hash:'SHA-256'},m,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encrypt(a,pass){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),k=await derive(pass,salt),data=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:enc.encode(AAD)},k,enc.encode(JSON.stringify(norm(a)))));return{version:3,cipher:'AES-256-GCM',kdf:'PBKDF2-SHA256',iterations:250000,salt:b64(salt),iv:b64(iv),data:b64(data),updatedAt:now()}}
async function decrypt(v,pass){const k=await derive(pass,unb64(v.salt),Number(v.iterations)||250000),p=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(v.iv),additionalData:enc.encode(AAD)},k,unb64(v.data));return norm(JSON.parse(dec.decode(p)))}async function rpc(name,body){const r=await fetch(SB+name,{method:'POST',headers:{apikey:API,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error(await r.text());return r.json()}
async function cloudPush(a,pass=sessionStorage.getItem('kathleenAdminPass')||''){if(!pass||!navigator.onLine)return false;try{await rpc('class_vault_save',{p_passphrase:pass,p_vault_id:CLOUD,p_vault:await encrypt(a,pass)});return true}catch(e){console.warn('To-do Cloud-Sicherung fehlgeschlagen',e);return false}}async function cloudPull(pass=sessionStorage.getItem('kathleenAdminPass')||''){if(!pass||!navigator.onLine)return[];try{const d=await rpc('class_vault_get',{p_passphrase:pass,p_vault_id:CLOUD});return d?.exists&&d.vault?.data?await decrypt(d.vault,pass):[]}catch(e){return[]}}
async function save(a){a=merge(a);const raw=JSON.stringify(a);localStorage.setItem(KEY,raw);localStorage.setItem(BACKUP,raw);await idbSet(a);try{if(window.KathleenClassLists?.isUnlocked?.())await window.KathleenClassLists.secureSet('teacher-todos-v3',a)}catch(e){}cloudPush(a);window.dispatchEvent(new CustomEvent('kathleen:todos',{detail:{count:a.length}}));return a}
async function remove(id,current){id=String(id);const t=tombs();t[id]=now();setTombs(t);return save((current||load()).filter(x=>String(x.id)!==id))}
async function init(){const a=load(),b=await idbGet();let s=[];try{if(window.KathleenClassLists?.isUnlocked?.())s=await window.KathleenClassLists.secureGet('teacher-todos-v3',[])}catch(e){}const cloud=await cloudPull(),all=merge(a,b,s,cloud);await save(all);return all}
window.KathleenTodoStore={load,save,remove,init,cloudPush,cloudPull,normalize,normalizeStep,normalizeMaterial,merge,key:KEY};init().then(()=>window.dispatchEvent(new CustomEvent('kathleen:todos-ready'))).catch(console.warn);
})();