(()=>{'use strict';if(window.KathleenArcadeHubV2)return;window.KathleenArcadeHubV2=true;const $=(s,r=document)=>r.querySelector(s);let selected='buzzer';const info={buzzer:{title:'Buzzer Battle',desc:'Zwei Teams treten in einer echten Quizshow-Arena gegeneinander an.',tags:['Teams','Buzzer','Schnelligkeit','Premium V3']},risk:{title:'Risk or Safe',desc:'Wissen trifft Entscheidung: sichere Punkte nehmen oder für mehr Risiko gehen.',tags:['Teams','Taktik','Quiz','Premium V2']},timeline:{title:'Timeline Race',desc:'Ereignisse unter Zeitdruck in die richtige historische Reihenfolge bringen.',tags:['Geschichte','Chronologie','Demo']},picture:{title:'Picture Reveal',desc:'Ein Bild wird Stück für Stück sichtbar. Wer erkennt es zuerst?',tags:['Visuell','Raten','Demo']},bomb:{title:'Word Bomb',desc:'Begriffe finden, bevor die Zeit abläuft.',tags:['Englisch','Wortschatz','Demo']},classvs:{title:'Class vs Teacher',desc:'Die Klasse fordert Frau Müller heraus.',tags:['Klasse','Challenge','Demo']}};
function ensure(){if($('#arcLobby'))return;document.body.insertAdjacentHTML('beforeend',`<div class="arc-lobby" id="arcLobby"><div class="arc-panel"><button class="arc-close" type="button" data-arc-close>×</button><div class="arc-cover"><div class="arc-eyebrow">KATHLEEN'S ARCADE · GAME LOBBY</div><h2 id="arcTitle"></h2><p id="arcDesc"></p></div><div class="arc-body"><section class="arc-section"><h3>Spiel vorbereiten</h3><div class="arc-meta" id="arcTags"></div><label class="arc-field"><span>SET-TITEL</span><input id="arcSetTitle"></label><label class="arc-field"><span>FRAGEN / INHALTE</span><textarea id="arcContent"></textarea></label><div class="arc-row"><button class="arc-secondary" type="button" id="arcDemo">Beispiel laden</button><button class="arc-secondary" type="button" id="arcSave">Set speichern</button></div></section><aside class="arc-section"><h3>Bereit?</h3><div class="arc-meta"><span class="arc-chip">Beamer</span><span class="arc-chip">iPad</span><span class="arc-chip">Live</span></div><div class="arc-tip">Im Spiel verschwindet die komplette Verwaltungsoberfläche. Übrig bleiben nur die Game Stage und eine kleine Lehrersteuerung.</div><div class="arc-actions"><button class="arc-start" type="button" id="arcStart">SPIEL STARTEN</button><button class="arc-secondary" type="button" id="arcPresent">Beamer-Fenster öffnen</button></div></aside></div></div></div><div class="arc-gameview" id="arcGameview"></div>`);$('#arcLobby').addEventListener('click',e=>{if(e.target===e.currentTarget||e.target.closest('[data-arc-close]'))closeLobby()});$('#arcSave').onclick=save;$('#arcDemo').onclick=demo;$('#arcStart').onclick=start;$('#arcPresent').onclick=present}
function cardClick(e){const card=e.target.closest('.qg-game[data-game]');if(!card)return;e.preventDefault();e.stopImmediatePropagation();open(card.dataset.game)}
function open(g){selected=g;const m=info[g];if(!m)return;const card=$(`.qg-game[data-game="${g}"]`);card?.click?.__noop;document.body.dataset.qgpGame=g;$('#arcTitle').textContent=m.title;$('#arcDesc').textContent=m.desc;$('#arcTags').innerHTML=m.tags.map(x=>`<span class="arc-chip">${x}</span>`).join('');const gameCard=document.querySelector(`.qg-game[data-game="${g}"]`);document.querySelectorAll('.qg-game').forEach(x=>x.classList.toggle('active',x===gameCard));const nativeTitle=$('#setTitle'),nativeContent=$('#contentBox');if(nativeTitle)$('#arcSetTitle').value=nativeTitle.value||m.title;if(nativeContent)$('#arcContent').value=nativeContent.value||'';$('#arcLobby').classList.add('show');document.body.style.overflow='hidden'}
function closeLobby(){$('#arcLobby')?.classList.remove('show');document.body.style.overflow=''}
function syncNative(){const t=$('#setTitle'),c=$('#contentBox');if(t)t.value=$('#arcSetTitle').value;if(c)c.value=$('#arcContent').value}
function save(){syncNative();$('#saveBtn')?.click();setTimeout(()=>open(selected),40)}
function demo(){const old=$('#contentBox')?.value||'';$('#demoBtn')?.click();setTimeout(()=>{$('#arcContent').value=$('#contentBox')?.value||old},20)}
function start(){syncNative();$('#saveBtn')?.click();setTimeout(()=>{closeLobby();const ws=$('#workspace'),view=$('#arcGameview');if(!ws||!view)return;view.appendChild(ws);view.classList.add('show');const exit=document.createElement('button');exit.className='arc-exit';exit.type='button';exit.textContent='← Spiele';exit.onclick=stop;view.appendChild(exit);document.body.style.overflow='hidden';window.dispatchEvent(new CustomEvent('kathleen:arcade-start',{detail:{game:selected}}))},50)}
function stop(){const view=$('#arcGameview'),ws=$('#workspace');if(ws)document.querySelector('.qg-shell')?.appendChild(ws);view?.querySelector('.arc-exit')?.remove();view?.classList.remove('show');document.body.style.overflow='';open(selected)}
function present(){syncNative();$('#saveBtn')?.click();setTimeout(()=>{const u=new URL(location.href);u.searchParams.set('present','1');u.searchParams.set('game',selected);window.open(u,'qg-present','width=1440,height=900')},40)}
function boot(){if(new URLSearchParams(location.search).get('present')==='1')return;ensure();const grid=$('#gameGrid');if(grid)grid.addEventListener('click',cardClick,true);document.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('#arcGameview')?.classList.contains('show'))stop();else closeLobby()}})}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot()})();