(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],BASE='../../data/vocabulary/',DIFFICULTY_KEY='kathleenVocabularyDifficultyV1';
const state={grade:7,unit:'all',section:'all',pos:'all',search:'',difficult:false,favorites:false,page:1,pageSize:60,entries:[],catalog:null,selected:new Set(),fav:new Set(read('kathleenVocabularyFavoritesV1',[])),difficulty:read(DIFFICULTY_KEY,{})};
const DIFFICULTY={easy:{label:'Leicht',next:'standard'},standard:{label:'Mittel',next:'challenge'},challenge:{label:'Schwer',next:'easy'}};
function read(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch(e){return f}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
async function json(path){const r=await fetch(BASE+path);if(!r.ok)throw Error(path+' ('+r.status+')');return r.json()}
function boxText(b){const rows=(b.rows||[]).flat().join(' · '),items=(b.items||[]).join(' · '),groups=(b.groups||[]).flatMap(g=>[g.head,...(g.items||[]),...(g.notes||[])]).join(' · ');return [rows,items,groups,...(b.notes||[])].filter(Boolean).join(' · ')}
async function load(){try{state.catalog=await json('catalog.json');const paths=[],boxPaths=[];for(const g of state.catalog.grades){if(g.supplementary)paths.push(g.supplementary.data);paths.push(...g.units.map(u=>u.data));boxPaths.push(g.knowledge_boxes)}const [docs,boxDocs]=await Promise.all([Promise.all(paths.map(json)),Promise.all(boxPaths.map(json))]);const words=docs.flatMap(d=>d.entries.map(x=>({...x,grade:d.grade,difficulty:state.difficulty[x.id]||((x.tags||[]).includes('difficult')?'challenge':'standard')})));if(words.length!==state.catalog.entry_count)throw Error('Katalogzahl stimmt nicht mit den Datendateien überein.');const boxes=boxDocs.flatMap(d=>d.boxes.map(b=>({id:b.id,english:b.title,german:boxText(b),phonetic:'',part_of_speech:'knowledge-box',unit:b.unit,unit_title:'Lernkasten',section:'Lernkasten',page:b.page,tags:['knowledge-box'],grade:d.grade,isBox:true,difficulty:'standard'})));state.entries=[...words,...boxes];$('#notice').className='notice ready';$('#total').textContent=words.length.toLocaleString('de-DE');setupUnits();render()}catch(e){$('#notice').className='notice error';$('#notice').innerHTML='<b>Die Vokabeldaten konnten nicht vollständig geladen werden.</b><br>'+esc(e.message);$('#list').innerHTML=''}}
function gradeMeta(){return state.catalog.grades.find(g=>g.grade===state.grade)}
function setupUnits(){const g=gradeMeta(),opts=['<option value="all">Alle Units</option>'];if(g.supplementary)opts.push('<option value="0">Zusatzmaterial</option>');for(const u of g.units)opts.push('<option value="'+u.unit+'">Unit '+u.unit+' · '+esc(u.title)+'</option>');$('#unit').innerHTML=opts.join('');state.unit='all';setupSections()}
function setupSections(){const sections=[...new Set(state.entries.filter(x=>x.grade===state.grade&&(state.unit==='all'||String(x.unit??0)===state.unit)).map(x=>x.section))].sort((a,b)=>a.localeCompare(b,'de'));$('#section').innerHTML='<option value="all">Alle Abschnitte</option>'+sections.map(x=>'<option>'+esc(x)+'</option>').join('');state.section='all'}
function filtered(){const q=norm(state.search);return state.entries.filter(x=>x.grade===state.grade&&(state.unit==='all'||String(x.unit??0)===state.unit)&&(state.section==='all'||x.section===state.section)&&(state.pos==='all'||x.part_of_speech===state.pos)&&(!state.difficult||x.difficulty==='challenge')&&(!state.favorites||state.fav.has(x.id))&&(!q||norm(x.english+' '+x.german+' '+x.section+' '+x.phonetic).includes(q)))}
function render(){const items=filtered(),pages=Math.max(1,Math.ceil(items.length/state.pageSize));state.page=Math.min(state.page,pages);const shown=items.slice((state.page-1)*state.pageSize,state.page*state.pageSize);$('#resultCount').textContent=items.length.toLocaleString('de-DE')+' Treffer';$('#selectionCount').textContent=state.selected.size+' ausgewählt';$('#list').innerHTML=shown.length?shown.map(x=>`<article class="word" data-id="${x.id}"><input type="checkbox" aria-label="${esc(x.english)} auswählen" ${state.selected.has(x.id)?'checked':''}><div class="english"><strong>${esc(x.english)}</strong><small>${x.phonetic?'['+esc(x.phonetic)+']':'ohne Lautschrift'}</small></div><div class="german">${esc(x.german)}</div><div class="word-side"><div class="meta"><span>${x.unit?'Unit '+x.unit:'Zusatz'}</span><span>S. ${x.page}</span><span>${esc(x.section)}</span></div>${x.isBox?'':`<button class="difficulty-tag ${x.difficulty}" aria-label="Schwierigkeit ändern" title="Klicken zum Ändern">${DIFFICULTY[x.difficulty].label}</button>`}<button class="star ${state.fav.has(x.id)?'on':''}" aria-label="Favorit">★</button></div></article>`).join(''):'<div class="empty">Keine passenden Vokabeln gefunden.</div>';$('#pageInfo').textContent='Seite '+state.page+' / '+pages;$('#prev').disabled=state.page<=1;$('#next').disabled=state.page>=pages;$$('.word').forEach(el=>{const id=el.dataset.id,x=state.entries.find(item=>item.id===id);el.querySelector('input').onchange=e=>{e.target.checked?state.selected.add(id):state.selected.delete(id);render()};el.querySelector('.star').onclick=()=>{state.fav.has(id)?state.fav.delete(id):state.fav.add(id);localStorage.setItem('kathleenVocabularyFavoritesV1',JSON.stringify([...state.fav]));render()};const tag=el.querySelector('.difficulty-tag');if(tag)tag.onclick=()=>{x.difficulty=DIFFICULTY[x.difficulty].next;state.difficulty[id]=x.difficulty;localStorage.setItem(DIFFICULTY_KEY,JSON.stringify(state.difficulty));render()}})}
function reset(){state.page=1;render()}
$$('[data-grade]').forEach(b=>b.onclick=()=>{state.grade=Number(b.dataset.grade);$$('[data-grade]').forEach(x=>x.classList.toggle('active',x===b));setupUnits();reset()});$('#unit').onchange=e=>{state.unit=e.target.value;setupSections();reset()};$('#section').onchange=e=>{state.section=e.target.value;reset()};$('#pos').onchange=e=>{state.pos=e.target.value;reset()};$('#search').oninput=e=>{state.search=e.target.value;reset()};$('#difficult').onchange=e=>{state.difficult=e.target.checked;reset()};$('#favorites').onchange=e=>{state.favorites=e.target.checked;reset()};$('#prev').onclick=()=>{state.page--;render();scrollTo({top:0,behavior:'smooth'})};$('#next').onclick=()=>{state.page++;render();scrollTo({top:0,behavior:'smooth'})};$('#selectVisible').onclick=()=>{filtered().forEach(x=>state.selected.add(x.id));render()};$('#clearSelection').onclick=()=>{state.selected.clear();render()};
function chosen(){const all=state.entries.filter(x=>!x.isBox&&state.selected.has(x.id));return all.length?all:filtered().filter(x=>!x.isBox).slice(0,12)}
$('#football').onclick=()=>{const selected=state.entries.filter(x=>!x.isBox&&state.selected.has(x.id)),words=(selected.length?selected:filtered().filter(x=>!x.isBox)).slice(0,80);if(words.length<2){alert('Bitte mindestens zwei Vokabeln auswählen.');return}localStorage.setItem('kathleenVocabularyFootballPayloadV1',JSON.stringify({ids:words.map(x=>x.id),createdAt:new Date().toISOString()}));location.href='../vocabulary-football/?selection=1'};
$('#memory').onclick=()=>{const words=chosen().slice(0,30);if(words.length<2){alert('Bitte mindestens zwei Vokabeln auswählen.');return}localStorage.setItem('kathleenVocabularyGamePayloadV1',JSON.stringify({content:words.map(x=>x.english+' | '+x.german.replace(/\|/g,'/')).join('\n'),count:words.length,createdAt:new Date().toISOString()}));localStorage.setItem('kathleenQuickGamesDemoPackV66','english');location.href='../quick-games/?vocab=memory'};
$('#worksheet').onclick=()=>{const ids=new Set(chosen().map(x=>x.id));$$('.word').forEach(el=>el.style.display=ids.has(el.dataset.id)?'grid':'none');window.print();$$('.word').forEach(el=>el.style.display='')};
load();
})();
