(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],BASE='../../data/vocabulary/',DIFFICULTY_KEY='kathleenVocabularyDifficultyV1';
const state={grade:7,unit:'all',section:'all',pos:'all',search:'',difficult:false,favorites:false,page:1,pageSize:60,entries:[],catalog:null,selected:new Set(),fav:new Set(read('kathleenVocabularyFavoritesV1',[])),difficulty:read(DIFFICULTY_KEY,{})};
const DIFFICULTY={easy:{label:'Leicht',next:'standard'},standard:{label:'Mittel',next:'challenge'},challenge:{label:'Schwer',next:'easy'}};
function read(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch(e){return f}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
async function json(path){const r=await fetch(BASE+path);if(!r.ok)throw Error(path+' ('+r.status+')');return r.json()}
function boxText(b){const rows=(b.rows||[]).flat().join(' · '),items=(b.items||[]).join(' · '),groups=(b.groups||[]).flatMap(g=>[g.head,...(g.items||[]),...(g.notes||[])]).join(' · ');return [rows,items,groups,...(b.notes||[])].filter(Boolean).join(' · ')}
async function load(){try{state.catalog=await json('catalog.json');const paths=[],boxPaths=[];for(const g of state.catalog.grades){if(g.supplementary)paths.push(g.supplementary.data);paths.push(...g.units.map(u=>u.data));boxPaths.push(g.knowledge_boxes)}const [docs,boxDocs]=await Promise.all([Promise.all(paths.map(json)),Promise.all(boxPaths.map(json))]);const words=docs.flatMap(d=>d.entries.map(x=>({...x,grade:d.grade,difficulty:state.difficulty[x.id]||((x.tags||[]).includes('difficult')?'challenge':'standard')})));if(words.length!==state.catalog.entry_count)throw Error('Katalogzahl stimmt nicht mit den Datendateien überein.');const boxes=boxDocs.flatMap(d=>d.boxes.map(b=>({id:b.id,english:b.title,german:boxText(b),phonetic:'',part_of_speech:'knowledge-box',unit:b.unit,unit_title:'Lernkasten',section:'Lernkasten',page:b.page,tags:['knowledge-box'],grade:d.grade,isBox:true,difficulty:'standard'})));state.entries=[...words,...boxes];$('#notice').className='notice ready';$('#total').textContent=words.length.toLocaleString('de-DE');setupUnits();render()}catch(e){$('#notice').className='notice error';$('#notice').innerHTML='<b>Die Vokabeldaten konnten nicht vollständig geladen werden.</b><br>'+esc(e.message);$('#list').innerHTML=''}}
function gradeMeta(){return state.catalog.grades.find(g=>g.grade===state.grade)}
function setupUnits(){const g=gradeMeta(),opts=['<option value="all">Alle Units</option>'];if(g.supplementary)opts.push('<option value="0">Zusatzmaterial</option>');for(const u of g.units)opts.push('<option value="'+u.unit+'">Unit '+u.unit+' · '+esc(u.title)+'</option>');$('#unit').innerHTML=opts.join('');state.unit='all';setupSections()}
function setupSections(){const sections=[...new Set(state.entries.filter(x=>x.grade===state.grade&&(state.unit==='all'||String(x.unit??0)===state.unit)).map(x=>x.section))].sort((a,b)=>a.localeCompare(b,'de'));$('#section').innerHTML='<option value="all">Alle Abschnitte</option>'+sections.map(x=>'<option>'+esc(x)+'</option>').join('');state.section='all'}
function filtered(){const q=norm(state.search);return state.entries.filter(x=>x.grade===state.grade&&(state.unit==='all'||String(x.unit??0)===state.unit)&&(state.section==='all'||x.section===state.section)&&(state.pos==='all'||x.part_of_speech===state.pos)&&(!state.difficult||x.difficulty==='challenge')&&(!state.favorites||state.fav.has(x.id))&&(!q||norm(x.english+' '+x.german+' '+x.section+' '+x.phonetic).includes(q)))}
function render(){const items=filtered(),pages=Math.max(1,Math.ceil(items.length/state.pageSize));state.page=Math.min(state.page,pages);const shown=items.slice((state.page-1)*state.pageSize,state.page*state.pageSize);$('#resultCount').textContent=items.length.toLocaleString('de-DE')+' Treffer';$('#selectionCount').textContent=state.selected.size+' ausgewählt';$('#list').innerHTML=shown.length?shown.map(x=>`<article class="word" data-id="${x.id}"><input type="checkbox" aria-label="${esc(x.english)} auswählen" ${state.selected.has(x.id)?'checked':''}><div class="english"><strong>${esc(x.english)}</strong><small>${x.phonetic?'['+esc(x.phonetic)+']':'ohne Lautschrift'}</small></div><div class="german">${esc(x.german)}</div><div class="word-side"><div class="meta"><span>${x.unit?'Unit '+x.unit:'Zusatz'}</span><span>S. ${x.page}</span><span>${esc(x.section)}</span></div>${x.isBox?'':`<button class="difficulty-tag ${x.difficulty}" aria-label="Schwierigkeit ändern" title="Klicken zum Ändern">${DIFFICULTY[x.difficulty].label}</button>`}<button class="star ${state.fav.has(x.id)?'on':''}" aria-label="Favorit">★</button></div></article>`).join(''):'<div class="empty">Keine passenden Vokabeln gefunden.</div>';$('#pageInfo').textContent='Seite '+state.page+' / '+pages;$('#prev').disabled=state.page<=1;$('#next').disabled=state.page>=pages;$$('.word').forEach(el=>{const id=el.dataset.id,x=state.entries.find(item=>item.id===id);el.querySelector('input').onchange=e=>{e.target.checked?state.selected.add(id):state.selected.delete(id);render()};el.querySelector('.star').onclick=()=>{state.fav.has(id)?state.fav.delete(id):state.fav.add(id);localStorage.setItem('kathleenVocabularyFavoritesV1',JSON.stringify([...state.fav]));render()};const tag=el.querySelector('.difficulty-tag');if(tag)tag.onclick=()=>{x.difficulty=DIFFICULTY[x.difficulty].next;state.difficulty[id]=x.difficulty;localStorage.setItem(DIFFICULTY_KEY,JSON.stringify(state.difficulty));render()}})}
function reset(){state.page=1;render()}
$$('[data-grade]').forEach(b=>b.onclick=()=>{state.grade=Number(b.dataset.grade);$$('[data-grade]').forEach(x=>x.classList.toggle('active',x===b));setupUnits();reset()});$('#unit').onchange=e=>{state.unit=e.target.value;setupSections();reset()};$('#section').onchange=e=>{state.section=e.target.value;reset()};$('#pos').onchange=e=>{state.pos=e.target.value;reset()};$('#search').oninput=e=>{state.search=e.target.value;reset()};$('#difficult').onchange=e=>{state.difficult=e.target.checked;reset()};$('#favorites').onchange=e=>{state.favorites=e.target.checked;reset()};$('#prev').onclick=()=>{state.page--;render();scrollTo({top:0,behavior:'smooth'})};$('#next').onclick=()=>{state.page++;render();scrollTo({top:0,behavior:'smooth'})};$('#selectVisible').onclick=()=>{filtered().forEach(x=>state.selected.add(x.id));render()};$('#clearSelection').onclick=()=>{state.selected.clear();render()};
function chosen(){const all=state.entries.filter(x=>!x.isBox&&state.selected.has(x.id));return all.length?all:filtered().filter(x=>!x.isBox).slice(0,12)}
$('#football').onclick=()=>{const selected=state.entries.filter(x=>!x.isBox&&state.selected.has(x.id)),words=(selected.length?selected:filtered().filter(x=>!x.isBox)).slice(0,80);if(words.length<2){alert('Bitte mindestens zwei Vokabeln auswählen.');return}localStorage.setItem('kathleenVocabularyFootballPayloadV1',JSON.stringify({ids:words.map(x=>x.id),createdAt:new Date().toISOString()}));location.href='../vocabulary-football/?selection=1'};
$('#memory').onclick=()=>{const words=chosen().slice(0,30);if(words.length<2){alert('Bitte mindestens zwei Vokabeln auswählen.');return}localStorage.setItem('kathleenVocabularyGamePayloadV1',JSON.stringify({content:words.map(x=>x.english+' | '+x.german.replace(/\|/g,'/')).join('\n'),count:words.length,createdAt:new Date().toISOString()}));localStorage.setItem('kathleenQuickGamesDemoPackV66','english');location.href='../quick-games/?vocab=memory'};
let worksheetWords=[];
const worksheetTypeLabel={translate:'Übersetzen',"cloze-bank":'Lückentext mit Wortbank',"cloze-free":'Lückentext ohne Wortbank',matching:'Zuordnen',mixed:'Gemischtes Training'};
const worksheetPrintLabel={translate:'Translation',"cloze-bank":'Cloze with word bank',"cloze-free":'Cloze without help',matching:'Matching',mixed:'Mixed practice'};
const shuffle=a=>{const out=[...a];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out};
function worksheetDirection(mode,index){return mode==='mixed'?(index%2?'de-en':'en-de'):mode}
function worksheetItem(word,index,mode,solution=false){const direction=worksheetDirection(mode,index),prompt=direction==='de-en'?word.german:word.english,answer=direction==='de-en'?word.english:word.german,from=direction==='de-en'?'GERMAN':'ENGLISH',to=direction==='de-en'?'ENGLISH':'GERMAN';return `<article class="worksheet-item" data-word-id="${esc(word.id)}"><span class="worksheet-number">${index+1}</span><div class="worksheet-question"><small>${from}</small><strong>${esc(prompt)}</strong></div><div class="worksheet-answer"><small>${to}</small>${solution?`<strong>${esc(answer)}</strong>`:'<i></i><i></i>'}</div></article>`}
function worksheetMeta(){const unit=state.unit==='all'?'All units':state.unit==='0'?'Extra material':'Unit '+state.unit;return `Grade ${state.grade} · ${unit}`}
function worksheetLimit(type){return type==='mixed'?26:type==='matching'?16:type.startsWith('cloze')?12:40}
function sentenceFor(word){const variants=[String(word.english||'').replace(/^to\s+/i,''),String(word.english||'')].filter(Boolean),sentences=String(word.source_note||'').split(/(?<=[.!?])\s+/).filter(s=>s.length>18&&/[.!?]$/.test(s));for(const sentence of sentences)for(const variant of variants){const re=new RegExp(`\\b${variant.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'i');if(re.test(sentence))return{prompt:sentence.replace(re,'________'),answer:variant}}return{prompt:`The English word for “${word.german}” is ________.`,answer:String(word.english||'').replace(/^to\s+/i,'')||word.english}}
function clozeItem(word,index,solution=false){const row=sentenceFor(word);return `<article class="cloze-item" data-word-id="${esc(word.id)}"><span>${index+1}</span><p>${esc(row.prompt)}</p>${solution?`<b>${esc(row.answer)}</b>`:''}</article>`}
function clozeSheet(words,solution=false){return `<div class="worksheet-list cloze-list">${words.map((word,index)=>clozeItem(word,index,solution)).join('')}</div>`}
function matchingSheet(words,solution=false){const right=shuffle(words),letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ';if(solution)return `<div class="matching-solutions">${words.map((word,index)=>`<div data-word-id="${esc(word.id)}"><b>${index+1}</b><span>${esc(word.english)}</span><em>→</em><strong>${esc(word.german)}</strong></div>`).join('')}</div>`;return `<div class="matching-note">Write the matching number next to each German word.</div><div class="matching-grid"><section><h3>ENGLISH</h3>${words.map((word,index)=>`<p data-word-id="${esc(word.id)}"><b>${index+1}</b>${esc(word.english)}</p>`).join('')}</section><section><h3>GERMAN</h3>${right.map((word,index)=>`<p><b>${letters[index]}</b><i></i>${esc(word.german)}</p>`).join('')}</section></div>`}
function worksheetIntro(type,mode){if(type==='matching')return'Match each English word with its German translation.';if(type==='cloze-bank')return'Complete the gaps. All target words are in the word bank.';if(type==='cloze-free')return'Complete every gap without help. Check your spelling.';return mode==='de-en'?'Translate the German words into English.':'Translate the given words into the other language.'}
function worksheetPage(title,count,intro,content,solution=false,page=solution?2:1){return `<div class="worksheet-page ${solution?'worksheet-solutions':''}"><header class="worksheet-print-head"><div><span>${solution?'ANSWER KEY':'ENGLISH VOCABULARY PRACTICE'}</span><h1>${esc(title)}</h1><p>${esc(worksheetMeta())} · ${count} tasks</p></div><div class="worksheet-mark">${solution?'✓':'EN'}</div></header>${solution?'':`<div class="worksheet-student"><span>Name</span><i></i><span>Date</span><i></i></div><div class="worksheet-instruction"><b>Task</b><p>${esc(intro)}</p></div>`}${content}<footer>${solution?'Answer key':worksheetPrintLabel[document.querySelector('[name="worksheetType"]:checked').value]} · Grade ${state.grade}<span>Page ${page}</span></footer></div>`}
function splitMixed(words){const base=Math.floor(words.length/4),remainder=words.length%4,groups=[],sizes=Array.from({length:4},(_,index)=>base+(index<remainder?1:0));let cursor=0;for(const size of sizes){groups.push(words.slice(cursor,cursor+size));cursor+=size}return groups}
function worksheetSection(label,detail,content){return `<section class="worksheet-section"><header><b>${esc(label)}</b><span>${esc(detail)}</span></header>${content}</section>`}
function mixedPageOne(groups,solution=false){const [translate,bank]=groups,translation=`<div class="worksheet-list mixed-translation">${translate.map((word,index)=>worksheetItem(word,index,'mixed',solution)).join('')}</div>`,cloze=(solution?'':`<div class="worksheet-wordbank"><b>Word bank</b>${shuffle(bank.map(word=>`<span>${esc(sentenceFor(word).answer)}</span>`)).join('')}</div>`)+clozeSheet(bank,solution);return worksheetSection('Part A · Translation','Translate the words into the other language.',translation)+worksheetSection('Part B · Cloze with word bank','Use every word from the word bank once.',cloze)}
function mixedPageTwo(groups,solution=false){const [, ,free,matching]=groups,cloze=clozeSheet(free,solution),match=matchingSheet(matching,solution);return worksheetSection('Part C · Cloze without help','Complete each gap from memory.',cloze)+worksheetSection('Part D · Matching','Match English words with their German translations.',match)}
function updateWorksheetOptions(){const type=document.querySelector('[name="worksheetType"]:checked').value;$('#worksheetDirections').hidden=type!=='translate';const count=Math.min(worksheetWords.length,worksheetLimit(type));$('#worksheetCount').textContent=`${count} Vokabeln · ${worksheetTypeLabel[type]} · Klasse ${state.grade}`}
function buildWorksheet(){const type=document.querySelector('[name="worksheetType"]:checked').value,mode=document.querySelector('[name="worksheetMode"]:checked').value,title=$('#worksheetTitle').value.trim()||'Vocabulary Practice',solutions=$('#worksheetSolutions').checked,words=worksheetWords.slice(0,worksheetLimit(type));if(type==='mixed'){if(words.length<8){alert('For mixed practice, please select at least 8 words.');return}const groups=splitMixed(words),first=mixedPageOne(groups),second=mixedPageTwo(groups),answers=mixedPageOne(groups,true)+mixedPageTwo(groups,true);$('#printSheet').innerHTML=worksheetPage(title,words.length,'Complete all four parts. Every selected word is used only once.',first,false,1)+worksheetPage(title,words.length,'Continue with Parts C and D.',second,false,2)+(solutions?worksheetPage(title,words.length,'',answers,true,3):'');$('#worksheetDialog').close();window.print();return}let content='',answers='';if(type==='matching'){content=matchingSheet(words);answers=matchingSheet(words,true)}else if(type.startsWith('cloze')){content=(type==='cloze-bank'?`<div class="worksheet-wordbank"><b>Word bank</b>${shuffle(words.map(word=>`<span>${esc(sentenceFor(word).answer)}</span>`)).join('')}</div>`:'')+clozeSheet(words);answers=clozeSheet(words,true)}else{content=`<div class="worksheet-list">${words.map((word,index)=>worksheetItem(word,index,mode)).join('')}</div>`;answers=`<div class="worksheet-list">${words.map((word,index)=>worksheetItem(word,index,mode,true)).join('')}</div>`}const intro=worksheetIntro(type,mode);$('#printSheet').innerHTML=worksheetPage(title,words.length,intro,content)+ (solutions?worksheetPage(title,words.length,intro,answers,true):'');$('#worksheetDialog').close();window.print()}
$('#worksheet').onclick=()=>{worksheetWords=chosen().slice(0,40);if(!worksheetWords.length){alert('Bitte zuerst Vokabeln auswählen.');return}updateWorksheetOptions();$('#worksheetDialog').showModal()};
$$('[name="worksheetType"]').forEach(input=>input.onchange=updateWorksheetOptions);
$('#createWorksheet').onclick=buildWorksheet;
load();
})();
