(()=>{'use strict';
const EDGE='https://fzqxnjhuvgpgovcovosl.supabase.co/functions/v1/teacher-push',SB='https://fzqxnjhuvgpgovcovosl.supabase.co/rest/v1/rpc/',API='sb_publishable_GIyyWoyaQXipaA4S9OuTyQ_cZn7LUgV';
let filter='open',selectedId='',pushToken=sessionStorage.getItem('kathleenPushAdminToken')||'';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const uid=(p='id')=>p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),pad=n=>String(n).padStart(2,'0');
const nowIso=()=>new Date().toISOString();
function load(){return window.KathleenTodoStore?.load?.()||[]}
async function save(a){return window.KathleenTodoStore?.save?.(a)||a}
function find(id=selectedId){return load().find(x=>String(x.id)===String(id))||null}
function dateKey(d){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}
function state(x){if(x.done)return'done';if(!x.due)return'open';const d=new Date(x.due),n=new Date(),tom=new Date(n);tom.setDate(n.getDate()+1);if(d<n)return'overdue';if(dateKey(d)===dateKey(n))return'today';if(dateKey(d)===dateKey(tom))return'tomorrow';return'future'}
function dueText(v){if(!v)return'Kein Fälligkeitsdatum';const d=new Date(v);return Number.isNaN(d.getTime())?'Kein Fälligkeitsdatum':d.toLocaleString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
function toInput(v){if(!v)return'';const d=new Date(v);return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())+'T'+pad(d.getHours())+':'+pad(d.getMinutes())}
function classes(){try{const a=window.KathleenClassLists?.classMeta?.();if(Array.isArray(a)&&a.length)return a}catch(e){}try{const a=JSON.parse(localStorage.getItem('kathleenClassMetaV1')||'[]');return Array.isArray(a)?a:[]}catch(e){return[]}}
function updateFilterOptions(){const all=load(),cs=classes(),subjects=[...new Set(all.map(x=>x.subject).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'de'));const cf=$('#classFilter'),sf=$('#subjectFilter'),oldC=cf.value||'all',oldS=sf.value||'all';cf.innerHTML='<option value="all">Alle Klassen</option>'+cs.map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name)+'</option>').join('');sf.innerHTML='<option value="all">Alle Fächer</option>'+subjects.map(s=>'<option value="'+esc(s)+'">'+esc(s)+'</option>').join('');if([...cf.options].some(o=>o.value===oldC))cf.value=oldC;if([...sf.options].some(o=>o.value===oldS))sf.value=oldS}
function matches(x){const q=$('#search').value.trim().toLocaleLowerCase('de'),cf=$('#classFilter').value,sf=$('#subjectFilter').value,pf=$('#priorityFilter').value,st=state(x),filterOk=filter==='all'||(filter==='open'&&!x.done)||(filter==='today'&&st==='today')||(filter==='upcoming'&&['tomorrow','future'].includes(st))||(filter==='overdue'&&st==='overdue')||(filter==='done'&&x.done);const search=[x.text,x.subject,x.notes,...(x.classNames||[]),...(x.steps||[]).map(s=>s.text),...(x.materials||[]).map(m=>m.title)].join(' ').toLocaleLowerCase('de');return filterOk&&(!q||search.includes(q))&&(cf==='all'||(x.classIds||[]).map(String).includes(String(cf)))&&(sf==='all'||x.subject===sf)&&(pf==='all'||x.priority===pf)}
function sortTasks(a,b){if(a.done!==b.done)return a.done?1:-1;const rank={overdue:0,today:1,tomorrow:2,future:3,open:4,done:5},sa=rank[state(a)]??9,sb=rank[state(b)]??9;if(sa!==sb)return sa-sb;if(a.important!==b.important)return a.important?-1:1;if(a.priority!==b.priority)return({high:0,normal:1,low:2}[a.priority]??1)-({high:0,normal:1,low:2}[b.priority]??1);return String(a.due||'9999').localeCompare(String(b.due||'9999'))}
function stats(){const a=load();$('#statOpen').textContent=a.filter(x=>!x.done).length;$('#statToday').textContent=a.filter(x=>state(x)==='today').length;$('#statOverdue').textContent=a.filter(x=>state(x)==='overdue').length;$('#statDone').textContent=a.filter(x=>x.done).length}
function renderList(){updateFilterOptions();stats();const arr=load().filter(matches).sort(sortTasks),box=$('#todoList69');$('#listCount').textContent=arr.length+' Aufgabe'+(arr.length===1?'':'n');if(!arr.length){box.innerHTML='<div class="todo69-empty"><strong>Nichts offen.</strong><span>Hier erscheinen deine passenden Aufgaben.</span></div>';return}box.innerHTML=arr.map(x=>{const steps=x.steps||[],done=steps.filter(s=>s.done).length,mats=(x.materials||[]).length,st=state(x);return '<article class="todo69-row '+(selectedId===x.id?'active ':'')+st+' '+(x.done?'done ':'')+'" data-id="'+esc(x.id)+'"><button class="todo69-check '+(x.done?'checked':'')+'" data-check="'+esc(x.id)+'" aria-label="Erledigt">'+(x.done?'✓':'')+'</button><div class="todo69-rowbody"><div class="todo69-rowtitle">'+esc(x.text||'Neue Aufgabe')+'</div><div class="todo69-rowmeta">'+(x.due?'<span class="'+(st==='overdue'?'danger':'')+'">◷ '+esc(dueText(x.due))+'</span>':'')+(x.classNames?.length?'<span>👥 '+esc(x.classNames.join(', '))+'</span>':'')+(x.subject?'<span>'+esc(x.subject)+'</span>':'')+(steps.length?'<span>☑ '+done+'/'+steps.length+' Schritte</span>':'')+(mats?'<span>📎 '+mats+' Material'+(mats===1?'':'ien')+'</span>':'')+'</div></div><button class="todo69-star '+(x.important?'on':'')+'" data-star="'+esc(x.id)+'" title="Wichtig">☆</button></article>'}).join('');$$('[data-id]').forEach(r=>r.addEventListener('click',e=>{if(e.target.closest('[data-check],[data-star]'))return;select(r.dataset.id)}));$$('[data-check]').forEach(b=>b.onclick=()=>toggleDone(b.dataset.check));$$('[data-star]').forEach(b=>b.onclick=()=>toggleImportant(b.dataset.star))}
function detailEmpty(){const d=$('#todoDetail69');d.className='todo69-detail empty';d.innerHTML='<div class="todo69-detail-empty"><div>✓</div><strong>Aufgabe auswählen</strong><span>Details, Schritte, Material und Notizen erscheinen hier.</span></div>'}
function classChecks(x){const ids=new Set((x.classIds||[]).map(String));return classes().map(c=>'<label class="todo69-classcheck"><input type="checkbox" value="'+esc(c.id)+'" data-name="'+esc(c.name)+'" '+(ids.has(String(c.id))?'checked':'')+'> <span>'+esc(c.name)+'</span></label>').join('')||'<span class="todo69-muted">Noch keine Klassenliste verfügbar.</span>'}
function renderDetail(){const x=find();if(!x){selectedId='';detailEmpty();return}const d=$('#todoDetail69'),steps=x.steps||[],materials=x.materials||[],stepDone=steps.filter(s=>s.done).length;d.className='todo69-detail';d.innerHTML='<div class="todo69-detail-top"><button class="todo69-circle '+(x.done?'done':'')+'" id="detailDone">'+(x.done?'✓':'')+'</button><textarea id="detailTitle" rows="1" maxlength="300">'+esc(x.text)+'</textarea><button class="todo69-bigstar '+(x.important?'on':'')+'" id="detailStar" title="Wichtig">☆</button><button class="todo69-close" id="detailClose">×</button></div>'+ 
'<section class="todo69-section"><div class="todo69-section-head"><strong>Schritte</strong><span>'+stepDone+'/'+steps.length+(steps.length?' erledigt':'')+'</span></div><div class="todo69-steps" id="stepList">'+steps.map(s=>'<div class="todo69-step '+(s.done?'done':'')+'"><input type="checkbox" data-step-check="'+esc(s.id)+'" '+(s.done?'checked':'')+'><input class="todo69-steptext" data-step-text="'+esc(s.id)+'" value="'+esc(s.text)+'"><button data-step-del="'+esc(s.id)+'">×</button></div>').join('')+'</div><div class="todo69-addline"><span>＋</span><input id="newStep" placeholder="Schritt hinzufügen"></div></section>'+ 
'<section class="todo69-section todo69-properties"><label><span>◷</span><input id="detailDue" type="datetime-local" value="'+esc(toInput(x.due))+'"></label><label><span>↻</span><select id="detailRepeat"><option value="none">Nicht wiederholen</option><option value="daily">Täglich</option><option value="weekdays">Werktags</option><option value="weekly">Wöchentlich</option></select></label><label><span>🔔</span><select id="detailPush"><option value="0">Keine Erinnerung</option><option value="1">Push zum Termin</option></select></label><label><span>◇</span><select id="detailPriority"><option value="normal">Priorität: normal</option><option value="high">Priorität: hoch</option><option value="low">Priorität: niedrig</option></select></label><label><span>📚</span><input id="detailSubject" list="todoSubjects69" placeholder="Fach" value="'+esc(x.subject||'')+'"><datalist id="todoSubjects69"><option value="Englisch"><option value="Geschichte"></datalist></label></section>'+ 
'<section class="todo69-section"><div class="todo69-section-head"><strong>Klassen</strong><span>Mehrfachauswahl möglich</span></div><div class="todo69-classes" id="detailClasses">'+classChecks(x)+'</div></section>'+ 
'<section class="todo69-section"><div class="todo69-section-head"><strong>Material</strong><a href="../../#library" target="_blank">Material & Aufgaben öffnen ↗</a></div><div class="todo69-materials">'+materials.map(m=>'<div class="todo69-material"><span class="todo69-fileicon">'+(m.type==='material'?'▤':'↗')+'</span><a href="'+esc(m.href||'#')+'" '+(m.href?'target="_blank"':'')+'><b>'+esc(m.title)+'</b><small>'+esc(m.href||'Nur Referenz')+'</small></a><button data-material-del="'+esc(m.id)+'">×</button></div>').join('')+'</div><div class="todo69-material-add"><input id="materialTitle" placeholder="Materialtitel"><input id="materialHref" placeholder="Link oder Pfad, z. B. ../../#library"><button id="materialAdd">＋</button></div><div class="todo69-material-hint">Material wird als Verknüpfung gespeichert – Dateien werden nicht dupliziert.</div></section>'+ 
'<section class="todo69-section"><div class="todo69-section-head"><strong>Notizen</strong><span>für die Unterrichtsvorbereitung</span></div><textarea class="todo69-notes" id="detailNotes" placeholder="Notiz hinzufügen …">'+esc(x.notes||'')+'</textarea></section>'+ 
'<div class="todo69-detail-foot"><span>Erstellt '+new Date(x.createdAt).toLocaleDateString('de-DE')+'</span><button id="deleteTask">Aufgabe löschen</button></div>';
$('#detailRepeat').value=x.repeat||'none';$('#detailPush').value=x.push?'1':'0';$('#detailPriority').value=x.priority||'normal';bindDetail();setTimeout(autoGrowTitle,0)}
function select(id){selectedId=String(id);renderList();renderDetail();document.body.classList.add('todo69-detail-open')}
function autoGrowTitle(){const t=$('#detailTitle');if(t){t.style.height='auto';t.style.height=Math.min(120,t.scrollHeight)+'px'}}
async function mutate(id,fn,{render=true}={}){const a=load(),i=a.findIndex(x=>String(x.id)===String(id));if(i<0)return;const next=fn({...a[i],steps:[...(a[i].steps||[])],materials:[...(a[i].materials||[])]})||a[i];next.updatedAt=nowIso();a[i]=next;await save(a);if(render){renderList();if(String(id)===String(selectedId))renderDetail()}}
async function toggleDone(id){const x=find(id);if(!x)return;await mutate(id,o=>{o.done=!o.done;return o});}
async function toggleImportant(id){await mutate(id,o=>{o.important=!o.important;if(o.important&&o.priority==='low')o.priority='normal';return o})}
function bindDetail(){const x=find();if(!x)return;$('#detailClose').onclick=()=>{selectedId='';document.body.classList.remove('todo69-detail-open');renderList();detailEmpty()};$('#detailDone').onclick=()=>toggleDone(x.id);$('#detailStar').onclick=()=>toggleImportant(x.id);const title=$('#detailTitle');title.oninput=autoGrowTitle;title.onblur=()=>{const v=title.value.trim();if(v&&v!==x.text)mutate(x.id,o=>{o.text=v;return o})};
$('#newStep').addEventListener('keydown',e=>{if(e.key!=='Enter')return;e.preventDefault();const v=e.target.value.trim();if(!v)return;mutate(x.id,o=>{o.steps.push({id:uid('step'),text:v,done:false,createdAt:nowIso(),updatedAt:nowIso()});return o})});$$('[data-step-check]').forEach(c=>c.onchange=()=>mutate(x.id,o=>{const s=o.steps.find(q=>q.id===c.dataset.stepCheck);if(s){s.done=c.checked;s.updatedAt=nowIso()}return o}));$$('[data-step-text]').forEach(t=>t.onblur=()=>{const v=t.value.trim();if(!v)return;mutate(x.id,o=>{const s=o.steps.find(q=>q.id===t.dataset.stepText);if(s){s.text=v;s.updatedAt=nowIso()}return o})});$$('[data-step-del]').forEach(b=>b.onclick=()=>mutate(x.id,o=>{o.steps=o.steps.filter(s=>s.id!==b.dataset.stepDel);return o}));
$('#materialAdd').onclick=()=>{const title=$('#materialTitle').value.trim(),href=$('#materialHref').value.trim();if(!title&&!href)return;mutate(x.id,o=>{o.materials.push({id:uid('mat'),title:title||href,href,type:href.includes('#library')?'material':'link',sourceId:'',createdAt:nowIso()});return o})};$('#materialHref').addEventListener('keydown',e=>{if(e.key==='Enter')$('#materialAdd').click()});$$('[data-material-del]').forEach(b=>b.onclick=()=>mutate(x.id,o=>{o.materials=o.materials.filter(m=>m.id!==b.dataset.materialDel);return o}));
$('#detailNotes').onblur=e=>{if(e.target.value!==x.notes)mutate(x.id,o=>{o.notes=e.target.value;return o})};$('#detailSubject').onchange=e=>mutate(x.id,o=>{o.subject=e.target.value.trim();return o});$('#detailPriority').onchange=e=>mutate(x.id,o=>{o.priority=e.target.value;return o});$('#detailRepeat').onchange=e=>updateReminderFields(x.id);$('#detailDue').onchange=()=>updateReminderFields(x.id);$('#detailPush').onchange=()=>updateReminderFields(x.id);$('#detailClasses').querySelectorAll('input').forEach(i=>i.onchange=()=>mutate(x.id,o=>{const checked=[...$('#detailClasses').querySelectorAll('input:checked')];o.classIds=checked.map(c=>c.value);o.classNames=checked.map(c=>c.dataset.name);o.classId=o.classIds[0]||'';o.className=o.classNames[0]||'';return o}));$('#deleteTask').onclick=()=>removeTask(x.id)}
async function rpc(name,body){const r=await fetch(SB+name,{method:'POST',headers:{apikey:API,'Content-Type':'application/json'},body:JSON.stringify(body||{})});if(!r.ok)throw Error(await r.text());return r.json()}
async function issuePushToken(){let pass=sessionStorage.getItem('kathleenAdminPass')||'';if(!pass){pass=prompt('Kisten-Adminpasswort für Push-Erinnerungen:')||'';if(!pass)throw Error('Kein Passwort')}const token=await rpc('teacher_push_issue_token',{p_passphrase:pass});if(!token){sessionStorage.removeItem('kathleenAdminPass');throw Error('Admin-Passwort falsch')}sessionStorage.setItem('kathleenAdminPass',pass);pushToken=String(token);sessionStorage.setItem('kathleenPushAdminToken',pushToken);return pushToken}
async function edge(action,payload={},retry=true){if(!pushToken)await issuePushToken();const r=await fetch(EDGE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload,adminToken:pushToken})});let d={};try{d=await r.json()}catch(e){}if(r.status===401&&retry){pushToken='';sessionStorage.removeItem('kathleenPushAdminToken');return edge(action,payload,false)}if(!r.ok||d?.ok===false)throw Error(d?.error||('HTTP '+r.status));return d}
async function cancelReminder(x){if(!x?.pushReminderId)return;try{await edge('cancel',{id:x.pushReminderId})}catch(e){console.warn('Reminder konnte nicht gelöscht werden',e)}}
async function scheduleReminder(x){if(!x.push||!x.due)return'';const d=new Date(x.due);if(Number.isNaN(d.getTime())||d<=new Date())return'';const res=await edge('schedule',{title:'To-do: '+x.text,body:[(x.classNames||[]).join(', '),x.subject].filter(Boolean).join(' · ')||'Kathleens Kiste',scheduledFor:d.toISOString(),recurrence:x.repeat||'none',url:'./tools/todos/',timezone:'Europe/Berlin'});return String(res.id||'')}
async function updateReminderFields(id){const current=find(id);if(!current)return;const due=$('#detailDue').value?new Date($('#detailDue').value).toISOString():'',repeat=$('#detailRepeat').value,push=$('#detailPush').value==='1';try{if(current.pushReminderId)await cancelReminder(current);let reminder='';const next={...current,due,repeat,push,pushReminderId:'',updatedAt:nowIso()};if(push&&due)reminder=await scheduleReminder(next);next.pushReminderId=reminder;const a=load(),i=a.findIndex(q=>q.id===id);if(i>=0){a[i]=next;await save(a)}renderList();renderDetail()}catch(e){alert('Push-Erinnerung konnte nicht gespeichert werden. Termin wurde ohne Push übernommen.');await mutate(id,o=>{o.due=due;o.repeat=repeat;o.push=false;o.pushReminderId='';return o})}}
async function removeTask(id){const x=find(id);if(!x)return;if(!confirm('Diese Aufgabe wirklich löschen?'))return;if(x.pushReminderId)await cancelReminder(x);await save(load().filter(q=>q.id!==id));selectedId='';document.body.classList.remove('todo69-detail-open');renderList();detailEmpty()}
async function newTask(){const g=window.KathleenClassLists?.getGlobalClass?.(),x={id:uid('todo'),text:'Neue Aufgabe',done:false,important:false,classIds:g?.id?[String(g.id)]:[],classNames:g?.name?[String(g.name)]:[],classId:g?.id||'',className:g?.name||'',subject:window.KathleenLessonMode?.get?.()?.subject||'',due:'',priority:'normal',repeat:'none',push:false,pushReminderId:'',notes:'',steps:[],materials:[],createdAt:nowIso(),updatedAt:nowIso()},a=load();a.unshift(x);await save(a);filter='open';syncTabs();select(x.id);setTimeout(()=>{$('#detailTitle')?.select()},50)}
function syncTabs(){$$('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter))}
async function syncCloud(){const btn=$('#syncBtn'),stateEl=$('#syncState');let pass=sessionStorage.getItem('kathleenAdminPass')||'';if(!pass){pass=prompt('Kisten-Adminpasswort für die verschlüsselte To-do-Synchronisierung:')||'';if(!pass)return;sessionStorage.setItem('kathleenAdminPass',pass)}btn.disabled=true;btn.textContent='☁︎ Synchronisiere …';try{const remote=await window.KathleenTodoStore.cloudPull(pass),all=window.KathleenTodoStore.merge(load(),remote);await window.KathleenTodoStore.save(all);if(!await window.KathleenTodoStore.cloudPush(all,pass))throw Error('Push fehlgeschlagen');btn.textContent='☁︎ Synchronisiert ✓';stateEl.textContent='Stand wurde verschlüsselt abgeglichen.';setTimeout(()=>btn.textContent='☁︎ Synchronisieren',1800);renderList();renderDetail()}catch(e){sessionStorage.removeItem('kathleenAdminPass');btn.textContent='☁︎ Synchronisieren';stateEl.textContent='Synchronisierung fehlgeschlagen.';alert('To-do-Sync fehlgeschlagen. Bitte Admin-Passwort prüfen.')}finally{btn.disabled=false}}
function init(){updateFilterOptions();renderList();detailEmpty();$('#newBtn').onclick=newTask;$('#syncBtn').onclick=syncCloud;['search','classFilter','subjectFilter','priorityFilter'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',renderList));$$('#tabs button').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;syncTabs();renderList()});window.addEventListener('storage',e=>{if(e.key==='kathleen-home-todos-v1'){renderList();renderDetail()}});window.addEventListener('kathleen:todos',()=>{renderList();if(selectedId)renderDetail()});window.addEventListener('kathleen:todos-ready',()=>{renderList();if(selectedId)renderDetail()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();